netlify/cli

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE
=> Add missing project management files.

README.md
time to start work on deprecating this.  This is a soft announcement since there's no new doc on our site yet which is kinda required before we can fully deprecate.
=> deprecatin'

.eslintrc.json, package.json, src/index.js
=> Add update notifier

src/commands/status/hooks.js, src/commands/status/index.js, src/utils/init/config-github.js
Closes https://github.com/netlify/cli/issues/62
=> Create Github deploy notifications on init

docs/commands/deploy.md, src/commands/deploy.js, src/utils/api/deploy/index.js
This adds a drafts deploys flag that works. Closes #84
=> Add draft deploys

src/commands/watch.js, src/utils/header.js
Closes https://github.com/netlify/cli/issues/82
=> Improve watch copy

package.json, src/utils/header.js
=> improve header output

netlify.toml, src/base/index.js, src/commands/init.js, src/commands/link.js, src/commands/logout.js, src/commands/sites/create.js, src/commands/unlink.js, src/hooks/init.js, src/utils/init/config-github.js, src/utils/link/link-by-prompt.js, src/utils/telemetry/index.js
=> install base modules

README.md, docs/commands/open.md, docs/commands/sites.md, docs/commands/watch.md, src/commands/deploy.js, src/commands/init.js, src/commands/link.js, src/commands/unlink.js
Update docs and final bits and bobs for beta release
=> updates beta release

package.json, src/commands/deploy.js
Closes https://github.com/netlify/cli/issues/37
=> Add the ability to add deploy messages

src/commands/deploy.js, src/commands/init.js
Added a create site/link prompt and prompt for deploy folder.  Also fixed some path relsotion bugs.
=> Improve init flow on deploy command

src/base/utils/projectRoot.js
Fix project resolution when no git repo or netlify.toml file is found.
=> Implement improved project resolution algorithm

README.md, docs/commands/deploy.md, docs/commands/index.md, docs/commands/sites.md, scripts/docs.js, site/src/_layout.js, src/commands/deploy.js
=> Doc strings tweaks

src/commands/logout.js
**- Summary**
Since we started going down the multi-user path, logout doesn’t actually log you out (tokens are still in the config file).  We should prioritize getting user switching in soon after the launch.
This is just an oclif setting.  No testing nessisary.
Hide logout command until user switching is added.
=> Hide logout command

src/base/utils/project-root.js
Closes https://github.com/netlify/cli/issues/145
=> Handle type error in project-root algorithm

src/commands/deploy.js
**- Summary**
Fix missing `site_id` error when deploying a new site
Fixes missing `site_id` error when deploying a new site
🐈 How about an emoji? 🐕
closes #163
=> Fix missing site_id error

src/commands/init.js
Closes https://github.com/netlify/cli/issues/151
=> Handle GitHub error better when user lacks perms

package.json
=> Update ESLint plugin

src/commands/deploy.js
**- Summary**
This is a minor edit to improve the consistency of CLI prompts
n/a
n/a
=> Update CLI prompts for more consistent style

src/base/index.js, src/commands/login.js
This allows users to set NETLIFY_WEB_UI to set the login url thats opened when logging in.
=> Allow users to set the login url in the auth flow

package.json
Update API client to 2.2.1 to help address https://github.com/netlify/cli/issues/161#issuecomment-433201317
=> Update Netlify API client to 2.2.1

.gitignore, package-lock.json, package.json
Use a lock file instead of shrink-wrapping on publish.
=> Use a package-lock file instead of shrink-wrap strategy

package-lock.json, package.json
A few updates for dependencies.
=> Chore: Updates

package-lock.json, package.json
**- Summary**
This will allow us to develop plugins without
having to add every single command to this repository.
See: https://github.com/oclif/plugin-plugins
As we add more functionality to the CLI, it doesn't make sense to add 
every single command to this repository. Using Oclif Plugins will allow 
us and other people to add functionality to the CLI without having to 
wait for Netlify to build it.
There is nothing to test at this moment.
Allow external plugins by using Oclif's Plugins system.
=> Add oclif help and plugins plugin.

src/index.js
This does a couple of things:
- Check for updates a bit more frequently
- Warn when there are errors during update
=> Update check improvements

src/commands/addons/create.js, src/commands/addons/delete.js, src/commands/addons/list.js, src/commands/addons/update.js, src/commands/init.js, src/commands/sites/list.js
**- Summary**
- add `-m` shorthand flag for `init` command
- add loading message to make `sites:list` feel faster
🐎
closes #73
=> Output and feedback enhancements

src/utils/parseRawFlags.js
This adds a naive json parsing algorithm to the addons command.
=> Add simple JSON parsing to parse raw for addons commands

src/commands/addons/index.js, src/commands/addons/show.js
This command lets you see the current config of a given addon namespace.
=> Add addons:show command

src/utils/gh-auth.js
**- Summary**
Fix method not found in @octokit/rest
ref: https://octokit.github.io/rest.js/#api-OauthAuthorizations-createAuthorization
fixes #199
none
* fix(auth): github token error because api change in @octokit/rest
none
=> fix(auth): due to api change in @octokit/rest

package-lock.json, package.json
This plugin is oclif's solution to autocomplete right now.  Some may
want to take advantage of that and this allows them to do that.
=> Add @oclif/plugin-autocomplete plugin

package.json
Resolves https://github.com/netlify/cli/issues/204
It wasn’t working very well.  We can revisit when oclif improves autocomplete or we really want to implement it ourselves.
=> Remove autocomplete plugin

package-lock.json, package.json, src/base/index.js
Update Netlify js client to support rate limiting.
See https://github.com/netlify/cli/issues/206
=> Fix rate limiting handing

package-lock.json, package.json
Update js-client to fix rate limit handling.
=> Update js-client to fix rate limit handling

package.json, src/commands/deploy.js
Fix for even more upload failure scenarios.
Closes https://github.com/netlify/cli/issues/206
=> Even more upload fixes

.gitignore, package-lock.json, package.json
Closes https://github.com/netlify/cli/issues/234
=> Publish with a shrink-wrap file again

src/commands/deploy.js
Closes https://github.com/netlify/cli/issues/209
=> Fix function config lookup in netlify.toml

src/commands/addons/create.js
**- Summary**
- Use Array.prototype.find rather than Array.prototype.reduce
- Remove dead code
I've tested that code with a new addon
=> Minor cleanup to addons:create

npm-shrinkwrap.json, package.json
Update netlify's js-client and semver floors.
* "@iarna/toml": "^2.2.3",
* "netlify": "^2.4.0",
* "@oclif/dev-cli": "^1.21.1",
* "dependency-cruiser": "^4.13.2",
=> Update netlify's js-client and semver ranges

azure-pipelines-template.yml, azure-pipelines.yml
=> Update azure-pipelines.yml for Azure Pipelines

npm-shrinkwrap.json
Update zip-it-and-ship-it to 0.2.2 and also update transient deps.
=> Update zip-it-and-ship-it to 0.2.2

src/commands/addons/delete.js, src/commands/sites/delete.js
**- Summary**
closes https://github.com/netlify/cli/issues/270
tested locally
Ask for confirmation before destructive actions (delete addons, and infuture, delete sites)
=> confirm before doing destructive actions

src/utils/init/config-manual.js, src/utils/init/netlify-toml-template.js
**- Summary**
we only had it on github init previously
netlify toml templating is now available on manual init
:octocat:
=> Update netlify toml template and bring it to manual init as well

package.json, src/commands/sites/delete.js
Closes https://github.com/netlify/cli/issues/293
=> Repair tests

package.json
**- Summary**
- Fixes an error throw on login after the teams pricing changes.
Tests passing in cli-utils.
- Update cli-utils to ^1.0.2
=> Update cli-utils to ^1.0.2

npm-shrinkwrap.json, package.json
Fixes some underlying bugs when bundling functions without a pacakge.json in the project.
=> Update Zip-it-and-ship-it to 0.3.1

docs/commands/index.md
Fixes side nav header and adds https://5cc0f8b045706e0008e004a8--cli.netlify.com/commands/
=> add command index base page

src/commands/init.js, src/commands/link.js
**- Summary**
Some changes to the text in `init` and `link` commands.
To see the new text:
* Run `netlify init`
* Run `netlify link`
Changed text in `init.js` and `link.js`
=> Some grammar fixes

src/utils/get-repo-data.js, src/utils/link/link-by-prompt.js
**- Summary**
Return the parsed `host` of the git repo. And use it in provider url construction.
Fixes: https://github.com/netlify/cli/issues/331
* Add a `host` field to `getRepoData` function with repo `host` as value
* Use the `host` field from `getRepoData` to build a repo URL
=> getRepoDate: Fix host

docs/commands/functions.md, npm-shrinkwrap.json, package.json, src/commands/login.js, src/commands/logout.js, src/commands/status/index.js
Bump CLI utils to fix https://github.com/netlify/cli/issues/353
Related https://github.com/netlify/cli-utils/pull/11
=> Make all command honor process.env.NETLIFY_AUTH_TOKEN

npm-shrinkwrap.json, package.json
Fix https://github.com/netlify/cli/issues/356
=> update util dep

npm-shrinkwrap.json, package.json
Fix https://github.com/netlify/cli/issues/359
=> bump dev plugin

CONTRIBUTING.md
Ensure npm deps are correct before publish
=> add release checklist notes

.circleci/config.yml, src/tests/addons.test.js
**- Summary**
Testing CircleCI
=> Deployment changes

src/commands/status/index.js
Update `--json` for `netlify status --json`
```
{
"account": {
"Name": "David Wells",
"Email": "hello@email.io",
"Github": "DavidWells",
"Teams": {
....
}
},
"siteData": {
"site-name": "cli",
"config-path": "/Users/xyx/Netlify/repos/cli/netlify.toml",
"admin-url": "https://app.netlify.com/sites/xzy",
"site-url": "https://cli.netlify.com",
"site-id": "d3807379-www-4a43-eeeee-e7e8d90ecf70"
}
}
```
=> add json output with siteId

package-lock.json, src/commands/status/index.js
```
netlify status --verbose
```
=> refactor: update status verbose flag

.github/ISSUE_TEMPLATE.md
**- Summary**
Updated the issue template to show up `netlify status --info` instead.
N/A
Updated the issue template to show up `netlify status --info` instead.
=> chore: Minor fix

src/commands/dev/index.js, src/utils/serve-functions.js
**- Summary**
Fixes: https://github.com/netlify/netlify-dev-plugin/issues/215
Adds `client-ip` header to functions request to mimic the behavior on production.
* Create a function with following handler:
```
exports.handler = async (event, context) => {
return {
statusCode: 200,
body: JSON.stringify({
event,
})
};
};
```
* Run `netlify dev` in the project
* Make http request for function path and inspect `client-ip` in response as part of `headers` object
* Add `x-forwarded-for` header which represents `connection.remoteAddress` to proxy request to functions server
* Use `x-forwarded-for` or `request.connection.remoteAddress` to derive value for `client-ip` header
=> Functions: Add client-ip header to request

src/utils/serve-functions.js
**- Summary**
Fixes: https://github.com/netlify/netlify-dev-plugin/issues/185
Corrects the `isBase64Encoded` parameter in function event object.
* Create a function with following handler:
```
exports.handler = async (event, context) => {
return {
statusCode: 200,
body: JSON.stringify({
isBase64Encoded: event.isBase64Encoded,
})
};
};
```
* POST a form or file that is not base64 encoded, e.g. a key value form submitted from browser and observe the output
* POST another form with complex values like an image and some text data and observe the output
* Take string value of `request.body` as base value
* Use `Buffer` class to compare a `base64` encoded form of the body with original base value
* Use the result of comparison to set …
=> Functions: Fix isBase64Encoded

src/utils/serve-functions.js
**- Summary**
Add support for multi-value headers. Ref: https://github.com/netlify/netlify-lambda/pull/181
Loop through the `lambdaResponse.multiValueHeaders` and set them on our proxy response.
=> Functions: Add support for multi-value headers

package-lock.json, package.json, src/commands/sites/create.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/385
Logs site data as JSON when `--json` flag is passed to `sites:create`
`netlify sites:create --json`
* Import `lodash.pick`
* Pick compact and meaningful properties from `site` object and display them
=> sites:create Fix JSON log

docs/commands/deploy.md, src/commands/deploy.js
**- Summary**
Add a new flag (`-p`) to `netlify deploy` to allow users to configure timeout for deployments.
* Run `netlify deploy -p 5`
* Expect to error out if deployment takes more than five seconds
* Add new flag (`--timeout`) to `deploy` command
🐶
=> Deploy: Add a timeout flag

src/commands/deploy.js
**- Summary**
make functions folder existence optional for netlify deploy
make functions folder existence optional for netlify deploy
🦉
=> make functions folder existence optional for netlify deploy

src/functions-templates/js/slack-rate-limit/.netlify-function-template.js, src/functions-templates/js/slack-rate-limit/package.json
**- Summary**
```
❯❯❯ netlify functions:create
```
`slack-rate-limit` should have the typo fixed.
Fix typo in slack-rate-limit description
=> Neltify -> Netlify

src/commands/deploy.js
closes https://github.com/netlify/cli/issues/507
=> rename deploy path 

src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/450
Fixes: https://github.com/netlify/cli/issues/424
=> Rules Proxy: Pass on query parameters

src/commands/functions/create.js, src/commands/functions/invoke.js, src/functions-templates/js/fauna-graphql/fauna-graphql.js, src/functions-templates/js/graphql-gateway/graphql-gateway.js, src/utils/serve-functions.js
**- Summary**
I've fixed some `no-unused-vars` warnings from eslint.
Delete unnecessary variables.
=> Fix: Fixing some no-unused-vars warnings from eslint

src/commands/dev/index.js, src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/517
Fixes: https://github.com/netlify/cli/issues/432
Fix the logic to check if a static file for given URL exists.
`netlify.toml`:
```
[[redirects]]
from = "/"
to = "/home"
status = 200
```
* Ensure a file exists in /static/home/index.html
* run `netlify dev`
* browse to http://localhost:8888
* Move `alternativePathsFor` function from `dev` command `index.js` to `rules-proxy.js`
* Use `alternativePathsFor` to check if a path has static file before calling `next()`
🐥
=> Dev: Try static files before deciding on redirect

src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/450
`netlify.toml`:
```
[[redirects]]
from = "/"
to = "/ding/:path"
status = 200
query = {path = ":path"}
```
* Run `netlify dev`
* Vist http://localhost:8888/?path=ding in browser
* Observe `Rewrote URL to  /ding/ding` in terminal
* Update `matchReq` to match the specification
* Remove `?` from beginning of `matchReq.query`
* Use `match.to` when rewriting the URL
🦆
=> Dev: Fix redirects with query constraints

src/commands/dev/index.js, src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/373
Fixes: https://github.com/netlify/cli/issues/415
1. Create a site with the following redirect rule specified in the netlify.toml:
```
[[redirects]]
from = "/posts/*"
to = "/no-post-found.html"
status = 404
```
2. Serve a site locally under `netlify dev` which includes:
- at least on page within the `/posts/` directory
- a page such as `/no-post-found.html` to serve as a 404
3. Navigate to a correct URL within the `/posts/` directory and it should display the page correctly
4. Navigate to a URL of non-existing file within the `/posts/` directory and it should display the contents of `/no-post-found.html`
* Move the routing part out of rule proxy and just use it to create a …
=> Dev: Fix 404 redirects

src/commands/dev/index.js, src/hooks/analytics.js, src/utils/rules-proxy.js, src/utils/telemetry/index.js, src/utils/telemetry/request.js
**- Summary**
Some files were not prettified.
Fix prettier.
=> Fix prettier

.eslintrc.json, package-lock.json, package.json, scripts/docs.js, scripts/generateCommandData.js, src/commands/dev/index.js, src/commands/functions/invoke.js, src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-2.js, src/functions-templates/js/oauth-passport/package.json, src/functions-templates/js/slack-rate-limit/slack-rate-limit.js, src/functions-templates/js/stripe-subscription/stripe-subscription.js, src/functions-templates/js/token-hider/token-hider.js, src/functions-templates/js/url-shortener/generate-route.js, src/functions-templates/js/url-shortener/get-route.js, src/functions-templates/js/url-shortener/url-shortener.js, src/utils/addons/prompts.js, src/utils/detect-server.js, src/utils/read-repo-url.js, src/utils/redirect-parser/common.js
**- Summary**
This fixes linting. We have 100+ errors at the moment.
This also adds ESLint autofixing.
Fixes linting.
=> Fix linting

src/commands/api.js
=> Typo in error message

package-lock.json, package.json
=> Bump @netlify/build version

package-lock.json, package.json
This fixes some issues with `zip-it-and-ship-it`.
=> Bump `@netlify/build` version

src/function-builder-detectors/README.md
**- Summary**
These links were pointing to the archived netlify-dev-plugin repo.
/
/
🦁
=> Update code links to new repository

package-lock.json, package.json, src/commands/build/index.js
**- Summary**
This fixes a bug from `@netlify/config` thrown during configuration loading.
Fix configuration loading with `netlify build`
=> Fix configuration loading with `netlify build`

src/commands/dev/index.js
**- Summary**
Opens the dev server URL in default browser. Fixes: https://github.com/netlify/cli/issues/608
* `netlify dev` in a valid project
* Use `open` package to launch the dev server URL in default browser.
🐶
=> Open URL on netlify dev

package-lock.json, package.json, src/commands/dev/index.js
**- Summary**
Cleans up the child processes run by `netflify dev` if it crashes. Fixes: https://github.com/netlify/cli/issues/580
* Create a syntax error in `netlify dev` codebase to simulate a hard crash [maybe here](https://github.com/netlify/cli/blob/a288984fb4ea68f0e80557c959e8f2d4cd291370/src/commands/dev/index.js#L436)
* Run `netlify dev`
* Run `ps` to see all the relevant processes exited successfully
* Fix the syntax error and run `netlify dev` again
* Get the process id of the process run by dev server (`yarn` or `npm` etc)
* Kill that process when `netlify dev` exits
* Kill any zombie process by the port number
👻
=> Fix zombie child proceses

src/commands/deploy.js
**- Summary**
Propagate `siteId` and `site.id` in `netlify deploy` logic after linking to site. Fixes: https://github.com/netlify/cli/issues/642
* `netlify deploy` in project without linking it to a site
* Link to existing site
You shouldn't see the error.
Propagate `siteId` and `site.id` in `netlify deploy` logic after linking to site.
🐠
=> Propagate siteId and site.id vars after linking

src/commands/functions/invoke.js
There's a check for `payload` a few lines above
=> Remove useless conditional

README.md, docs/commands/functions.md, docs/commands/index.md, docs/index.md, package.json, scripts/docs.js, site/package.json, src/commands/functions/build.js, src/commands/functions/create.js, src/commands/functions/invoke.js, src/commands/functions/list.js
Log "no functions" for `functions:list` if no functions found
Also adds `--json` output if flag supplied
=> Update function list command

src/utils/dev.js
=> Fix double space before env var name

src/commands/dev/index.js
fixes https://github.com/netlify/cli/issues/620
=> fill in proxyPort when detector is bypassed

src/commands/link.js, src/utils/link/link-by-prompt.js
fix: https://github.com/netlify/cli/issues/675
=> fix: https://github.com/netlify/cli/issues/675

package-lock.json, package.json, src/commands/dev/index.js
**- Summary**
The new changes use a different approach where we don't try to kill the processes and instead log the error and let the user terminate the `netlify dev` process which cleanly kills all of the child processes. The previous approach did not fix all of the issues and there were still some edge cases. This can serve as a good patch-fix until we can dedicate some time to solve this problem properly.
* `netlify dev` in your existing project
Dont try to kill the child processes, log the error and let the use exit.
=> Handle zombie processes differently

src/utils/command.js
Previously the codebase would proceed with a file not found, only for an error to be thrown by `path.join` later down the line. This validates the existence as early as can be
=> Validate existence of config file in command

src/detectors/nuxt.js
**- Summary**
Actually, `netlify dev` will try to run `nuxt start` instead of `nuxt` or `nuxt dev`
=> fix: update nuxt detector for netlify dev

src/detectors/gatsby.js
**- Summary**
Improves: https://github.com/netlify/cli/issues/698
* `netlify dev` in a Gatsby project
* Add `GATSBY_LOGGER=yurnalist` env var to Gastby detector
🐕
=> detectors: Add GATSBY_LOGGER env

.github/ISSUE_TEMPLATE.md
Is a change to the issue filing template, so no changes to functionality of code/tests should apply
=> asking for a bit more info and clarifying how to search the issues list

src/commands/api.js
=> [api] Add support for not passing the data flag when it is not needed

src/tests/addons.test.js
=> Tests: Dont asign NETLIFY_AUTH_TOKEN explicitly

src/detectors/angular.js
**- Summary**
Creates a detector that looks for an Angular workspace configuration file to identify it as an Angular project.
ran `dev`, `init`, and a few other cli commands to make sure nothing broke
Added a detector to distinguish Angular projects.
=> Adds angular detector

src/tests/dev.test.js, src/tests/dummy-site/functions/timeout.js, src/tests/dummy-site/netlify.toml, src/tests/dummy-site/package.json, src/utils/serve-functions.js
**- Summary**
Change timeout for Netlify Functions served via `netlify dev` to 10 seconds from the default 3 seconds.
Fixes: https://github.com/netlify/cli/issues/724
* Use `netlify dev` to run a function longer than 5 seconds
* Specify `timeoutMs` property on `execute` method of `lambda-local` and set it to `10 * 1000`
* Add tests for function timeout
🦁
=> Dev: Change functions timeout to 10s

package-lock.json, package.json
**- Summary**
There was a behavior mistake in `@netlify/config` which returned incorrect directory for deployment (`$ProjectDir/.netlify/build`) in some cases where it shouldn't have. The latest update in `@netlify/config` fixes that behavior and thus the issue.
Fixes: https://github.com/netlify/cli/issues/676
Fixes: https://github.com/netlify/cli/issues/667
* Create a blank project with an `index.html` file
* Run `netlify deploy` and choose to create new website
* Update `@netlify/config` to latest version
🐓
=> netlify deploy: Fix hang in certain situations

src/commands/dev/index.js
**- Summary**
In Netlify Dev, if a request was cancelled before server returned a response, it would result in a `socket hang up` error because the server would try to write to a broken (response) socket. This PR adds handling of the `error` event in proxy server to not crash when this happens and add a log to console.
Fixes: https://github.com/netlify/cli/issues/404
Follow instructions here: https://github.com/netlify/cli/issues/404#issuecomment-562037979
Add handling of `error` event in `http-proxy`, so that, we it doesn't throw an unhandled exception.
🦋
=> Netlify Dev: Protect against "socket hang up" errors

site/sync.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/741
Go to Commands page in the generated site and click any command header
Fix the regex that replaces `.md` links with non `.md`.
🐳
=> Docs: Fix 404 page for commands

src/commands/deploy.js
Hi folks 👋 
just had to spend quite some time tracking down a bug, which eventually happened because we set a wrong site id. If this error message had been in place, it could have save me quite a few hours.
=> fix(deploy): handle 404

src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/751
Try running `netlify dev` in https://github.com/tamouse/jamstack-intro-basic
Make sure `config.build.publish` is defined before string comparison.
🦁
=> Netlify Dev: Verify publish dir before comparing

src/commands/dev/index.js, src/tests/dummy-site/_headers, src/utils/headers.js, src/utils/headers.test.js, src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/446
Have the following file in your project root:
```
/templates/index.html
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
/templates/index2.html
X-Frame-Options: SAMEORIGIN
/*
cache-control: max-age=0
cache-control: no-cache
cache-control: no-store
cache-control: must-revalidate
```
Run `netlify dev`, make an http request to `/` and observe response headers.
* Add new function `parseHeadersFile`
* Watch for changes in `_headers` files in project root and dist directory
* Set headers defined in `_headers` files to responses
🦁
=> Add support for _headers files

src/commands/deploy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/175
`netlify deploy --trigger` on a existing project
* Add new `trigger` flag
* Call `api.createSiteBuild` when `trigger` is specified
🐶
=> Deploy: Add flag to trigger build

docs/netlify-dev.md, src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/438
Fixes: https://github.com/netlify/cli/issues/563
Specify `port` in your `netlify.toml`, like so:
```
[dev]
port = 2021
```
Run `netlify dev` and make sure it is running on port 2021 (if is is not in use by another process).
Run `netlify dev --port=2025` and verify that it's running on port 2025.
Reset `port`, `targetPort` and `functionsPort` on `settings` object with values from flags having the highest priority, then configuration file (`netlify.toml` etc) and then site detectors.
🦁
=> Make sure to respect port flags and configuration

src/commands/deploy.js, src/commands/init.js, src/commands/sites/create.js
**- Summary**
This PR fixes deprecation warnings on `error.code` (_except what seemed to be non-native error objects with the same `code` field_).
None.
Fix deprecation warnings on errors.
=> Fix deprecation on errors

docs/netlify-dev.md
**- Summary**
Fix typo: wold -> would.
=> Fix typo in Netlify Functions section.

src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/705
Add `index.html` and `404.html` as static files. Set `_redirects` to:
```
/*  /404.html  200
```
Navigate to `/index.html`. `404.html` will **not be displayed**.
Make sure to trim `/` from pathname when resolving path to check for static files.
🐵
=> Fix rewrite force behavior for static files

src/commands/dev/index.js
**- Summary**
Provide `process.env` as env for static server.
Run `netlify dev` with `--dir`
Pass `process.env` as `env` in static server settings.
🐳
=> Dev: Provide process.env as env to static server

docs/netlify-dev.md, src/commands/dev/index.js, src/utils/detect-server.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/767
Not elegant to look at but it's simple and does it's job.
Run two instances of `netlify dev -p 8888`
* Try to acquire `port`, and fail if not available and is specified in config or flags.
* Remove flag and config parameters for `functionsPort`
🐹
=> Dev: Revisit port specification options

src/tests/addons.test.js
**- Summary**
fixes #783 and partially #694 
addons.test.js contained someone's hardcoded account slug `netlify-services`.
So other users without access to this account couldn't pass the test.
For the first step I suggest to use one of existing user's accounts, which we can get using `netlify api listAccountsForUser` command. Later on account could be configured with some environment variable for example.
```
npm run ava -- src/tests/addons.test.js
```
Any suggestions?
=> fix: use existing user's account instead of hardcoded

package-lock.json, package.json
**- Summary**
Fixes: https://github.com/netlify/cli/issues/769
`npm i` in the CLI project directory
Upgrade `firebase` package
🦁
=> Upgrade firebase

src/functions-templates/js/sanity-create/.netlify-function-template.js, src/functions-templates/js/sanity-create/package.json, src/functions-templates/js/sanity-create/sanity-create.js, src/functions-templates/js/sanity-groq/.netlify-function-template.js, src/functions-templates/js/sanity-groq/package.json, src/functions-templates/js/sanity-groq/sanity-groq.js
**- Summary**
This PR adds 2 javascript function templates for creating and querying documents in Sanity.io. They can then be used by invoking `netlify functions:create`.
Netlify functions are a common (and good!) way of interacting with Sanity datasets, and it would help the community if there was an easy way to get started with them.
The templates have been tested by manually linking the npm package and running `netlify functions:create`.
Added function templates with examples of interacting with Sanity.io
=> Add js function templates for Sanity.io

src/commands/dev/index.js, src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/794
Described in https://github.com/netlify/cli/issues/794#issue-595896156
* Dont filter out index redirect rules for static server
* Try the bare pathname to check for static file
🐶
=> Dev: Fix index redirect for static files

src/commands/status/index.js
**- Summary**
Made `verbose` flag to show up local environment information which wasn't the case before.
closes #778
`--verbose` flag shows up information regarding the local environment when passed along with the `status` command.
=> fix: verbose flag displays the necessary information

src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/800
`netlify dev` in multiple static projects
Fallback to random port for static server. Still make sure that `--port` is respected.
🦋
=> Dev: Fallback port to random ports for static server

package-lock.json, package.json
**- Summary**
Upgrade `minimist` because of a vulnerability in the version we were using.
NA
* Upgrade `minimist`
* Delete `package-lock.json` and `npm install` again
🐰
=> Update minimist package

src/commands/dev/index.js
**- Summary**
🤦🏽‍♂️
We're using random port if none is requested specifically here: https://github.com/netlify/cli/compare/raees/port?expand=1#diff-8a2f65e3aede3ea9696e546766f50f03L440
Don't use random port on settings assignment
🤦🏽‍♂️
=> Dev: Don't use random "port" on settings assignment

package-lock.json, package.json
**- Summary**
Fixes: https://github.com/netlify/cli/issues/709
`netlify dev` and test redirect rules
Upgrade `netlify-redirector` to `0.2.0` which includes this PR https://github.com/netlify/libredirect/pull/88
🐠
=> Upgrade netlify-redirector

package-lock.json, package.json
This PR upgrades `@netlify/build` and `@netlify/config` in order to fix the issue reported in #809.
=> Fix `netlify build` crash

package-lock.json, package.json
**- Summary**
Ref: https://github.com/netlify/cli/issues/809
NA
Upgrade `netlify-redirect-parser`
☃️
=> Upgrade netlify-redirect-parser

src/utils/rules-proxy.js
=> Revert "Dev: Dont crash on no config file"

src/commands/dev/index.js
**- Summary**
Improve error message if the required command was not found in PATH.
=> Dev: Better error message if command bin not found

package-lock.json, package.json
This upgrades `@netlify/build`, `@netlify/config`, `@netlify/zip-it-and-ship-it` and `netlify` to the latest versions.
=> Upgrade Netlify Build

package-lock.json, package.json
**- Summary**
Not used anymore. Was causing two vulnerabilities.
Basic tests included.
Remove `dependency-cruiser`
🐼
=> Remove devDependency "dependency-cruiser"

src/commands/deploy.js, src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/509
=> Deploy: Replace live with better words

package-lock.json, package.json
This upgrades `netlify build` with the latest version of `@netlify/build` and `@netlify/config`.
=> Upgrades Netlify Build

src/commands/sites/create.js
**- Summary**
Updates the default domain for the site's name suggestion message during the creation process.
=> Use .app for the site's name suggestion message.

.github/workflows/main.yml, tests/cra.test.js
=> GitHub Actions debug

package-lock.json, package.json
**- Summary**
Fixes: https://github.com/netlify/cli/issues/872
* Upgrade `netlify-redirect-parser`
* Upgrade `@netlify/config`
🐼
=> Fix redirect parsing issues

package-lock.json, package.json, src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/886
* Run `netlify dev` in CRA project
* Upgrade `strip-ansi-control-characters`
🦖
=> Upgrade strip-ansi-control-characters

docs/netlify-dev.md, package-lock.json, package.json, site/package-lock.json, src/commands/dev/index.js, src/utils/detect-server.js, src/utils/detect-server.test.js
**- Summary**
Related to https://github.com/netlify/cli/issues/898
Fixes: https://github.com/netlify/cli/issues/901
* Improve logs in `serverSettings`
* Throw error if `port` or `targetPort` are not numbers
* Improve text description of `port` and `targetPort`
* Log when child process exits
🐰
=> Improve Netlify Dev config and docs

tests/cra.test.js, tests/dev.test.js
**- Summary**
Don't need to parse output to get port and host
=> Improve dev and CRA tests logic

docs/netlify-dev.md
**- Summary**
Fixes: https://github.com/netlify/cli/issues/916
=> Update Netlify Dev docs

src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/921
Described in https://github.com/netlify/cli/issues/921#issue-623615821
Set the query params before doing any redirect or rewrite
🐿
=> Dev: Pass query params in redirect and rewrites

docs/commands/sites.md
**- Summary**
corrected two incomplete command examples
=> Correction in docs

src/commands/dev/index.js, tests/dev.test.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/939
Tests added
Make sure the paths for alternatives files for shadowing do not contain query params.
=> Fix shadowing of files when request has query params

docs/netlify-dev.md
**- Summary**
I was unaware the functions were actually being served through the browser, I thought you had to interact with them through the command line.  While trying to find a way to interact with them through the browser I read the netlify-lambda docs and realized that netlify dev does serve the files in the browser, it's just not mentioned anywhere.
No need for tests, just updating the docs.
Include url where functions are served (/.netlify/functions/your-function)
=> Update Functions Docs to Include Functions Domain

src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/851
=> Dev: Dont force redirect on internal URL's

src/commands/deploy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/745
Test manually with large scale sites that fail with timeout
Set deployment `syncFileLimit: 1` to force an async deployment
🐠
=> Deploy: Force async on large deployments

src/utils/serve-functions.js, tests/dev.test.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/970
We were previously using `query` object provided by Express which turns out to parse URL query parameters incorrectly. The new approach uses native `URL` class to get the query parameters from the original request URL.
Test added
The new approach uses native `URL` class to get the query parameters from the original request URL.
🐥
=> Functions: Handle query parameters correctly

src/commands/functions/invoke.js
**- Summary**
This PR adds mocked response data that resembles the shape of `body.user` for identity functions in production, which I'd find helpful during development.
There are no tests since it's just a few lines.
=> Mock identity response with properly-shaped data

docs/netlify-dev.md
**- Summary**
Fix a couple of typos in the `netlify-dev` document that I came across when referencing the docs:
- Change `accissible` to `accessible` 👍 
- Change `wil` to `will` 👍 
- Change `that` to `they`?
- Fix typos in `netlify-dev.md`.
=> Fix typos in docs/netlify-dev.md

renovate.json
**- Summary**
Improves renovate bot config
Not needed
1. Use Netlify default
2. I found the default of `prHourlyLimit2` too strict especially when timing only [weekly updates](https://github.com/netlify/renovate-config/blob/81097c37d95e8c781b1d39a530fbd3b6bf872c13/default.json#L4)
3. `semanticCommits: true` to force semantic commit messages (otherwise the bot tries to auto detect).
4. `masterIssue: true` provides visibility into upcoming/pending updates. See https://github.com/netlify/netlify-lambda/issues/243 for example.
🐼
=> chore(deps): improve renovate config

.github/workflows/main.yml
This tests Netlify CLI on Node 14 in CI.
=> Test on Node 14

.github/workflows/main.yml
=> Revert "Test on Node 14"

.github/workflows/labeler.yml
Fixes https://github.com/netlify/cli/issues/1036
=> ci(chore): auto label PRs

package-lock.json, package.json
Fixes https://github.com/netlify/cli/issues/1038
=> chore(deps): remove unused dev dependencies

src/detectors/README.md, src/detectors/angular.js, src/detectors/brunch.js, src/detectors/create-react-app.js, src/detectors/docusaurus.js, src/detectors/eleventy.js, src/detectors/ember.js, src/detectors/expo.js, src/detectors/gatsby.js, src/detectors/gridsome.js, src/detectors/hexo.js, src/detectors/hugo.js, src/detectors/jekyll.js, src/detectors/middleman.js, src/detectors/next.js, src/detectors/nuxt.js, src/detectors/parcel.js, src/detectors/phenomic.js, src/detectors/quasar-v0.17.js, src/detectors/quasar.js, src/detectors/react-static.js, src/detectors/sapper.js, src/detectors/stencil.js, src/detectors/svelte.js, src/detectors/vue.js, src/detectors/vuepress.js, src/utils/detect-server.js
`urlRegexp` is not used anywhere. This PR removes it.
=> Remove dead code `urlRegexp`

renovate.json
This groups Netlify packages updates into a single PR and makes sure they happen as soon as possible,
=> chore(deps): group Netlify packages updates

src/utils/rules-proxy.js
**- Summary**
Make host based redirect rules work with `netlify dev`
Add a rule like:
```
http://testing.dev/* /testing.html 200!
```
to a local project and test with:
```
curl http://locahost:8888 -H "Host: testing.dev"
```
Without this fix, the redirect won't work, with this fix the redirect will work.
Make host based rules like:
```
http://localhost/* /:splat 200
```
Work in Netlify dev
=> Make sure scheme is formatted right for redirector

docs/commands/functions.md, src/commands/functions/invoke.js
See https://github.com/netlify/cli/issues/492#issuecomment-687957987
=> docs(command-functions): fix invoke example payload

src/commands/dev/index.js, tests/utils/devServer.js
Fixes https://github.com/netlify/cli/issues/1200
Opening as draft to get some feedback since this might be considered a breaking change.
See https://github.com/netlify/cli/issues/1200#issuecomment-688207258
=> fix(command-dev): change autoLaunch default to true

src/lib/settings.js, src/utils/state-config.js, src/utils/traffic-mesh.js
Otherwise we dump the logs in the terminal and it's very noisy.
=> Set the log location for traffic mesh explicitly.

tests/command.dev.test.js
**- Summary**
Adds a missing test case for this scenario:
https://github.com/netlify/cli/pull/1157
N/A
Add a missing test case for fully qualified URLs redirects
🐒
=> test(command-dev): add missing test case

.eslintrc.json, package-lock.json, package.json, site/.eslintrc.json
Follow up on https://github.com/netlify/build/pull/1905
=> chore: add lodash,underscore linting

package.json, tests/command.deploy.test.js, tests/command.dev.test.js, tests/command.dev.trace.test.js, tests/command.functions.test.js, tests/cra.test.js, tests/rules-proxy.test.js
Follow up on #1341.
This runs ESLint on `tests/**/*.js`.
=> Lint test files

src/functions-templates/js/google-analytics/google-analytics.js, src/functions-templates/js/url-shortener/generate-route.js, src/lib/api.js, src/utils/telemetry/index.js, src/utils/telemetry/validation.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`prefer-includes`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-includes.md).
=> Use `Array.includes()` instead of `Array.indexOf`

src/functions-templates/js/google-analytics/google-analytics.js, src/functions-templates/js/send-email/validations.js, src/functions-templates/js/url-shortener/url-shortener.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`throw-new-error`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/throw-new-error.md).
=> Use `new Error()` instead of `Error()`

site/scripts/docs.js, src/commands/addons/config.js, src/commands/addons/create.js, src/commands/addons/list.js, src/commands/dev/exec.js, src/commands/dev/index.js, src/commands/functions/create.js, src/commands/functions/list.js, src/commands/sites/list.js, src/commands/watch.js, src/utils/gitignore.js, src/utils/headers.js, src/utils/proxy.js, src/utils/rules-proxy.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`explicit-length-check`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/explicit-length-check.md).
=> Make `Array.length` checks consistent

src/commands/functions/create.js, src/commands/functions/invoke.js, src/utils/detect-server.js, src/utils/proxy.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`prefer-set-has`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-set-has.md).
=> Use `Set.has()` instead of `Array.includes()`

src/utils/telemetry/index.js
This fixes a linting error from `eslint-plugin-unicorn`.
=> Small code simplification

.eslintrc.json, package.json, site/.eslintrc.json, src/commands/switch.js, src/functions-templates/js/apollo-graphql/apollo-graphql.js, src/functions-templates/js/fauna-crud/create.js, src/functions-templates/js/fauna-crud/delete.js, src/functions-templates/js/fauna-crud/read-all.js, src/functions-templates/js/fauna-crud/read.js, src/functions-templates/js/fauna-crud/update.js, src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-1.js, src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-2.js, src/functions-templates/js/hasura-event-triggered/hasura-event-triggered.js, src/functions-templates/js/hello-world/hello-world.js, src/functions-templates/js/identity-signup/identity-signup.js, src/functions-templates/js/node-fetch/node-fetch.js, src/functions-templates/js/set-cookie/set-cookie.js, src/functions-templates/js/stripe-subscription/stripe-subscription.js, src/functions-templates/js/token-hider/token-hider.js, src/functions-templates/js/url-shortener/generate-route.js, src/utils/command.js, src/utils/proxy.js, src/utils/rules-proxy.js, src/utils/serve-functions.js, tests/command.deploy.test.js, tests/command.dev.test.js, tests/command.dev.trace.test.js, tests/command.functions.test.js
This adds the `no-unused-vars` linting rule to remove unused variables.
=> Remove unused variables

package.json, src/utils/proxy.js
**- Summary**
Related #1275 
When I run `npm run watch` in my environment, I get some hooks failed in the master branch as well. 
Please help me.
chore: use async call in proxy.js
Added p-filter as I edit.
=> chore: use async fs in proxy js

package-lock.json, package.json, renovate.json5
Follow up on https://github.com/netlify/build/pull/1971
=> chore: upgrade eslint

CONTRIBUTING.md
Fixes https://github.com/netlify/build/issues/1950
This improves the `CONTRIBUTING.md` section related to linting and prettification.
=> Improve `CONTRIBUTING.md` section about dev setup

CONTRIBUTING.md
This PR hopefully improves the beginning of the `CONTRIBUTING.md`. Let me know what you think.
=> Improve `CONTRIBUTING.md` first section

.eslintrc.js, src/commands/deploy.js, src/commands/watch.js, src/detectors/create-react-app.js, src/detectors/stencil.js, src/detectors/utils/jsdetect.js, src/functions-templates/js/google-analytics/google-analytics.js, src/functions-templates/js/sanity-create/sanity-create.js, src/functions-templates/js/sanity-groq/sanity-groq.js, src/functions-templates/js/slack-rate-limit/slack-rate-limit.js, src/utils/parse-raw-flags.js
This adds the [`multiline-comment-style`](https://eslint.org/docs/rules/multiline-comment-style) ESLint rule.
This uses the `//` style because it is easier to comment/uncomment individual lines. Also, it is the closest to our current style, so this requires the least modification. However, I'm happy with other styles if you'd prefer :+1:
=> Add `multiline-comment-style` ESLint rule

.eslintrc.js, src/commands/dev/index.js, src/commands/functions/invoke.js, src/functions-templates/js/fauna-crud/fauna-crud.js, src/lib/api.js, src/lib/exec-fetcher.js, src/utils/chalk.js, src/utils/command.js, src/utils/gh-auth.js
This adds the [`no-else-return`](https://eslint.org/docs/rules/no-else-return) ESLint rule.
This rule is useful to decrease the amount of indentation in functions and decrease how much `if`/`then`/`else` nesting we need to remember while reading code, making it simpler.
This PR used `eslint --fix` to generate the diff.
=> Add `no-else-return` ESLint rule

.eslintrc.js, src/commands/functions/invoke.js, src/commands/functions/list.js, src/functions-templates/js/fauna-graphql/sync-schema.js, src/functions-templates/js/set-cookie/set-cookie.js, src/functions-templates/js/url-shortener/generate-route.js, src/functions-templates/js/url-shortener/get-route.js
This adds the [`no-var`](https://eslint.org/docs/rules/no-var) ESLint rule.
This PR's diff is generated by `eslint --fix`.
=> Add `no-var` ESLint rule

src/functions-templates/js/send-email/validations.js
This simplifies a function, without changing its behavior.
=> Simplify a function

src/commands/functions/create.js
This is a small refactoring of function, simplifying it. It does not change its behavior.
=> Small refactoring of a function

src/utils/init/config-github.js
This PR improves performance by running GitHub hooks API configuration in parallel instead of serially. I cannot see a reason why those would need to be serial, but @erezrokah please let me know if I got this wrong.
This PR tries also to put some constants at the top-level scope.
=> Run GitHub hooks configuration in parallel

src/utils/rules-proxy.js, src/utils/rules-proxy.test.js
This improves the performance of proxy rules parsing by running asynchronous operations in parallel.
=> Improve the performance of proxy rules parsing

package-lock.json, package.json, renovate.json5, src/utils/proxy.js
This improves the performance of the static proxy by checking for file existence in parallel.
=> Improve performance of static proxy

.eslintrc.js, src/utils/proxy.js
This adds the [`max-params`](https://eslint.org/docs/rules/max-params) ESLint rule, with a maximum of 4 positional parameters.
=> Add `max-params` ESLint rule

.eslintrc.js
This removes some unused ESLint overrides.
=> Remove some unused ESLint overrides

.eslintrc.js, tests/utils/dev-server.js
This adds the [`no-plusplus`](https://eslint.org/docs/rules/no-plusplus) ESLint rule.
=> Add `no-plusplus` ESLint rule

.eslintrc.js, src/commands/deploy.js, src/commands/env/get.js, src/utils/chalk.js, src/utils/command.js
This adds the [`no-negated-condition`](https://eslint.org/docs/rules/no-negated-condition) ESLint rule.
=> Add `no-negated-condition` ESLint rule

.eslintrc.js, .github/workflows/main.yml, src/commands/functions/invoke.js, src/lib/exec-fetcher.js
This adds the [`no-underscore-dangle`](https://eslint.org/docs/rules/no-underscore-dangle) ESLint rule.
=> Add `no-underscore-dangle` ESLint rule

.eslintrc.js, package-lock.json, package.json, src/utils/addons/diffs/options.js, src/utils/dev.js, src/utils/telemetry/request.js
This adds [`eslint-plugin-eslint-comments`](https://github.com/mysticatea/eslint-plugin-eslint-comments), which is a linter for the ESLint comments themselves.
=> Add `eslint-plugin-eslint-comments`

.eslintrc.js, src/commands/deploy.js, src/utils/gh-auth.js, src/utils/proxy.js
This adds the [`no-return-await`](https://eslint.org/docs/rules/no-return-await) ESLint rule.
=> Add `no-return-await` ESLint rule

.eslintrc.js, site/src/_layout.js, src/commands/dev/exec.js, src/commands/functions/create.js, src/commands/functions/invoke.js, src/commands/functions/list.js, src/commands/open/admin.js, src/commands/open/site.js, src/commands/sites/index.js, src/commands/status/hooks.js, src/commands/status/index.js, src/detectors/create-react-app.js, src/detectors/stencil.js, src/detectors/utils/jsdetect.js, src/functions-templates/js/auth-fetch/auth-fetch.js, src/functions-templates/js/fauna-graphql/fauna-graphql.js, src/functions-templates/js/fauna-graphql/sync-schema.js, src/functions-templates/js/google-analytics/google-analytics.js, src/functions-templates/js/graphql-gateway/graphql-gateway.js, src/functions-templates/js/identity-signup/identity-signup.js, src/functions-templates/js/node-fetch/node-fetch.js, src/functions-templates/js/sanity-create/sanity-create.js, src/functions-templates/js/sanity-groq/sanity-groq.js, src/utils/detect-functions-builder.js, src/utils/detect-server.js, src/utils/init/config-github.js, src/utils/read-repo-url.js, src/utils/telemetry/index.js, tests/command.env.test.js
This adds the [`no-inline-comments`](https://eslint.org/docs/rules/no-inline-comments) and [`line-comment-position`](https://eslint.org/docs/rules/line-comment-position) ESLint rules.
=> Add `no-inline-comments` ESLint rule

.eslintrc.js, .prettierrc.json, site/src/_app.js, site/src/_layout.js, src/commands/deploy.js, src/commands/sites/create.js, src/functions-templates/js/slack-rate-limit/slack-rate-limit.js, src/functions-templates/js/submission-created/submission-created.js, src/functions-templates/js/url-shortener/generate-route.js, src/lib/api.js, src/utils/live-tunnel.js, src/utils/proxy.js, tests/command.deploy.test.js, tests/command.dev.test.js, tests/cra.test.js
This removes unnecessary quotes, using Prettier.
=> Remove unnecessary quotes

.eslintrc.js, .github/workflows/main.yml, netlify.toml, package.json, site/package-lock.json, site/package.json, site/src/_app.js, site/src/_ui.js
This adds `plugin:node/recommended` and few additional rules, like in Netlify Build.
Note: CI tests currently failing. Looking into it.
=> Add `plugin:node/recommended`

src/utils/get-functions.js, src/utils/get-functions.test.js, src/utils/serve-functions.js, tests/command.dev.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1471
Added tests
See logs example:
Add support for handling background functions invocations
> Some of the code can be refactored once https://github.com/netlify/cli/pull/1478 lands
=> feat(command-dev): don't error when background functions don't return a response

.eslintrc.js, src/functions-templates/js/google-analytics/google-analytics.js, src/functions-templates/js/send-email/send-email.js, src/functions-templates/js/slack-rate-limit/slack-rate-limit.js, src/functions-templates/js/stripe-charge/stripe-charge.js
This adds the [`node/callback-return`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/callback-return.md) ESLint rule.
=> Add `node/callback-return` ESLint rule

renovate.json5
This is taken from https://github.com/netlify/renovate-config/blob/1a04d26820630db23537e0625274ed376c0a3bb6/default.json#L2 now
=> chore(renovate): remove constraints

README.md, docs/README.md, docs/commands/dev.md, docs/commands/index.md, src/commands/dev/trace.js
This unhides the `dev:trace` command
=> chore: unhide dev:trace

.eslintrc.js
This adds [`eslint-plugin-promise`](https://github.com/xjamundx/eslint-plugin-promise).
See https://github.com/netlify/build/issues/1956
=> Add `eslint-plugin-promise`

.eslintrc.js, site/scripts/generate-command-data.js, site/src/_app.js, src/commands/dev/trace.js, src/commands/functions/create.js, src/commands/functions/invoke.js, src/functions-templates/js/auth-fetch/auth-fetch.js, src/functions-templates/js/hasura-event-triggered/hasura-event-triggered.js, src/functions-templates/js/node-fetch/node-fetch.js, src/functions-templates/js/oauth-passport/oauth-passport.js, src/functions-templates/js/oauth-passport/utils/auth.js, src/functions-templates/js/submission-created/submission-created.js, src/utils/detect-functions-builder.js, src/utils/detect-server.js, src/utils/init/config-github.js, src/utils/rules-proxy.js, src/utils/rules-proxy.test.js, src/utils/state-config.js, src/utils/telemetry/request.js, tests/cra.test.js
See https://github.com/netlify/build/issues/1955
This adds [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import).
=> Add `eslint-plugin-import`

.eslintrc.js, package-lock.json, package.json
This upgrades `eslint-config-node` and simplifies the linting configuration thanks to it.
=> Use new `eslint-config-node`

src/commands/functions/invoke.js
Background in #1478.
This simplifies the code related to functions invoke.
=> Refactor functions invoke

package-lock.json, package.json, src/commands/dev/index.js, src/utils/traffic-mesh.js
This will allow testing edge handlers to geoip location capabilities.
That flag was introduced in https://github.com/netlify/traffic-mesh/pull/1199/files
=> feat(dev): set path to geoip location database

.github/workflows/fossa.yml
**- Summary**
- adds back custom config changes that were reverted in the last update to the fossa workflow files
- tested on this branch
Fix fossa workflow configuration
=> fix fossa pr check

CONTRIBUTING.md
**- Summary**
I got unresolved dependencies errors during the pre-push hooks, since I hadn't installed the dependencies in the `site` subdirectory. This PR adds instructions to install those missing deps to the contributing guide. If you think there's a better place or alternative, happy to change the PR or you're welcome to take over!
I've tested locally, though I wish there was a way to test/maintain the contributor onboarding experience. If there's something I'm not aware of, I'm down to look at the implementation.
docs: add instructions to install npm dependencies in the site subdirectory
<details><summary>༼ つ ◕_◕ ༽つ🤳</summary>
</details>
=> docs: include npm install for site subdirectory

site/package-lock.json
**- Summary**
npm run site:build:install, which runs `npm ci`, inside of the site directory was throwing a cannot find module error. An update of the package lock adds the required package.
Reference:
https://stackoverflow.com/a/60853591
Check out the automated tests 🤞
chore: update site/package-lock.json
<details><summary>༼ つ ◕_◕ ༽つ</summary>
</details>
=> chore: update site/package-lock.json

package-lock.json, package.json, src/utils/detect-server.js, src/utils/proxy.js, src/utils/rules-proxy.js, tests/command.dev.test.js, tests/rules-proxy.test.js, tests/utils/site-builder.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1518
Tested on this branch https://github.com/erezrokah/netlify-build-reproductions/tree/cli/issue_1518
I'll add more tests in another commit
- Write a 404 response when JWT role doesn't match the route
- Set `force404` to `false` when JWT role matches the route to return a valid response
🐱
=> fix(command-dev): role based redirects

src/commands/dev/index.js
=> Fix timeout duration typo

src/commands/init.js
**- Summary**
Related to https://github.com/netlify/cli/issues/1611
Tested manually the different flows
Extract init command into separate functions for code clarity
🧸 
Marking as `low-risk` as this shouldn't impact existing behavior
=> refactor(command-init): extract code into functions

src/utils/headers.js, src/utils/headers.test.js, tests/command.dev.test.js
**- Summary**
Fixes #1277 
There's room for more if users expect support for multiple `*`, like `/**/yolo`. I didn't include that here, since that seems out of scope for this PR. I'm inclined to think the preemptive change wouldn't be worth it until it's brought up by a user.
I added a case to `headers.test.js` and added the expected behavior to the root test. My first commit contains a couple end to end tests of the dev command. I'm not sure what the testing philosophy is for the cli, so let me know if you'd like me to remove or add more.
fix-bug(command-dev): match root path with /* headers
<details><summary>༼ つ ◕_◕ ༽つ🎉</summary>
</details>
=> Fix: match root path to /* headers

tests/utils/dev-server.js
This PR adds a timeout when starting the dev server during tests to avoid blocking forever
=> test: add start dev server timeout

src/commands/functions/invoke.js
A small refactoring to use `async/await` when invoking functions
=> refactor(command-functions-invoke): use async/await

package.json, src/commands/api.js, src/utils/command.js
Related to https://github.com/netlify/cli/issues/1568
Example output:
=> feat: add warning message if running Node.js < 10

renovate.json5
Follow up on https://github.com/netlify/cli/pull/1688
=> chore(deps): ignore major updates for boxen

.github/workflows/main.yml, README.md, package.json, renovate.json5
Fixes https://github.com/netlify/cli/issues/1568
Not to be merged yet, but opened for visibility
=> feat!: drop Node.js 8 support

CONTRIBUTING.md
**- Summary**
Quick update to our `CONTRIBUTING` guidelines 👍 
N.A.
Update the CONTRIBUTING file with a mention to our integrationt tests
=> chore: update the CONTRIBUTING file with a mention to our integrationt tests

.github/workflows/release-please.yml, CONTRIBUTING.md, package-lock.json, package.json
Fixes https://github.com/netlify/cli/issues/1665
Removed the docs generation during publish in favor of https://github.com/netlify/cli/pull/1745
=> chore: add release please

src/utils/live-tunnel.js
**- Summary**
When running `ntl dev --live`, I'm seeing CLI opening a new browser window with a 502. If I then refresh the site, it works as expected. I think this is because we're launching the browser before the live tunnel has had a chance to connect.
As a proposed solution, this PR polls the API and waits until the `/live_sessions/:id` endpoint returns `state: "online"`. For the polling mechanism, I've used the same logic as the `watch` command.
Closes https://github.com/netlify/cli/issues/1189.
1. `cd` into a directory with a Netlify site configured
2. run `ntl dev --live`
There are currently no tests for the live tunnel. If we're happy with the approach taken in this PR, I'd like to try and add some tests before merging it.
fix: …
=> fix: wait for live session to be ready before starting tunnel

package.json, src/lib/deprecations.js, src/utils/command.js
Fixes https://github.com/netlify/cli/issues/1753
=> fix: remove redundant Node.js 10 warning

tests/command.dev.test.js
Remove the public directory because the dev server doesn't know about it.
=> fix(dev): fix role based access tests

package-lock.json, package.json, src/utils/init/utils.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1773
See flow when running from a `create-react-app` site:
recommend framework specific settings on site creation
=> feat(command-init): recommend framework specific settings on site creation

package-lock.json, package.json, tests/command.dev.test.js
Add a test for cookie based country redirects.
Fixes #1786 
=> fix(dev): fix cookie handling with TM

src/commands/dev/index.js
**- Summary**
When running `ntl dev`, we wait for the port of the local server to open before launching the browser session. However, there is sometimes a delay between the port being open and the server actually being ready to receive requests. This means that the page we open may be blank and unable to recover without a refresh.
I'm able to reproduce this consistently with a fresh Gatsby site.
The solution proposed in this PR is to poll the local server with `HEAD` requests. Once one is completed successfully, we consider the server to be ready and only then launch the browser session.
Closes #404
fix: make ntl dev wait for local server to be ready
=> fix: make ntl dev wait for local server to be ready

renovate.json5
Follow up on https://github.com/netlify/cli/pull/1828
=> chore: ignore path-type major updates

.eslintrc.js, package.json
Related to https://github.com/netlify/team-dev/issues/7 and https://github.com/npm/cli/issues/2609
=> chore: fix linting and formatting on npm@7

site/scripts/generate-command-data.js, site/src/_app.js
Follow up on https://github.com/netlify/cli/pull/1886#discussion_r576371470
=> refactor: remove regex usage in site scripts

.eslintrc.js, src/functions-templates/js/fauna-crud/read-all.js, src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
Related to https://github.com/netlify/cli/issues/1891
=> refactor: enable and fix promise/no-nesting

.eslintrc.js, src/utils/proxy.js, src/utils/serve-functions.js
Related to https://github.com/netlify/cli/issues/1891
=> refactor: enable and fix unicorn/no-array-push-push

src/detectors/vite.js
**- Summary**
This PR adds a detector for [Vite](https://vitejs.dev/).
`netlify dev` should work out of the box in a Vite project.
=> feat(detectors): add detector for Vite

src/utils/serve-functions.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/413
Run `netlify dev` and add a new function
=> fix(command-dev): newly added functions are not recognized

src/utils/proxy.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2216.
Probably caused by https://github.com/netlify/cli/pull/2195
I couldn't reproduce, the fix is based on the issue stacktrace.
Still it would be great to get a reproduction so I can understand the cause.
Waiting on a reproduction for the issue.
🐼
=> fix(command-dev): handle undefined location

renovate.json5
Closes https://github.com/netlify/cli/pull/2231
=> chore(deps): ignore major updates for to-readable-stream

README.md, docs/README.md, docs/getting-started.md
**- Summary**
Fixes https://github.com/netlify/cli/issues/2208
N/A
🦒
=> feat(docs): recommend local install on CI

src/utils/dev.js, src/utils/serve-functions.js
Follow up on https://github.com/netlify/cli/pull/2239
=> refactor(command-dev): move ms conversion closer to lambda invocation

src/function-builder-detectors/netlify-lambda.js, src/function-builder-detectors/zisi.js, src/utils/serve-functions.js, tests/serving-functions.test.js
**- Summary**
Use memoization instead of debouncing the build function.
Reinstates the TypeScript tests.
=> feat: memoize build function

npm-shrinkwrap.json, package.json, src/function-builder-detectors/zisi.js, tests/serving-functions.test.js
**- Summary**
Adds support for the `functions.included_files` property introduced in https://github.com/netlify/build/pull/2681.
Added a new test.
=> feat: add support for functions.included_files property

src/commands/build/index.js, tests/command.build.test.js
**- Summary**
Same as https://github.com/netlify/cli/pull/2298 for the build command tests
See modified tests
=> test(command-build): use mock api

.github/workflows/vale.yml, .gitignore, .vale.ini, CONTRIBUTING.md
**- Summary**
Initial work towards https://github.com/netlify/cli/issues/1846. Only lints docs for now (not CLI logs).
This creates a lot of annotations so I might just enable it for changes files only, but I wanted to get some visibility into the warnings.
See GitHub annotations.
🐼
=> chore(ci): add vale

tests/command.addons.test.js, tests/command.env.test.js, tests/utils/call-cli.js, tests/utils/mock-api.js
**- Summary**
Same as #2298 and #2299 for the env command tests
See modified tests
=> test(command-env): use mock api

src/lib/help.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/80
Before:
After:
🐕‍🦺
=> feat(command-help): add per command help description

README.md, docs/README.md, docs/commands/functions.md, docs/commands/index.md, docs/functions-dev.md, site/src/_app.js, src/commands/functions/build.js, src/commands/functions/list.js, src/commands/functions/serve.js, src/utils/dev.js, src/utils/functions/index.js, src/utils/serve-functions.js, tests/command.functions.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/409
Fixes https://github.com/netlify/cli/issues/2151
Added tests and docs on how to debug functions
=> feat(command-functions): add serve command

docs/functions-dev.md
**- Summary**
Follow up on https://github.com/netlify/cli/pull/2270
Fixes some typos due to last minute changes in the PR.
N/A
🐦
=> docs(functions-dev): fix some typos

npm-shrinkwrap.json, package.json
**- Summary**
Follow up on https://github.com/netlify/cli/pull/2341 and https://github.com/netlify/cli/pull/2350
We can update to `v4`, but not `v5`
Existing tests
🐻
=> fix(deps): update p-map to v4

renovate.json5
**- Summary**
This should auto close https://github.com/netlify/cli/pull/2341 and https://github.com/netlify/cli/pull/2340
N/A
🐱
=> chore(deps): renovate ignore p-map and http-proxy-middleware

scripts/postinstall.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2325
Hopefully this fixes the installations issues (and not just move the error to when a user invokes the CLI).
N/A
🐒
=> fix(postinstall): wrap chalk require

src/commands/init.js
**- Summary**
Change `git push -u origin master` to `git push -u origin main` to match github default branch name
None, only changed one word
Not today, folks!
=> fix(command-init): use main instead of master

.github/workflows/benchmark.yml, .github/workflows/main.yml, .github/workflows/release-please.yml, .github/workflows/verify-docs.yml
=> chore: run CI tests on Node 16

.github/workflows/main.yml
This fixes the test coverage upload since `*` is not allowed there.
=> chore: fix test coverage upload

npm-shrinkwrap.json, package.json, tests/command.dev.test.js, tests/command.functions.test.js, tests/utils/dev-server.js, tests/utils/process.js
**- Summary**
Uses a more robust way to kill child processes in tests
Also fixes a bug in the functions tests (not passing the `port` parameter)
Existing tests
🙈
=> test: improve process handling

npm-shrinkwrap.json, package.json, src/lib/path.js, src/utils/init/config-github.js, src/utils/init/config-manual.js, src/utils/init/frameworks.js, src/utils/init/node-version.js, src/utils/init/utils.js, src/utils/lm/install.js, tests/command.init.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2380
I'll add tests soon
=> feat(command-init): prompt for base

npm-shrinkwrap.json, package.json, src/commands/build/index.js, src/commands/deploy.js, src/lib/build.js, tests/command.deploy.test.js, tests/utils/site-builder.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2501
TBD - add a new test
🐶
=> feat(command-deploy): refresh configuration when running with --build

src/utils/proxy.js, tests/command.dev.test.js, tests/utils/curl.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2591
See https://github.com/http-party/node-http-proxy/issues/1219
Added a new test
🐱
=> fix(command-dev): handle Expect:100-continue

npm-shrinkwrap.json, package.json
Fixes the version of `functions-utils` in our lock file
=> fix(deps): fix @netlify/esbuild usage by functions-utils

src/commands/functions/invoke.js, src/utils/get-functions.js, src/utils/serve-functions.js, tests/command.dev.test.js, tests/command.functions.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2697
Added new tests
🐟
=> fix(command-dev): handle event triggered background functions

.github/workflows/docsearch.yml
**- Summary**
Updates to the latest version of the docsearch action for [improved speed](https://github.com/darrenjennings/algolia-docsearch-action/pull/3).
Also reduced the indexing interval to avoid hitting the Algolia API too many times.
Existing tests
🐜
=> ci(docsearch): update to latest version and update schedule

npm-shrinkwrap.json, package.json
Replaces https://github.com/netlify/cli/pull/2758
=> fix(deps): pin zisi to 4.4.2

renovate.json5
Follow up on https://github.com/netlify/cli/pull/2774
=> chore(deps): ignore major updates for node-version-alias

src/detectors/vite.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2882 which is a regression because of https://github.com/netlify/cli/pull/2842
If we see more cases I'll revert that PR
Tested manually
🐟
=> fix(command-dev): don't poll for http requests for vite framework

tests/serving-functions.disabled-test.js, tests/serving-functions.test.js
**- Summary**
Temporarily disables flaky tests. I've commented them out since the `.only` construct is not available due to us patching `test`.
N/A
🙈
=> chore: temporarily disable problematic tests

src/commands/functions/serve.js, tests/command.functions.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2922
🐘
=> fix(command-functions): inject env variables to functions:serve

.github/workflows/main.yml
**- Summary**
Fixes https://github.com/netlify/build/pull/3291#pullrequestreview-706505493.
=> chore: make release check cross-OS compatible

.github/workflows/pre-release.yml
Fixes https://github.com/netlify/cli/pull/2954/checks?check_run_id=3096984652#step:10:53.
=> chore: skip npm scripts on pre-release publish

src/commands/deploy.js, src/lib/fs.js, src/lib/functions/registry.js, src/lib/functions/server.js, src/utils/deploy/deploy-site.js, src/utils/deploy/hash-fns.js, src/utils/functions/index.js, tests/command.deploy.test.js, tests/serving-functions.test.js
**- Summary**
Adds support for bundling functions from `.netlify/functions-internal`. Needs https://github.com/netlify/build/pull/3213.
Added new tests.
=> feat: add support for internal functions directory

.github/workflows/fossa.yml
**- Summary**
Fixes fossa workflow error.
Tested by running in Github Actions.
=> chore: fossa workflow

src/lib/functions/local-proxy.js
**- Summary**
We changed the CLI interface in https://github.com/netlify/local-functions-proxy/commit/d2cd7fdb7a58ebb530b089cfc6d5cb565018f388#diff-ef2b813e004771704c627906842d921b5bf3e0d027dba4f042a72f19a0013d58. This PR makes the necessary changes in the consumer.
N/A
🐩
=> fix: use new arguments syntax

tests/serving-functions-go.test.js, tests/serving-functions.test.js, tests/utils/dev-server.js
**- Summary**
Print the CLI output when the serving functions tests fail
Existing tests
🐼
=> test(serving-functions): add CLI output on failure

src/commands/status/index.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/3021
This was broken in https://github.com/netlify/cli/pull/2827
I'll add a test in another PR
🐒
=> fix(command-status): invoke getToken()

.github/workflows/release-please.yml
**- Summary**
Follow up on https://github.com/netlify/cli/pull/3027
We should only run `npm ci` if a release was created
🙈  https://github.com/netlify/cli/actions/runs/1078774929
=> chore(ci-release-please): add missing condition

tests/command.deploy.test.js, tests/command.functions.test.js
**- Summary**
Updates some test fixture names. Also using it to force a major release.
=> chore!: update test fixture names

.github/workflows/release-please.yml
This is an attempted workaround for https://github.com/google-github-actions/release-please-action/issues/337
=> chore: pin release-please version

src/utils/proxy.js, tests/command.dev.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/3217
~~TBD~~ Added a test
=> fix(command-dev): don't redirect to function server if it doesn't exist

src/utils/proxy.js
When `netlify dev` redirects to a Function, we keep the original request URL as a `X-Netlify-Original-Pathname` HTTP request header.
https://github.com/netlify/cli/blob/cc84d2ab4da62c8fc523b30362d243c044d71c57/src/utils/proxy.js#L250
This is used by the Functions server to set the `event.path` so it matches the URL before the redirection happened.
https://github.com/netlify/cli/blob/cc84d2ab4da62c8fc523b30362d243c044d71c57/src/lib/functions/server.js#L65
However, this does not work when the redirect is a fallback after a JWT authentication failed. In that case, we set the request URL as `/.netlify/non-existing-path` in order to serve it as a fallback. However, `/.netlify/non-existing-path` ends up being interpreted as the original URL, which is then set to `event.path`. This is incorrect. …
=> fix: use original `event.path` when redirecting to Functions

scripts/postinstall.js, site/fs.js, src/commands/lm/info.js, src/lib/fs.js, src/lib/functions/runtimes/go/index.js, src/lib/functions/server.js, src/utils/command.js, src/utils/get-global-config.js, src/utils/get-global-config.test.js, src/utils/init/config-github.js, src/utils/lm/install.js, tests/serving-functions.test.js
**- Summary**
While reviewing #3347, @ehmicky suggested to replace `catch(_)` with `catch` since the `_` isn't really needed. 
This PR implements that same suggestion for the entire repository.
=> refactor: replace catch(_) with catch in try-catch blocks

tests/command.dev.test.js
**- Summary**
While working on #3368, I stumbled over the `gotCatch404` helper function, which works around Got's behaviour to throw on non-successful responses. The more idiomatic way to disable this behaviour is the built-in `throwHttpErrors: false` option. This has the benefit that tests now won't fail because of a thrown error, but instead because of failed assertions (wrong status code!), resulting in test failure messages that are easier to trace.
=> refactor: replace gotCatch404 with "throwHttpErrors: false"

src/commands/addons/config.js, src/commands/dev/index.js, src/commands/functions/serve.js, src/lib/functions/form-submissions-handler.js, src/lib/functions/netlify-function.js, src/lib/functions/registry.js, src/lib/functions/server.js, src/utils/dev.js, src/utils/link/link-by-prompt.js
**- Summary**
#3028 was too large for review and is being broken down.
This PR is a follow-up on #3247 and uses the separate logging and process control utilities created in it to remove the inherited ones.
This PR focuses on utilities related to the dev, functions and link commands. Changes are a bit sparse and not contained in a specific command folder like the previous PRs.
This is probably the 2nd last PR in this series and then we should be done.
=> refactor: replace log,exit in utils of dev,functions,link command

.github/workflows/pre-release.yml
Same as https://github.com/netlify/cli/pull/3277 for the pre-release workflow
=> chore(ci): fix pre-release

src/utils/init/config-github.js
There was a wrong default import inside the GitHub authentication 
---
=> fix(init): fixes a wrong import inside the github authentication

CONTRIBUTING.md
=> chore(docs): add note about netlify-services account

tests/telemetry.test.js
=> test: fix a test that was failing locally

README.md
This removes some broken badges from our readme
---
🐼
=> chore: remove broken readme badges

src/commands/switch/switch.js
The switch command failed when no user was logged in:
now it let's choose them without failing
---
=> fix(switch): fix switch command error when no user logged in

site/scripts/docs.js, src/utils/deploy/upload-files.js, src/utils/rules-proxy.js
Fixing a few of the [LGTM](https://lgtm.com/projects/g/netlify/cli/?mode=list) issues
---
PS. not super familiar with the commit messages you might be using, so feel free to tweak it while merging.
=> Remove superfluous arguments

npm-shrinkwrap.json, package.json
Reverts https://github.com/netlify/cli/pull/3995, as it doesn't fix the issue for yarn
=> fix: remove colors as a direct dependency

.gitignore, tests/eleventy-site/package-lock.json, tests/hugo-site/package-lock.json, tests/hugo-site/package.json
Fixes #<replace_with_issue_number>
---
=> chore(tests): update hugo-bin and regenerate lock files

.github/workflows/pre-release.yml
This fixes the `prerelease` step with the new Git hooks setup.
---
=> chore: fix prerelease step

src/lib/completion/generate-autocompletion.js
Fixes #3870
Sometimes it can happen that the autocomplete generation in the postinstall script lacks permissions to write files to the home directory of the user. Therefore just warn with the error and don't break install.
---
=> fix: fixes an issue where the autocomplete could not be written

tests/command.init.test.js
=> Disable flaky tests on windows

site/src/_app.js
Adds the `graph` command to the correct location in the CLI reference site nav bar
---
- [] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
🐒
=> chore(site): add graph to nav bar

tests/integration/20.command.functions.test.js
Our tests started failing after merging https://github.com/netlify/cli/pull/4145.
The underlying issue is that the order of the templates changed so we need to update the tests.
It wasn't caught by our automation as the `affected tests` logic didn't detect it as a test we should run (cc @lukasholzer)
---
🐳
=> test(command-functions): update to match templates

.gitignore, npm-shrinkwrap.json, package.json, src/lib/exec-fetcher.js, tests/integration/utils/rewiremock.js, tests/unit/lib/exec-fetcher.test.js
pre requisite for ESM migration to keep this as small as possible.
use `rewiremock` instead of `proxyrequire` as it is more active and supports esm modules for mocking.
---
=> test: replace proxyquire with rewiremock as it works with esm as well

src/commands/sites/sites-create.js
Fixes #1772
Earlier while creating a new site, the name suggested by the CLI and the name with which the site was actually created were different. This happened because the name suggested by the CLI wasn't considered and an empty name field was passed to the Netlify API which assigned a random site name on its own.
This PR fixes that behavior. Names suggested by the CLI will be set consistently when creating the site.
Test Run Post Fix with `init`
---
=> fix: make site suggestion flow consistent

src/lib/functions/utils.js, tests/integration/20.command.functions.test.js
=> fix: handle content-type headers with charset

.github/workflows/vale.yml
Follow up to https://github.com/netlify/cli/pull/4249
---
=> chore(vale): add continue-on-error

src/lib/functions/server.js
Adds `NETLIFY_GRAPH_TOKEN` to the env in addition to `ONEGRAPH_AUTHLIFY_TOKEN`. Preference should be given to the new name.
---
=> chore: add `NETLIFY_GRAPH_TOKEN` to env too

src/commands/graph/graph-config-write.js, src/commands/graph/graph-edit.js, src/commands/graph/graph-handler.js, src/commands/graph/graph-library.js, src/commands/graph/graph-pull.js, src/lib/one-graph/cli-client.js, src/lib/one-graph/cli-netlify-graph.js
Polishes a lot of the error messages, banners, etc.
---
=> feat: refresh graph dx

src/commands/graph/graph-handler.js
command was discarding `userOperationName` entirely
---
=> fix: in graph:handler, still allow user provided input

src/commands/main.js
=> fix: no option in Suggestion prompt (#4303)

renovate.json5
This package requires a manual update 
---
🐟
=> chore(deps): renovate ignore netlify-onegraph-internal

.github/workflows/e2e-test.yml, e2e/install.e2e.mjs
Out e2e tests are flaky, especially on Windows:
https://github.com/netlify/cli/runs/5362630555?check_suite_focus=true#step:6:512
The cause seems to be trying to remove a locked directory, and other file system related issues.
This PR runs the tests in serial to address the problem.
---
=> test(e2e): run in serial

.github/workflows/benchmark.yml
`v3` fails for us. Revert to `v2` until we can fix it.
---
=> ci(delta-action): use v2

src/commands/dev/dev.js
Only delete the netlify Graph configuration if no current authlifyTokenId exists.
---
=> fix: polling for API Authentication

package.json, src/lib/functions/server.js
Adds graph token header to function invocations to mimic behavior of production.
---
=> feat(dev-graph): populate X-Nf-Graph-Token header

package.json, site/package-lock.json, tests/integration/420.command.init.test.js
Fixes #2730
Adds test coverage to ensure that the cli is detecting frameworks within the init command and is adding the correct default build command and build directories.
---
=> chore: Add init command tests to verify framework specific build directories

tests/integration/100.command.dev.test.js
Fixes #<replace_with_issue_number>
---
=> chore: include edge functions file watcher tests

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml
Currently it is broken: https://github.com/netlify/cli/actions/runs/2446489918
=> chore: fix codeql scanning

src/lib/one-graph/cli-client.js
Fixes regressions introduced in https://github.com/netlify/cli/pull/4778
---
=> fix(graph): regressions introduced during JWT migration

src/commands/graph/graph-edit.js, src/lib/one-graph/cli-client.js
=> fix(graph): use graphJWT in more places

.github/workflows/vale.yml, package.json
Download styles manually and fix the inputs of the vale-action. v2 has different inputs than v1
Created a test commit and it works now again:
Fixes #4831
=> chore: fix vale workflow

npm-shrinkwrap.json, package.json
Fixes an upstream issue in the Graph dependency
---
=> fix(graph): update graph dep

src/lib/one-graph/cli-client.js
Previously we didn't publish codegen metadata when requested by the Graph UI, this includes that data in the event payload rather than session metadata.
---
=> fix(graph): publish codegen module metadata for Graph ui

src/commands/build/build.js
Fixes https://github.com/netlify/pillar-workflow/issues/813
Typo in destructuring introduced in https://github.com/netlify/cli/pull/4949 led to unexpected behavior
---
=> fix: incorrect destructuring in `netlify build`

CONTRIBUTING.md
Adds a note to `CONTRIBUTING.md` referencing `export DEBUG=true`.
---
=> chore: add instructions on how to see stack traces

npm-shrinkwrap.json, package.json
I noticed this dependency isn't used anymore so I'd love to remove it.
---
=> chore: remove unused plugins-list dependency

package.json
Fixes a problem where the template won't load for error pages when running `netlify dev`
---
=> fix: update template path in package.json

src/commands/base-command.cjs, src/utils/command-helpers.cjs
Follow up to - https://github.com/netlify/bitballoon/issues/13488 - currently we fallback to offline config resolution if we get back an error from `@netlify/config` which we classify as an user error. This PR adds debug logs that log the output of said error.
---
=> fix: add debug logs to config resolution

src/commands/deploy/deploy.mjs, src/lib/edge-functions/proxy.mjs, tests/integration/100.command.dev.test.cjs
Loads import maps for edge functions from the Deno config file. CLI counterpart of https://github.com/netlify/edge-bundler/pull/256.
=> feat: load edge function import maps from Deno config file

src/functions-templates/typescript/log/{{name}}.ts
part of https://github.com/netlify/pod-compute/issues/316
=> feat: use console.log for logging in ef template

npm-shrinkwrap.json, package.json, src/commands/dev/dev.mjs, tests/integration/100.command.dev.test.cjs, tests/integration/500.command.dev.test.cjs
Fixes #4511 
The [static-server](https://github.com/nbluis/static-server/blob/84999917193f664c205efd587934bc6ea361fa78/README.md) dependency which is currently being used by the `netlify dev` command is now deprecated. This PR intends to replace the dependency with [fastify-static](https://github.com/fastify/fastify-static) (recommended by @lukasholzer).
---
🦖
=> fix(command-dev): replace deprecated static-server dep by fastify-static

src/commands/dev/dev.mjs, src/lib/edge-functions/headers.mjs, src/lib/edge-functions/proxy.mjs, src/utils/proxy-server.mjs, src/utils/proxy.mjs
Part of https://github.com/netlify/pod-compute/issues/343.
=> fix: if --debug, enable debug logging for edge functions

npm-shrinkwrap.json, package.json, tests/integration/utils/got.cjs
Partial fix to #4921 & #2744
This PR updates `got` to a non-vulnerable version & removes a workaround that's no longer needed after the update.
---
=> fix: update got & remove outdated workaround

npm-shrinkwrap.json, package.json
Partial fix for #4921, #2744.
Reduces the number of vulnerabilities from 20 to 16 in npm audit.
---
=> chore(deps): update node-version-alias to v2.0.0

npm-shrinkwrap.json, site/package-lock.json
Fixes https://github.com/netlify/cli/security/dependabot/57
---
=> fix(deps): update dependency shell-quote to 1.7.3

site/src/_layout.js
Just like on https://www.netlify.com/enterprise/contact/, this is a compliance requirement until we get cookie banners in place.
Deploy preview: https://dainty-cupcake-eebc3b.netlify.app/
---
=> docs: add links to compliance content in the footer

tests/integration/utils/snapshots.cjs
Trying to somehow make all the snapshot tests work.
---
=> fix: graph deprecation snapshots with normalization

src/lib/edge-functions/bootstrap.mjs
=> fix: update edge functions bootstrap to `641064c685071e00083eb682`

src/lib/edge-functions/bootstrap.mjs
=> fix: update bootstrap URL to `64109c4552d9020008b9dadc`

tests/unit/utils/get-package-json.test.mjs
While looking at #5573 I created this unit test
=> chore: add unit test for getPackageJson

tests/unit/utils/get-package-json.test.mjs
Sorry the previous PR was automerged. Here are the improved tests, which work independently from each other.
=> chore: improve on getPackageJson tests

site/src/_layout.js
This adds a tag, as requested by @stephan1echung 
---
=> feat: add tag inside the head element

src/lib/functions/registry.mjs, tests/unit/lib/functions/registry.test.mjs
This reverts https://github.com/netlify/cli/pull/5617#issuecomment-1505597286 because it broke a test and I don't want to block a new release.
---
=> fix: revert 8ae14561c600c86f3a69657eb641ac5431419d88

.github/workflows/unit-tests.yml, functions/error-reporting.ts, netlify.toml, package-lock.json, package.json, src/utils/command-helpers.mjs, src/utils/execa.mjs, src/utils/telemetry/index.mjs, src/utils/telemetry/report-error.mjs, src/utils/telemetry/request.mjs, src/utils/telemetry/telemetry.mjs, src/utils/telemetry/utils.mjs
Fixes https://github.com/netlify/pillar-workflow/issues/1224
---
=> feat: add bugsnag reporting to the CLI application

functions/error-reporting.ts, package-lock.json, package.json, src/commands/dev/dev.mjs, src/utils/detect-server-settings.mjs, src/utils/telemetry/report-error.mjs, tsconfig.json
Reports differences in the new build settings detection compared to the old framework detection to bugsnag.
---
=> feat: report differences for new framework detection

src/utils/telemetry/report-error.mjs
It gets pretty spammy when we report errors on the CI. 
We are more interested in real developer issues.
---
=> fix: don't report error on CI

package-lock.json, package.json, tests/integration/utils/rewiremock.cjs
seems the tests that were using this, were already migrated to vitest.
=> chore: remove unused rewiremock

tests/integration/telemetry.test.mjs
Fix for an integration test that was broken after https://github.com/netlify/cli/pull/5752 was merged.
=> chore: fix integration test

src/lib/functions/form-submissions-handler.mjs, src/lib/functions/server.mjs, src/utils/proxy.mjs, tests/integration/__fixtures__/dev-server-with-functions/functions/echo.js, tests/integration/__fixtures__/dev-server-with-functions/netlify.toml, tests/integration/commands/dev/redirects.test.ts
Closes https://github.com/netlify/pillar-support/issues/447.
=> fix: expose original URL search to function redirects

src/lib/functions/runtimes/js/builders/zisi.mjs, tests/integration/__fixtures__/dev-server-with-v2-functions/functions/brotli.mjs, tests/integration/__fixtures__/dev-server-with-v2-functions/functions/ping-ts.ts, tests/integration/commands/dev/v2-api.test.ts
Fixes https://github.com/netlify/pod-dev-foundations/issues/534
This PR makes the CLI support V2 Functions written in TypeScript, based on https://github.com/netlify/zip-it-and-ship-it/pull/1478.
---
=> fix: support typescript in V2 API

src/lib/edge-functions/bootstrap.mjs
We haven't updated the Bootstrap URL in two months - time to do so!
---
=> fix: update bootstrap URL

tests/integration/330.serving-functions.test.cjs
Adds test for functionality introduced in https://github.com/netlify/cli/pull/1460.
Helps https://github.com/netlify/pod-dev-foundations/issues/13.
=> chore: add test for function response validation

src/utils/telemetry/report-error.mjs
Fixes an error when a non-error class was reported that it was failing to report the issue.
---
=> fix: fixes a bug inside the error reporting

package-lock.json, package.json, src/commands/deploy/deploy.mjs
Closes https://github.com/netlify/pod-dev-foundations/issues/574.
=> fix: pass bootstrapUrl to runCoreSteps

src/commands/build/build.mjs, src/commands/deploy/deploy.mjs, src/lib/build.mjs
…build for config mutations
Fixes an issue where netlify build did not receive the package path and failed reading the config file for mutations on build plugins.
---
=> fix: fixes an issue where the package_path was not passed to netlify/build

src/commands/deploy/deploy.mjs
Fixes #6000
Fixes an issue where the provided `--dir` flag was not used in a monorepo example.
Will add tests for it in a follow up PR but I don't want to delay the release of it.
---
=> fix: fixes an issue where the provided --dir flag was not used

.github/workflows/integration-tests.yml
Investigating temp measures to help ease the frustrations around the integration tests atm
=> chore: temp increase of timeout for integration tests

src/lib/edge-functions/registry.mjs, tests/integration/commands/dev/edge-functions.test.ts
Follow-up to https://github.com/netlify/cli/pull/6018 addressing a couple of items from the code review.
=> fix: simplify file watching expression

.github/workflows/e2e-tests.yml
=> chore: disable E2E tests on Windows

package-lock.json, package.json, src/commands/integration/deploy.mjs, tests/integration/commands/integration/deploy.test.ts
Removes SDK as a dependency
---
=> chore: remove sdk dependency

tests/integration/commands/help/__snapshots__/help.test.ts.snap
Updates a test snapshot with the changes in https://github.com/netlify/cli/pull/6098.
=> chore: update test snapshot

.github/workflows/integration-tests.yml
Removes the logic to only run affected integration tests in PRs
=> chore: enable all integration test to run on each PR

.github/workflows/e2e-tests.yml, .github/workflows/integration-tests.yml, .github/workflows/legacy-tests.yml, .github/workflows/unit-tests.yml, package-lock.json, package.json
Reverts netlify/cli#6110
There looks to be an issue with E2E tests with v18.0.0 so reverting in order to investigate further
=> Revert "fix: min version should be lowest version of 18, not the latest"

README.md, docs/commands/addons.md, docs/index.md, src/commands/addons/addons-auth.mjs, src/commands/addons/addons-config.mjs, src/commands/addons/addons-create.mjs, src/commands/addons/addons-delete.mjs, src/commands/addons/addons-list.mjs, src/commands/addons/addons.mjs, tests/integration/commands/help/__snapshots__/help.test.ts.snap
This will not affect current users of the command, just updates the docs and hides the command from the help output in the CLI
=> feat: deprecate addons command

package-lock.json, package.json, src/commands/lm/lm-info.mjs, src/commands/lm/lm-setup.mjs, src/utils/lm/install.mjs, tests/integration/commands/lm/lm.test.ts
In attempt to remove bloat, we would like to remove modules that use `rxjs`. The list display package `listr` is included in this list of packages that use rxjs:
However, `listr2` does not. 
Large Media has been deprecated but not removed across Netlify, so although this presents some small display changes, I am not worried about any issues as this feature is minimally used.
The changes in the tests are because `listr` prints two messages to the terminal (one with `[started`] and the second with `[completed]`), where as `listr2` prints something like `❯ Configuring Git LFS for this site` for started, and `✔ Configuring Git LFS for this site` for completed, and the test didn't like looking for those symbols. 
| Before | After  |  
|---|---|
| …
=> feat: substitute listr for listr2 in lm commands

src/commands/addons/addons-list.mts, src/commands/api/api.mts, src/commands/env/env-import.mts, src/commands/env/env-list.mts, src/commands/functions/functions-list.mts, src/commands/recipes/recipes-list.mts, src/utils/addons/render.mts, tsconfig.json, types/ascii-table/index.d.ts
Replaces https://github.com/netlify/cli/pull/6157 as the git history there is in a wonky place.
Adds TS types for the `ascii-table` package
---
=> feat: add ascii-table types

src/lib/images/proxy.mts, tests/unit/lib/images/proxy.test.mjs
Follow-up to https://linear.app/netlify/issue/ADN-57/local-image-server-generating-incorrect-image-fit 
See https://netlify.slack.com/archives/C05V2MLPAFN/p1700061416759679?thread_ts=1700050188.131249&cid=C05V2MLPAFN
---
=> fix: use inside for contain

package.json
This starts the TS compiler using the '--watch' command to allow automatic builds when someone makes changes to an '.mts' file
---
=> feat: add 'dev' command to 'scripts' in package.json

src/commands/api/api.ts, src/commands/unlink/unlink.ts, src/utils/styles/index.ts
Fixes: https://linear.app/netlify/issue/CT-486/convert-unlink-command-to-clack
This converts the api command into using the new NetlifyLog. It is part of a bigger piece of work that can be seen in https://github.com/netlify/cli/pull/6293. This is also the reason why this PR is merged into the branch [CP-101/design-system-clack-implementation](https://github.com/netlify/cli/tree/CP-101/design-system-clack-implementation). It's a way in which I'm trying to keep possible failing tests, but also the review work to a minimum amount of work for those who are reviewing.
Before:
After:
---
=> chore: convert unlink command

src/commands/switch/switch.ts
=> feat: convert switch command to clack

package-lock.json, package.json, src/commands/deploy/deploy.ts
Part of https://linear.app/netlify/issue/FRA-82/create-integration-tests-for-monorepo-scenarios
---
=> fix: fixes an issue with uploading blobs in monorepos

src/lib/functions/registry.ts
Fixes https://github.com/netlify/cli/issues/6348.
=> fix: add nil-check guard

src/lib/edge-functions/proxy.ts, src/lib/functions/netlify-function.ts
Adds support for the configurable consistency model in Netlify Blobs to local development.
=> fix: support Blobs `consistency` in local dev

docs/commands/blobs.md, docs/index.md, src/commands/blobs/blobs.ts, tests/integration/commands/help/__snapshots__/help.test.ts.snap
Premature merge, will open a new PR with the same changes to put on hold 
Reverts netlify/cli#6392
=> Revert "feat: remove blobs beta tags"

src/lib/edge-functions/bootstrap.ts
Updates the edge functions bootstrap to the latest version.
=> fix: update edge functions bootstrap

src/utils/build-info.ts
Specified dev command should fix the case of multiple detected commands
ref CRE-1324
---
=> fix: dev server command override for multiple commands error

renovate.json
https://github.com/netlify/cli/pull/6531
---
=> fix(deps): pin get-port in renovate config

package-lock.json, package.json
Reverts netlify/cli#6613
See: https://github.com/netlify/cli/pull/6637
See: https://github.com/netlify/cli/pull/6531
=> fix(deps): revert "update dependency get-port to v7"

src/commands/deploy/deploy.ts, src/commands/serve/serve.ts, src/lib/functions/registry.ts, src/lib/functions/server.ts, src/utils/feature-flags.ts, src/utils/frameworks-api.ts, src/utils/run-build.ts, tests/integration/commands/deploy/deploy.test.js, tests/integration/commands/dev/serve.test.ts, tests/integration/utils/site-builder.ts, tests/unit/lib/functions/registry.test.js, tests/unit/lib/functions/server.test.js
Adds support for the Frameworks API to the `deploy` and `serve` commands.
=> feat: add support for the Frameworks API

package-lock.json, package.json, src/utils/deploy/hash-config.ts, src/utils/deploy/hasher-segments.ts, src/utils/read-repo-url.ts
Fixes my mania for dependency minimalism
No need to use hasha, hashing strings and files is pretty straighftoward.
---
N/A
=> chore(deps): remove hasha

src/commands/build/build.ts, src/commands/env/env-list.ts, src/commands/integration/deploy.ts, src/commands/types.d.ts, src/lib/build.ts, src/utils/command-helpers.ts, src/utils/types.ts
I ran into some confusing poorly typed code while working on https://github.com/netlify/cli/pull/7047, so I improved it and pulled it into a separate PR.
We should upstream these fixes to `@netlify/build` sooner rather than later though...
=> types: mildly improve type safety of build command

tests/integration/utils/mock-api.js
Adds a little mock for @mrstork 
---
=> chore: add mock for extensions meta endpoint

package.json
Accidentally committed in 4571be31c1ec29460327bc5f7061406729762c16.
=> fix: remove package.json#packageManager entry

package-lock.json, package.json
=> feat: bump blob version

package.json
=> revert: temporarily remove broken postinstal hook

eslint_temporary_suppressions.js, src/utils/live-tunnel.ts
The types fixes in https://github.com/netlify/cli/pull/7130 identified a number of bugs. This fixes one of those.
=> fix: add missing error handling for unauthed live tunnel use

src/recipes/ai-context/index.ts
Running `netlify recipe ai-context` and selecting the custom directory option does not download files. This is due to an unnecessary, unintentional early filter.
---
=> fix: ai-context was not able to find catchall due to early filter

src/commands/base-command.ts, src/commands/dev/dev.ts, src/lib/extensions.ts
Modifies dev so a user must initialize a site first (so we can install the extension, create a db, and add env vars).
---
=> feat: get user to initialize site first if they have neon installed for dev

site/astro.config.js, site/package-lock.json, site/package.json
There were some breaking changes, thus this PR instead of a normal dependency update.
Replaces: https://github.com/netlify/cli/pull/7158
---
=> fix: update astro and starlight

src/utils/proxy.ts
=> fix: remove log from proxy error handler
