netlify/cli

- lib/commands/deploy.js
Useful when working on several features that must be tested separately. It cuts the need to go to the *Build* page on the site to get the unique URL.
> Permalink is displayed after deployment (along with the alias URL).

- bin/cli.js
- lib/commands/deploy.js
- lib/commands/env.js
*Improvement of developer experience*
This command takes the environment variables from netlify and writes them either to stdout or to a file.
It should be especially useful for people using dotenv locally, because the output uses dotenv compatible syntax.
> Add "env" command

- lib/helpers/webui.js
**- Summary**
Fixes a typo in the authentication prompt. 
Prompt should be 'Please visit this authentication', not 'Please visite this authentication'.
Fixes authentication prompt typo
> Fix authentication prompt typo

- src/commands/deploy.js
Specifying a folder and functions folder during a deploy is now done only by flags.  The reason is, if you omit the flag, you are likely depending on the toml file or the settings you set in the web ui.  This is probably more correct default behavior than deploying the cwd.
```console
bret-netlify:cli bret$ netlify help deploy
Create a new deploy from the contents of a folder
USAGE
$ netlify deploy
OPTIONS
-f, --functions=functions            Specify a functions folder to deploy  
-p, --publish-folder=publish-folder  Specify a folder to deploy
DESCRIPTION
Deploys from the build settings found in the netlify.toml file, or settings from the api.
```
> Incorporate some flag design to the deploy command

- README.md
**- Summary**
Adds context to the available commands, replacing the existing Get Started and intro docs pages.
I couldn't get the `build:docs` command to work for me locally, so we still need to run that to generate the ToC and Command reference with Markdown Magic.
> [WIP] Add use case instructions to docs

- src/base/state/index.js
Catch missing folder errors as well as missing file errors on state lookup.
> Don’t throw on state lookup in a missing folder

- package.json
Update to `netlify@2.0.1-beta.8` to improve cli characteristics when creating very large deploys.
> Update to netlify@2.0.1-beta.8

- CONTRIBUTING.md
- README.md
- docs/contributing.md
This cleans up the README, makes the CONTRIBUTING file worth reading, and removes the getting started guide, which is going to live on the main docs website.
> Moving the usage docs to the docs website and other docs improvements

- src/utils/init/config-github.js
After updating to @octokit/rest@16.1.0, some of the methods were renamed.  This addresses that.  
Related to https://github.com/netlify/cli/pull/184
> Fix renamed GitHub method

- package.json
- src/commands/addons/index.js
- src/commands/deploy.js
- src/commands/functions/index.js
- src/commands/init.js
- src/commands/link.js
- src/commands/login.js
- src/commands/logout.js
- src/commands/open/admin.js
- src/commands/open/index.js
- src/commands/open/site.js
- src/commands/sites/create.js
- src/commands/sites/index.js
- src/commands/sites/list.js
- src/commands/status/hooks.js
- src/commands/status/index.js
- src/commands/unlink.js
- src/commands/watch.js
- src/utils/renderShortDescription.js
We want to add a plugins system so you can add additional tools that need to interact with your netlify account from the CLI.  This PR will implement and experiment with a plugins system.
Closes https://github.com/netlify/cli/issues/117
> Add a plugin system

- src/commands/init.js
- src/commands/sites/create.js
- src/utils/init/config-manual.js
**- Summary**
This PR attempts to offer some solutions to #177. Therefore it does two things:
1. When performing manual configuration, there is now an additional step that offers the option to change the remote repository (while defaulting to the one that it could read locally) and also validates against non-SSH URL's
2. When using `sites:create`, it now gives the option to set up Continuous Integration using all of the available methods in `configManual`, including the new option to set the remote git URL. My favourite new feature here is that this command can now be used to entirely configure manual CI without needing to have the repository local at all
The following is the output when using the `sites:create` with my default team and a random name:
This did not require …
> Allow CI setup without a local clone from sites:create command

- src/commands/init.js
This makes init work when you made a deploy to a site manually and want to upgrade to using CI.  It also adds a force flag so you can re-init a site that is already using CI.
> Improve init flow in various manual depoy states

- src/commands/deploy.js
We added `netlify deploy` to our CI workflow.
We had a directory error but the exit status was `0`.
We wanted the GitHub status check to fail in this case.
> Exit with status 1 on directory errors

- package.json
After adding a shrinkwrap I discovered npm stupidly installs devDependencies even when the package is installed as a global dependency.  When is that ever the desired case?  
Either way, this runs a production prune before packing, then undoes it.  Slower publish times, but at least we wont publish devDeps.
> Run prune before shrink-wrap

- package.json
This restores the original package-lock file after packing.  Before you may accumulate transient dependency changes without restoring.
> Restore original package-lock.json after packing

- package-lock.json
- package.json
- src/commands/deploy.js
Update js-client to 2.3.0 which incorporates https://github.com/netlify/zip-it-and-ship-it which provides better support for deploying unbundled functions. 
See the zip-it-and-ship-it repo for more details.
> Update js-client providing zip-n-ship capabilities

- npm-shrinkwrap.json
- package.json
Update netlify's js-client and semver floors.
- "@iarna/toml": "^2.2.3",
- "netlify": "^2.4.0",
-  "@oclif/dev-cli": "^1.21.1",
- "dependency-cruiser": "^4.13.2",
> Update netlify's js-client and semver ranges

- src/commands/addons/create.js
- src/commands/deploy.js
- src/utils/addons/prompts.js
**- Summary**
Update add-on validation to ensure required fields exist
> Update addon validation

- src/utils/init/config-github.js
- src/utils/init/netlify-toml-template.js
**- Summary**
closes #210 and #267
https://netlify.slack.com/archives/CEV26F3FF/p1552942688000100
when doing `netlify init`:
- if netlify.toml doesn't exist: offer to create one with the given settings
- if netlify.toml exists: use settings from netlify.toml as defaults
https://twitter.com/HumansOfLate/status/1107013958207238145
> make netlify init work with netlify.toml, see #210 #267

- src/commands/addons/auth.js
- src/commands/addons/config.js
- src/commands/addons/create.js
- src/commands/addons/delete.js
- src/commands/addons/index.js
- src/commands/addons/list.js
**- Summary**
closes https://github.com/netlify/cli/issues/274
locally tested
add alias for `netlify addons` command to also work with `netlify addon`
> add alias for addons command

- src/commands/deploy.js
**- Summary**
FIX for issue: #273
I found about Netlify at HiringMixer event by LendingClub. I instantly loved your product and wanted to contribute. So here's my first contribution. 👋 
There isn't much to test. Not sure if its right excuse here 😄 
-src/commands/deploy.js
`const EXISTING_SITE = 'â‡„  Link this directory to an existing site'`
I removed `"â‡„"`, which was unnecessary... Whose keyboard is this btw?
**Hi There!**
> Removed unknown character from log msg

- src/commands/addons/config.js
- src/commands/addons/create.js
- src/commands/addons/delete.js
- src/commands/addons/list.js
**- Summary**
Add-ons were registering as deleted if addon provider returned status other than 204.
This PR fixes that and only logs "deleted" when deletion successful
https://github.com/netlify/cli/pull/265/files#diff-1afb28914604869c18bfbc1b8b844178R58
> Update delete addon

- src/commands/init.js
- src/commands/sites/create.js
**- Summary**
When creating a new site using the web UI, the site name is subject to a validation rule that allows only alphanumeric characters and hyphens. The same doesn't happen when using the `netlify init` command in the CLI. This PR addresses that by introducing a validation rule with the same regular expression used in the web flow.
I've also added a few cosmetic changes to some user-facing messages in the `init` command, to make words like _Netlify_ and _GitHub_ capitalized in a consistent manner. I'm more than happy to make this a different PR (or discard it altogether), if you prefer.
I started writing an integration test, but then I saw that there is a big change to the testing architecture underway in #254. I didn't want to create possible merge conflicts, so …
> Validate site name on init command

- src/commands/sites/create.js
- src/commands/status/index.js
Cleans up the teams concepts in various commands.
Closes https://github.com/netlify/product/issues/190
> Fix status command to accommodate teams changes

- src/commands/addons/config.js
- src/commands/addons/create.js
Fix output for addons with no config
Issue:
```
➜  fun-fun-functions git:(master) ✗ netlify addons:create xyz
Starting the setup for "xyz add-on"
The xyz add-on has the following configurable options:
.
||
|
|
-|
'
```
Now we check for object keys to show prompts
> only show config prompts for addons with config

- src/commands/init.js
**- Summary**
Some of our output is a little confusing/unfriendly for those just trying- a lot sounds like errors when really it's working. I'm sending a doc via email documenting the experience path here on 6/3 to maintainers.
Update verbiage in output to be friendlier
> Friendlier output for newcomers

- src/commands/addons/config.js
- src/commands/addons/create.js
- src/commands/addons/delete.js
**- Summary**
It's really about the cosmetics so that we can show error and exit the CLI nicely whenever we get an error response from API. Paring PR of this is: https://github.com/netlify/js-client/pull/51.
This can be resolved many other ways and this is not the most efficient or so, happy to tweak if there is a better alternative.
I tested out several locally. Example:
From:
```
$ netlify addons:create large-media
Creating addon
Error: Error {"error":"Large Media addon doesn't support the repo linked to multiple sites"}
at createAddon (~/.npm-packages/lib/node_modules/netlify-cli/node_modules/netlify/src/addons.js:24:11)
```
To:
```
$ ~/dev/netlify/cli/bin/run addons:create large-media 
Creating addon                                       
›   Error: Large Media addon …
```
> Catch error and finish with error upon create/update/delte of addons

- src/commands/deploy.js
First part of programatic data from deploy command.
```
netlify deploy --json
✔ Finished hashing 15 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
✔ Draft deploy is live!
{
"Logs": "https://app.netlify.com/sites/1111/deploys/5ccc8b52c8b992018cc60ace",
"Live Draft URL": "https://5ccc8b52c8b992018cc60ace--1111.netlify.com"
}
```
The `api.deploy` from SDK will need a silent option to kill spinners/messages
```
results = await api.deploy(siteId, deployFolder, {
configPath: configPath,
fnDir: functionsFolder,
statusCb: deployProgressCb(),
draft: !deployToProduction,
message: flags.message
})
```
> add —json flag for programatic access

- src/utils/link/link-by-prompt.js
**- Summary**
`netlify link` makes you manually enter the name of your site, which may result in human error and a tedious process. I wanted to give users a list of sites so there's no human error involved.
Better DX for linking sites in `netlify link`
> use a list of sites to chose from rather than entering the name manually

- README.md
- package.json
- src/commands/sites/create.js
**- Summary**
Based on feedback from our CLI call. This PR improves the messaging when you create a site through the CLI and when that command fails. 
Modifies the messaging to include the idea of a global site creation failure rather than a local one. Users will be confused when the site creation fails based on the name if the name is not outright determined to be a global conflict. 
> updates messaging for creating sites and error messages

- .gitignore
**- Summary**
I'm working with IntelliJ Idea IDE and this is a IDE config directory that doesn't need to be shared.
* Open the CLI project in any IntelliJ Idea IDE.
* `.idea` wont show up as untracked files in your `git status`
This small change adds `.idea` directory to `gitignore`
> Ignore .idea dir

- src/commands/sites/create.js
**- Summary**
When doing `netlify init` right now, if you choose a `Site name` that is already taken, the process fails and exits. This change allows the user to reenter a new `Site name` for their project without exiting.
First attempt with HEAD state:
- Run `netlify init` in a new project
- Choose `Yes, create manually deploy site`
- Enter `test` as `Site name`.
- Choose your team. The command will error out and exit with `Error: test.netlify.com already exists. Please try a different slug.`
Second attempt with this branch:
- Run `netlify init` in a new project
- Choose `Yes, create manually deploy site`
- Choose your team
- Enter `test` as `Site name`. The command will show a warning `Warning: test.netlify.com already exists. Please try a different slug.`. But will …
> Allow user to choose another site name if current doesn't exist

- src/utils/gh-auth.js
**- Summary**
Remove GitHub token from URL (query parameters) by using `history.replaceState`, so that, it won't be stored in browser's history.
* Remove your Github credentials from `~/.netlify/config.json`
* Do `netlify init` for a project with Github as remote
* Chose to sign in to Github via app.netlify.com
* Authorize
* Check the browser's URL after you're redirected back to `localhost`
* Use `history.replaceState` to remove query parameters from URL on the page we serve from localhost
> Remove Github token from browser history

- README.md
- docs/commands/deploy.md
- docs/commands/dev.md
- docs/commands/functions.md
- docs/commands/index.md
- docs/commands/open.md
- docs/commands/sites.md
- docs/index.md
- npm-shrinkwrap.json
- package.json
- scripts/docs.js
- scripts/generateCommandData.js
- src/commands/addons/auth.js
- src/commands/addons/config.js
- src/commands/addons/create.js
- src/commands/addons/delete.js
- src/commands/addons/index.js
- src/commands/addons/list.js
- src/commands/deploy.js
- src/commands/open/index.js
- src/commands/sites/delete.js
- src/commands/sites/list.js
- src/commands/status/index.js
- src/tests/addons.test.js
To better support programatic use cases, this PR adds `--json` flag support for relevant commands.
This will disable normal CLI logging and only output `json` for the user to parse and use elsewhere
Example:
Depends on https://github.com/netlify/netlify-dev-plugin/pull/224 & https://github.com/netlify/cli-utils/pull/13
> Add global --json, --auth, && --silent flag support

- .gitignore
- package-lock.json
- package.json
- src/commands/init.js
- src/commands/link.js
- src/utils/gitignore.js
- src/utils/link/link-by-prompt.js
Fixes https://github.com/netlify/cli/issues/282 & https://github.com/netlify/cli/issues/219
This will automatically add `.netlify` folder to gitignore folder of folder.
It will ignore `.gitignores` that already contain `.netlify`
Runs whenever `netlify init` or `netlify link` is ran
> Automatically Ignore .netlify folder on init/link

- src/commands/login.js
- src/commands/switch.js
**- Summary**
Adds a new command (`netlify switch`) to allow you to switch between different Netlify accounts in CLI.
Fixes: https://github.com/netlify/cli/issues/105
* `netlify switch`
* Select "I would like to login to a new account". You'll be logged into the new account and your current account in CLI will be updated to reflect the latest.
* `netlify switch`, you can now see both accounts and switch between them
* Adds a new flag to `netlify login` (`--new`), that allows you to login to a new Netlify account even if you're already logged in
* Adds a new command `netlify switch` that allows you to switch between already logged in accounts and login to a new one
> Add command to switch active Netlify account

- src/utils/live-tunnel.js
**- Summary**
Prevents the live-tunnel binary from being redownloaded every time `netlify dev --live` is run. Closes #417.
Resolution of #417 was confirmed manually in a Windows 10 VM. `npm run test` results in test failures, but they seem unrelated to this change as an identical test failure occurs on the master branch.
Fix repeated downloads of live-tunnel binary on Windows
> Fix repeated downloads of live-tunnel binary on Windows

- src/detectors/jekyll.js
My GH pages Jekyll setup fails without this change.
**- Summary**
Remove `-l` param from `possibleArgsArrs` option.
> Jekyll detector: Remove -l param

- src/detectors/parcel.js
**- Summary**
The Netlify CLI does not currently detect the bundler [Parcel](https://parceljs.org/). This pull request adds a detector to detect it.
Create the file `src/index.html`. At a minimum it should contain valid HTML.
Install [parcel-bundler](https://www.npmjs.com/package/parcel-bundler).
```
npm i -D parcel-bundler
```
Add a dev script in `package.json`.
```
"scripts": {
"dev": "parcel src/index.html",
},
```
Run Netlify Dev.
```
netlify dev
```
Parcel bundles the project and serves a hot-reloading dev server on port 1234. Netlify Dev proxies it on port 8888.
```
PS C:\Users\thorn\Development\netlifytest> netlify dev
◈ Netlify Dev ◈
◈ Starting Netlify Dev with parcel
Waiting for localhost:1234.
◈ Lambda server is listening on 34567
> netlifytest@2.2.4 dev …
```
> Add Parcel detector

- src/utils/link/link-by-prompt.js
Restores the site name search functionality removed in #335, along with some minor updates to copy and code. Partially addresses #496.
Run the `netlify link` command and try all of the options in the prompt tree:
- Use Git remote
- with no `origin` set in `git remote` (prompt won't display in choices)
- with an `origin` set that has no connected sites
- with an `origin` set that has one connected site (this may still fail due to #498 and https://github.com/netlify/js-client/issues/39)
- with an `origin` set that has more than one connected site (may also fail for same reasons)
- from an account with no sites
- Search by name
- with a string of garbage text that you know won't match anything
- with a unique site name that isn't also part of another site name
- with a short string that you …
> Improve prompts for `link` command

- src/commands/dev/index.js
- src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/425
We were not passing the `port` of the configured `to` address when creating a proxy. Which was a proxy to invalid address. This PR fixes that along with another fix for `reqUrl`'s protocol.
Create a redirect in your config. e.g.:
```
[[redirects]]
from = "/graph"
to = "http://localhost:34567/hello-world"    # a address for hello-world on functions server
status = 200
```
Run `netlify dev`
Now visit [http://localhost:8888/graph](http://localhost:8888/graph).
* Fix `protocol` when creating `reqUrl`
* Use `host` instead of `hostname` when creating `target` for proxy
🐨
> Fix port for proxy redirects

- docs/commands/dev.md
- docs/netlify-dev.md
- src/commands/dev/index.js
- src/utils/detect-server.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/452
Make port for functions server configureable when running via `netlify dev`.
* Run `netlify dev` in [https://github.com/raeesbhatti/netlify-redirect-test](https://github.com/raeesbhatti/netlify-redirect-test/tree/dceebb6f4ef8bf7fc8c786316049e4a6d90eb2cc)
* Go to http://localhost:4567/hello-world in your browser
* Try to use `functionsPort` coming from `config` as port for functions server if defined, otherwise revert to 34567.
🐶
> Dev: Make functions port configureable

- src/commands/dev/index.js
- src/commands/functions/create.js
- src/detectors/README.md
- src/utils/init/netlify-toml-template.js
**- Summary**
Hello! I was playing with the local `dev` feature (which I see that you *just* moved here) and a link popped up in the output that still goes to the readme in the old repo (specifically the Project Detection section of the docs).
Ran the same commands after making my changes and all seems fine, but this is my first time contributing here so please let me know if I missed anything!
I've replaced links to the appropriate equivalent file in this repo. Left old links intact that referenced issues that have been closed over there. 
https://github.com/netlify/netlify-dev-plugin#project-detection => https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection …
> Update links to netlify dev documentation

- src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/530
`dir` flag was specified but its value was not being used. This change makes it so that if `dir` flag is specified, it ignores the detected server.
* `npx create-react-app my-project`
* `cd my-project`
* `yarn build`
* `netlify dev --dir=./build`
Makes it so that if `dir` flag is specified, it ignores the detected server and using a static server.
🦁
> Dev: Respect the dir flag for serving directory

- src/utils/redirect-parser/line-parser.test.js
**- Summary**
This PR fix the failed test. The test trying read file by relative path, and it is failed. I've add global variable `__dirname`__dirname` to path.
Please run the command:
```
$ yarn test:ava
```
and make sure that the test `src/utils/redirect-parser/line-parser.test.js` not failed.
Fix the test, use absolute path to path in `fs.readFileSync`
> Fix: Fixing the relative path in test

- src/commands/dev/index.js
**- Summary**
DEPENDS ON: https://github.com/netlify/libredirect/pull/61
Fixes: https://github.com/netlify/cli/issues/423
* Have following in your `netlify.toml`:
```
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
headers = {X-From = "Netlify"}
[build]
functions = "functions/"
```
* Have following in `/functions/hello-world.js`
```
exports.handler = function(event, context, callback) {
callback(null, {
statusCode: 200,
body: JSON.stringify(event.headers),
});
}
```
* Goto http://localhost:8888/api/hello-world in your browser
* Expect to see `"x-from": "Netlify"` in the response
* Iterate through `match.proxyHeaders` and set them on request
* Make sure `functions` and `addons`requests are properly routed …
> Dev: Allow custom headers on rewrites

- src/utils/get-functions.test.js
**- Summary**
I've added the test for `get-functions.js`
Please, run the test `get-functions.test.js`
New test for `get-functions.js`
> Dev: Add new tests for get-functions.js

- src/commands/addons/config.js
- src/commands/addons/create.js
- src/commands/addons/delete.js
- src/commands/addons/list.js
- src/commands/api.js
**- Summary**
The API documentation URLs are about to change due to https://github.com/netlify/open-api/pull/182.
Note: this PR should be merged at the same time as https://github.com/netlify/open-api/pull/182, otherwise links will be broken.
Update API documentation URLs.
> Update API documentation URLs

- .circleci/config.yml
- package.json
**- Summary**
Our `package.json` is showing our supported Node.js version as `8.0.0`. However:
- we are using object spreads, which are `>=8.3.0`
- many of our dependencies are not supporting some minor versions of `8.*.*`. For example `execa` is `>=8.12.0` because of the use of `util.getSystemErrorName()`.
I checked dependencies and it seems like the Node.js version we actually support is `>=8.12.0`. We should advertise that one instead.
Fix supported Node.js version
> Fix supported Node.js version

- src/commands/dev/index.js
There was a const being declared with the same name as a function in the outer scope. I _think_ this could be responsible for #569, but in any case it’s probably worth renaming to avoid confusion/naming collisions.
**- Summary**
> fix: remove naming conflict

- src/tests/utils/cliPath.js
**- Summary**
Small testing fix I noticed while working on changes for #566. I've hit similar issues with my own CLI tools often, so I've moved all my code checkouts into a folder with a space in the name, it's great for catching these bugs :smiley:
* Check out the codebase in a path containing spaces
* `npm install`
* `npm test`
* `addons.test.js` fails because broken paths mean that it can't run the CLI
Stop tests from failing when run from a path containing spaces.
> Fix tests when run in a path containing spaces

- package-lock.json
- package.json
This enables semver with the Netlify Build dependency. This means `netlify/cli` will automatically pick up new non-breaking versions of `netlify/build`. 
Since `netlify/build` is still in `0.*.*`, this means picking any version that starts with `0.*.*` but not `1.0.0`.
This also upgrades `netlify/build` to the latest version with the following changes:
- add support for Node 13
- add support for Windows
- improve error stack traces
> Use semver with Netlify Build

- package-lock.json
- package.json
- src/commands/build/index.js
**- Summary**
This improves the `netlify build` command.
This fixes the following:
- analytics was not run if an error was thrown inside `netlify/build`
- the exit code was `0` instead of `1` on Netlify Build errors
- `@netlify/cli-utils` was used instead of `utils/command.js`. However we've deprecated `@netlify/cli-utils` and move the base command to `utils/command.js`.
- fix semver issue with `@netlify/build` (see #592)
This adds the following:
- adds the `--context` CLI flag
- improves the description for the `--dry` CLI flag
- improves the error message thrown when `--config` is invalid (it's thrown by `@netlify/config`)
This simplifies the following logic:
- the `configPath` logic has been moved to `@netlify/config`
Improve `netlify build` command. …
> Improves `netlify build` command

- src/commands/build/index.js
The Netlify configuration file should be optional. At the moment calling `netlify build` without one throw an error. This PR fixes this.
Implementation detail: note that `getConfigPath(undefined)` never throws.
Related: https://github.com/netlify/build/pull/499 and https://github.com/netlify/build/issues/497
> Allow no configuration file with `netlify build`

- docs/netlify-dev.md
- src/commands/dev/index.js
**- Summary**
Some users have a requested a way to disable the feature in Netlify Dev that automatically launches the local dev server in browser. This change implements a way to disable that feature from `netlify.toml`. Fixes https://github.com/netlify/cli/issues/615
Add the following to your `netlify.toml`
```
[dev]
autoLaunch = false
```
Run `netlify dev`
Check for `config.dev.autoLaunch` to determine if we should launch the browser automatically or not.
🐥
> Allow configuration of auto launch feature

- package-lock.json
- package.json
- src/utils/rules-proxy.js
Remove toml parser ref b/c @netlify/config is handing this now.
Remove `netlify-cli-logo` package. It's inlined here
> chore: remove unused deps

- docs/commands/functions.md
- docs/index.md
**- Summary**
I noticed some broken links when reading the function documentation and felt like it was my duty to fix them
**Case 1**
1. Navigate to https://github.com/netlify/cli/blob/master/docs/index.md
1. Click on any of the function subcommands
_**Expected Results**_
Taken to the appropriate page
_**Actual Results**_
404
**Case 2**
1. Navigate to https://github.com/netlify/cli/blob/master/docs/commands/functions.md
1. Click on any of the function subcommands
_**Expected Results**_
Taken to the appropriate page
_**Actual Results**_
404
Fixes broken links to function subcommands that were missing the `.md` part of the URL
_Approved by Riley 😝_
> Add .md to broken function subcommand links

- src/commands/deploy.js
**- Summary**
"netlify deploy --json" was only showing "site_id" and "deploy_id" ...etc but was not enough information for us, so I add a new field "site_name" into that output.
Run `netlify deploy --json` and check an output that should have a fileld like `{ ... "site_name": [SITE_NAME] }`
- `deploy --json` output has a new field "site_name".
> Output site_name when deployed with --json arg

- src/commands/dev/index.js
**- Summary**
Based on #658
When running `netlify dev` neither default functionsPort nor port passed in configuration is used.
Add to netlify.toml
```
[dev]
functionsPort = 30303
```
and verify the port is used
Remove duplicate call to getPort for the same port (default: 34567)
> Remove duplicate port allocation - fixes #658

- package-lock.json
- package.json
- src/commands/dev/index.js
- src/utils/rules-proxy.js
**- Summary**
Standardizes parsing of redirect rules by offloading it to the new API's of `netlify-redirect-parser`. Depends on https://github.com/netlify/netlify-redirect-parser/pull/8
* Run `netlify dev` in any existing project with redirect rules defined
* Pass down `configPath` to the redirect parsing logic
* Don't try to read all config files manually
* Only watch `_redirects` and adopted Netlify config file for redirect rules
* Use `netlify-redirect-parser`'s new `parseNetlifyConfig` function to parse different kinds of config files (`netlify.toml`, `netlify.yml` and `netlify.json`)
> Revamp redirects parsing

- src/commands/dev/index.js
- src/utils/serve-functions.js
**- Summary**
This PR assigns a port for the functions server in the `dev` command, sets it in the config and then uses it when starting the functions server. Previously, duplicate logic could result in the functions server starting on a specific port and then the CLI waiting for it on another port. This would prevent startup of the whole dev environment (_endless dots_).
The port is elected as follow:
- `functionsPort` option in `netlify.toml` if provided
- `34567` otherwise
If the elected port is currently in use, a random port is assigned.
This fixes the following issues: #659 #634 
The test must be run in a context where the functions server is started. This requires a `.functions` directory with appropriate contents.
The code was tested with the following …
> Fix functions server port assignment

- src/commands/dev/index.js
**- Summary**
This PR reverts the default `autoLaunch` to `true`, the way it works in the current release of `netlify-cli`. Motivation is explained in https://github.com/netlify/cli/pull/631#issuecomment-571555799.
The change is really basic so not much testing is needed, but I tested it with a new basic project with and without a `netlify.toml`.
Probably shouldn't be included in the changelog since it reverts a change present in master but not yet released.
> Revert default autoLaunch behavior to true

- src/detectors/expo.js
**- Summary**
This PR adds a detector for `netlify-cli` to work automagically with Expo projects.
Prior to this, every project needed to be configured using `netlify.toml` before `netlify dev` could be used.
This also fixes #333 since `netlify publish` now uses the detector config to find the publish directory.
I created a new blank Expo project, ran the `dev` command on that folder and it started up successfully. Then I ran the `publish` command and it didn't ask for the build directory.
*Note*: I also needed to use #669 or the port allocation of the functions server becomes random and `netlify dev` can't connect.
Add detector for Expo
> Add detector for Expo

- docs/netlify-dev.md
**- Summary**
I was reading the documentation for `netlify dev` and noticed that the detectors link goes to the archived netlify-dev-plugin.
Does not apply.
Documentation now links to current folder of detectors.
> Update path to detectors folder

- src/detectors/ember.js
**- Summary**
This detects that a project is using ember-cli and runs the appropriate command.
Running `netlify dev` inside an ember-cli project correctly identifies and starts the project.
`netlify dev` now detects ember-cli projects.
> Add ember detector

- package-lock.json
- package.json
**- Summary**
This upgrades the JavaScript to its [latest major release](https://github.com/netlify/js-client/releases/tag/v3.0.0).
I have checked the source code and tried to run few CLI commands locally and everything looks ok. 
However during the code review, if you could please make some additional manual tests, this might be a good idea :)
Upgrade `js-client` to `3.0.0`
> Upgrade js-client to `3.0.0`

- package.json
- src/utils/serve-functions.js
**- Summary**
Fixes `console.log`s not working in latest version when running Netlify Functions with `netlify dev`.
Fixes: https://github.com/netlify/cli/issues/716 
* Add `console.log` to your Netlify Function and run it through `netlify dev`
Use `winston` to provide custom logger for `lambda-local`
🐥
> Dev: Fix Netlify Functions logging

- src/commands/build/index.js
**- Summary**
The `--context` CLI flag with `netlify build` is currently not working. 
This is due to a bug in how the CLI flags are parsed.
This PR fixes that.
Manual tests only.
Fix `--context` CLI flag for `netlify build`.
> Fix `--context` CLI flag for `netlify build`

- src/commands/build/index.js
We currently allow unknown CLI flags to be passed to `netlify build`, instead of validating them. This was due in order to make the template variable `${opt:...}` work. Since templating has been removed from Netlify Build, we can now enforce strict CLI flags validation for this command.
> Enforce strict validation of build command CLI flags

- src/utils/dev.js
> [dev] Add support for injecting shared environment variables

- src/commands/dev/index.js
- src/tests/dummy-site/functions/env-file/.env
- src/tests/dummy-site/functions/env-file/env-file.js
- src/tests/dummy-site/functions/no-env.js
- src/tests/dummy-site/functions/override-process-env/.env
- src/tests/dummy-site/functions/override-process-env/override-process-env.js
- src/tests/serve-functions.test.js
- src/utils/serve-functions.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/734
Env variables set in [app.netlify.com](https://app.netlify.com) override variables in `.env` files for functions when running with `netlify dev`.
**- If the current behavior is a bug, please provide the steps to reproduce.**
* Link your project to a Netlify site using `netlify link`
* Create an env variable in [app.netlify.com](https://app.netlify.com) for your site
* Create a `.env` file in your function directory with the same variable name (access that env variable in your function)
* Run `netilfy dev` and access your function, see the value for the env var
* Record `process.env` before creating functions handler
* Provide variables from `.env` file to `lambda-local` (will …
> Allow overriding functions env vars with .env file

- src/hooks/init.js
Fixes #739. The line removed in this PR was added long ago without an issue or PR, so it isn't clear why we need it. Since disabling telemetry via config bypasses this call altogether, we should bypass it for users that disable via flag as well. `track()` shouldn't be called at all for users who disable telemetry.
> fix(telemetry): do not track disabling of telemetry

- package-lock.json
- package.json
- src/commands/build/index.js
- src/utils/command.js
Due to https://github.com/netlify/build/pull/868, the latest major release of `@netlify/config` had to merge the method for resolving the configuration and the method for retrieving the configuration file path.
This breaking change requires the CLI to be updated accordingly.
> Upgrade `@netlify/config`

- src/commands/dev/index.js
- src/tests/dev.test.js
- src/tests/dummy-site/.env
- src/tests/dummy-site/functions/env-file/.env
- src/tests/dummy-site/functions/env-file/env-file.js
- src/tests/dummy-site/functions/env/env.js
- src/tests/dummy-site/functions/override-process-env/.env
- src/tests/dummy-site/netlify.toml
**- Summary**
Fixes: https://github.com/netlify/cli/issues/747
* Added tests
* Have a `.env` file in your project root
* Access those vars in Netlify Functions via `netlify dev`
* Use `Object.entries` instead of `Object.values` 🤦🏽‍♂️
🙈
> 🐛 Fix a loop for setting env vars

- package-lock.json
- package.json
This upgrades `@netlify/build`. This should not be necessary since we use semver. However semver only works when users are updating their `package-lock.json`. Making a dummy new release of the CLI (which is essentially the goal of this PR) will update users lock files (if they upgrade Netlify CLI). 
This is important as part of the MVP, to make sure users get the same experience on Netlify CLI than in the UI.
> Upgrade `@netlify/build`

- package-lock.json
- package.json
- src/commands/deploy.js
- src/commands/watch.js
- src/utils/log_streamers/firebase.js
- src/utils/log_streamers/humiobase.js
- src/utils/log_streamers/index.js
- src/utils/log_streamers/nats-streamer.js
- src/utils/log_streamers/resources.js
- src/utils/log_streamers/socketeer.js
- src/utils/logs.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/69
Fixes: https://github.com/netlify/cli/issues/119
Fixes: https://github.com/netlify/cli/issues/70
Run `netlify deploy --trigger` in a project dir that is linked and has CI configured.
Run `netlify watch <deployId>` to watch logs for that deploy
* Import log streamers from app.netlify.com codebase
* Move `waitForBuildFinish` function out of `watch` command
* Use log streamers in `waitForBuildFinish` if `deployId` is provided
* Run `waitForBuildFinish` in `netlify deploy --trigger`
🐕
> Add support for getting/tailing deploy logs

- src/detectors/gridsome.js
- src/detectors/utils/jsdetect.js
**- Summary**
This PR fixes an issue with `gridsome`'s detector config and introduces support for `pnpm` as a package manager.
I didn't changed the name of the exported function to avoid touching more files than needed. This should be changed at some point, probably. Let me know if you'd want me to change it myself before merging.
Some tests were breaking and they still break at the same spot. Changes are minimal so everything should still work the same.
- fixes an issue with `gridsome`'s detector config: [link](https://gridsome.org/docs/how-it-works/#gridsome-build)
- introduces support for `pnpm` as a package manager: [link](https://pnpm.js.org/en/cli/install)
> Add support for `pnpm` + Fix issue with `gridsome`detector

- src/detectors/quasar.js
This help prevent the need to remember to load a different url when using netlify dev instead of quasar dev.
> change to run netlify dev on the port that quasar normally uses

- src/commands/dev/index.js
**- Summary**
This is to fix an inconsistency in NodeJS which results in `process.env` not realizing changes if they're accessed shortly after.
Fixes: https://github.com/netlify/cli/issues/747
* Have your `create-react-app` project connected to Netlify production with `netlify link`.
* Have some env variable in Netlify production
* Have a `.env` file in project root locally that overrides that env variable
* Run `netlify dev` and observe the value of that env variable
Pass the variables from `.env` file as `setting.env` object to `startDevServer`, so that, they're set explicitly on the new process.
🐳
> Dev: Pass .env vars as an object to child process

- package-lock.json
- package.json
This upgrades `zip-it-and-ship-it` to the latest version used inside Netlify Build.
This new version should be backward compatible, although it has not been tested with many real users yet.
This will ensure Netlify Build users are using consistent versions for `zip-it-and-ship-it` since that library is used separately by several projects: Netlify Build, Netlify CLI and the JavaScript client, which are requiring each other.
If there are issues in the beta version of `zip-it-and-ship-it`, it is better for us to catch those with local builds than with production builds.
This PR also upgrades to the latest major of the `js-client`. That major version only adds one thing: upgrading to the latest `zip-it-and-ship-it` as well (see https://github.com/netlify/js-client/pull/90). This PR put both …
> Upgrade `zip-it-and-ship-it` and `js-client`

- src/commands/build/index.js
Now that Netlify Build is officially in Beta, we should make the `netlify build` CLI command visible.
This also adjusts the command's description.
> Make `netlify build` visible

- package-lock.json
- package.json
This upgrades `@netlify/build`. This should not be necessary since we use semver. However semver only works when users are updating their `package-lock.json`. Making a dummy new release of the CLI (which is essentially the goal of this PR) will update users lock files (if they upgrade Netlify CLI). 
This is important as part of the MVP, to make sure users get the same experience on Netlify CLI than in the UI.
Important: I could not update `package-lock.json` since Netlify CLI fails to install on my machine due to #769. Could someone not on Linux help me run `npm install` to update that file then push to this PR? Thanks!
> Upgrade `@netlify/build` and `@netlify/config`

- src/commands/build/index.js
Currently `netlify build` passes the `dry: false` option unless it is set to `true` with the `--dry` CLI flag. We should instead pass `dry: undefined` to prevent the CLI flags from being unnecessarily logged.
> Do not pass `dry: false` option to `netlify build`

- package-lock.json
- package.json
Netlify Go Functions were broken. The new version of `zip-it-and-ship-it` is fixing it.
This PR upgrades to the latest version of `zip-it-and-ship-it`. The `js-client` uses it too and just made a patch release, included in this PR too.
> Fix Netlify Go Functions

- src/utils/get-functions.test.js
`src/utils/get-functions.js` uses `path.resolve`, meaning it returns `\\` on windows.
So it makes sense to use `path.*` methods or variables in tests, instead of hardcoded `/` separator (e.g. `/index.js` => path.sep + 'index.js')
fixes this test result
```
utils » get-functions » pass dummy repository with *.js files
C:\work\netlify-cli\src\utils\get-functions.test.js:20
19:   const f = getFunctions(sitePath)
20:   t.deepEqual(f, {
21:     index: {
Difference:
{
index: {
-     functionPath: 'C:\\work\\netlify-cli\\src\\tests\\dummy-repo\\index.js',
+     functionPath: 'C:\\work\\netlify-cli\\src\\tests\\dummy-repo/index.js',
moduleDir: 'C:\\work\\netlify-cli',
},
}
```
> fix: use path.sep in get-functions.test.js

- package-lock.json
- package.json
- src/commands/build/index.js
- src/utils/command.js
This upgrades to the latest version of `@netlify/build` and `@netlify/config`. This includes the breaking changes:
- the `siteId` option is now passed to `@netlify/config` instead of `@netlify/build`
- the `token` option must now be passed to `@netlify/config`
Those changes are due to the ongoing work on supporting UI build settings in local builds (https://github.com/netlify/build/issues/962).
> Upgrade to latest `@netlify/build` and `@netlify/config`

- package-lock.json
- package.json
- src/commands/build/index.js
- src/utils/command.js
This upgrades to the latest version of `@netlify/build`, `@netlify/config`, `netlify` and `@netlify/zip-it-and-ship-it`.
The Netlify CLI now passes a `--mode=cli` option so that Netlify Build can adapt some of its behavior depending on whether the build is run from the CLI or not.
> Upgrade to latest version of Netlify Build

- src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/802
Run `netlify dev` in a static project without functions directory specified or present.
Check if a `functionsDir` is present before awaiting for functions server port.
🦄
> Dev: Don't wait on functions port if no server

- src/commands/dev/index.js
- src/tests/dummy-site/netlify.toml
- src/tests/rules-proxy.test.js
- src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/794
`netlify dev` in `create-react-app` project
* Don't filter out homepage rule for SPA servers
* Pass server type to redirector
* Don't check for static files for redirect rules if server type is present (meaning that it's not a static server)
> Don't rely on files on disk for redirects when working with SPA servers

- .github/ISSUE_TEMPLATE.md
- src/commands/status/index.js
- src/hooks/init.js
**- Summary**
`netlify status` shows information about current signed-in user and their linked site which is private information. `--verbose` flag shows information about current system and installed `netlify-cli` package.
IMO it makes more sense to move it to `netlify version` command. This way users can paste results of `netlify version --verbose` and it will give us a complete picture of their environment without a possibility of accidentally logging private information.
`netlify version --verbose`
Move `--verbose` flag logs to `netlify version` command.
> Move --verbose flag to netlify version command

- package.json
- src/commands/dev/index.js
**- Summary**
Fix `netlify dev` on Windows. Use `which` package to resolve path for command before spawning it. Apparently, Windows doesn't allow spawning binaries without using full path.
Fixes: https://github.com/netlify/cli/issues/689
Run `netlify dev --offline` in this project: https://github.com/sw-yx/gatsby-netlify-form-example-v2
Use `which` package to resolve path for command before spawning it.
🐼
> Dev: Resolve command before spawning

- src/utils/rules-proxy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/819
* Create new create-react-app project
* Run netlify dev
Check for `configPath` variable before trying to resolve it and parse config.
🐶
> Dev: Dont crash on no config file

- src/commands/dev/index.js
- src/tests/addons.test.js
- src/tests/utils/cliPath.js
- src/utils/rules-proxy.js
**- Summary**
If the path to binary is not quoted on Windows and contains a space, it will get the path wrong and fail. This change makes sure that the path to app binary is quoted.
Fixes: https://github.com/netlify/cli/issues/817
* Have your app binary in path with spaces
* Run `netlify dev`
Quote app binary path before spawning it.
🐬
> Improve child process spawning

- src/commands/dev/index.js
**- Summary**
Pipe `stdin` of parent process to `stdin` of spawned app process.
Ref: https://github.com/netlify/cli/pull/818#discussion_r407461613
> Dev: Pipe stdin from parent to app process

- src/commands/dev/index.js
**- Summary**
Just another improvement. This mean that when proxying to an app server, it will process the redirect even if a static file exists. Which is the behavior we want. Also makes sure that we only use status code from matched rule if we're going to rewrite.
Fixes: https://github.com/netlify/cli/issues/640
`netlify dev` in `create-react-app` project
* Process rewrite rules for app server as well
* Only update `status` code when a rewrite is made
🐿
> Dev: Process match fixes

- src/commands/dev/index.js
**- Summary**
We were checking if path existed to determine if it was a static file request but that meant that directories also got a false positive. Now we're checking if there's a file on that path.
Fixes: https://github.com/netlify/cli/issues/832
Described in https://github.com/netlify/cli/issues/832#issue-599701933
* Use `fs.stat` instead of `fs.existsSync`
* Check if `stat.isFile()`to make sure
🙈
> Dev: Improve static check

- package-lock.json
- package.json
- src/commands/dev/index.js
**- Summary**
A 100% reliable solutions to prevent child processes from clearing screen when piping `stdout` and `stderr`.
Strip away ANSI Control Character that are used for moving cursors or screen clearing.
Fixes: https://github.com/netlify/cli/issues/666
Fixes: https://github.com/netlify/cli/issues/579
Fixes: https://github.com/netlify/cli/issues/590
Run `netlify dev` in a [VuePress project](https://vuepress.vuejs.org/guide/getting-started.html#global-installation)
Pipe `stdout` and `stderr` through [`strip-ansi-control-characters`](https://www.npmjs.com/package/strip-ansi-control-characters) (I wrote that 😉) to remove those pesky screen clearing characters.
🦁
> Prevent screen clearing once and for all

- src/tests/build.test.js
- src/tests/context-site/netlify.toml
- src/tests/failure-site/netlify.toml
- src/tests/subdir-site/netlify.toml
- src/tests/success-site/netlify.toml
- src/tests/wrong-config-site/netlify.toml
Fixes #835.
This adds tests for the `netlify build` command.
This only tests the integration between the Netlify CLI and `@netlify/build` and `@netlify/config`, since those already have their own tests in their respective repositories. 
The binary command is run (as opposed to importing the command programmatically) so that the tests are as close as possible to how users experience running this command.
Note: CI tests are failing due to other tests unrelated to this PR.
> Add tests for `netlify build`

- src/detectors/eleventy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/830
* Follow the getting [started guide for 11ty](https://www.11ty.dev/docs/getting-started/)
* Run netlify dev
Pass 11ty detector if either
* `package.json` and `.eleventy.js` files exist
* `package.json` file exists and `@11ty/eleventy` is listed as `dependency` or `devDependency`
🐔
> Fix 11ty detector

- src/commands/dev/index.js
- src/tests/dev.test.js
- src/tests/rules-proxy.test.js
- src/utils/rules-proxy.js
**- Summary**
Rules proxy needs some time before it can detect changes  t
Sometimes `chokidar` can take some time before it triggers the `add`, `change` event (which is when we parse the config files) and that results in server running without the rules applied. This is especially prominent in Windows and causes the tests to fail.
Now, we're parsing the those files on startup and then adding `onChange` event callbacks.
> Parse headers and redirect rules on startup

- src/utils/detect-server.js
**- Summary**
We should throw an error if `port` and `targetPort` options are same.
Run `netlify dev -p 3000 --targetPort 3000`
* Throw an error if specified `port` conflicts with specified `targetPort`
* Throw an error if specified `port` conflicts with `proxyPort` provided by detector
🐑
> Detect Server: Make sure "port" and 'targetPort" are not same

- src/commands/dev/index.js
**- Summary**
We broke this perviously by not returning `proxyPortUsed` from `startProxy`.
Fixes: https://github.com/netlify/cli/issues/797
Fixes: https://community.netlify.com/t/netlify-dev-live-flag-failing-port-is-required/12543
`netlify dev --live` in your project
Use `settings.proxyPort` instead of expecting `proxyPortUsed` from `startProxy`
🐰
> Dev: Fix --live flag

- .github/workflows/main.yml
When one of the environments of the CI matrix fails, it is useful to let the others complete, so we know if the failure is related to a specific OS or Node.js version. This PR adds this.
It also applies Prettier, and removes `CI=true` from environment variables since GitHub actions just added [support for it](https://github.blog/changelog/2020-04-15-github-actions-sets-the-ci-environment-variable-to-true/).
> Add `fail-fast: false` to CI tests

- src/commands/build/index.js
- src/tests/build.test.js
`netlify build` calls the API to retrieve UI build settings, so the build behaves correctly. To do that, it requires `siteId` and `token` to be available. This PR adds validation that informs users what to do if those values are missing.
> Make sure `siteId` and `token` are defined with `netlify build`

- package-lock.json
- package.json
This upgrades `zip-it-and-ship-it` to include some updates with Prisma: https://github.com/netlify/zip-it-and-ship-it/pull/100
The `js-client` and `@netlify/build` are updated too since they depend on `zip-it-and-ship-it` as well.
> Upgrade `zip-it-and-ship-it`

- package-lock.json
- package.json
- src/commands/deploy.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/182
* "Stop auto publishing" from https://app.netlify.com for your site
* Try `netlify deploy --prod`
* Add package `lodash.isobject`
* Show a prompt asking you if you want to unlock deployments for your site
🐼
> Allow users to unlock deployments while deploying

- src/commands/functions/invoke.js
- tests/dev.test.js
**- Summary**
Fixes: #877 
* Run `netlify functions:invoke name` in your project 
* Don't use `detectServer` because it's not useful in this situation anymore
* Add a flag for `port` to connect to right `netlify dev` server
🦁
> functions:invoke: Fix config problems by adding port flag

- docs/commands/functions.md
As written, gives an empty object as the body of the received event. With the fix, will produce the desired result.
**- Summary**
Was trying to test lambda function invocations locally, would not work with documentation as written.
create a simple `testFunction`, expect a certain <payload>, attempt to pass that payload with `netlify functions:invoke testFunction --payload <payload>`
Update documentation for CLI function invocation with --payload flag
🐼
> Update syntax for functions:invoke --payload

- src/commands/dev/index.js
- src/function-builder-detectors/netlify-lambda.js
- src/utils/detect-functions-builder.js
- src/utils/detect-server.js
- src/utils/env.js
- src/utils/env.test.js
- tests/dummy-site/.env
- tests/dummy-site/.env.development
**- Summary**
Fixes: https://github.com/netlify/cli/issues/876
* Tests added
* Add function `getEnvFile` to return `.env.development` or fallback to `.env` file
* Add tests for `getEnvFile`
* Pass project directory to detectors
🦆
> Add support for .env.development file

- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/function-builder-detectors/netlify-lambda.js
- src/utils/env.js
- src/utils/env.test.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/883
* Run `netlify dev:exec`
* Change `getEnvFile` to `getEnvSettings`
* Use `envSettings.{vars,file}` returned from `getEnvSettings` instead of parsing everywhere
🦄
> Add .env files support fo `netlify dev:exec` 

- src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/896
We were proxying the wrong port  🤦🏽‍♂️
* Change the port live proxy connects to from `settings.proxyPort` (port of the application framework server) to `settings.port` (port of `netlify dev` server) 
🐿
> Fix netlify dev --live

- src/commands/dev/index.js
**- Summary**
Related to https://github.com/netlify/cli/issues/898
* Update the log when can't connect to `targetPort`
* Make sure to exit correctly
🦖
> Improve error when cant connect to targetPort

- src/commands/dev/index.js
- src/detectors/README.md
- src/detectors/angular.js
- src/detectors/brunch.js
- src/detectors/create-react-app.js
- src/detectors/docusaurus.js
- src/detectors/eleventy.js
- src/detectors/ember.js
- src/detectors/expo.js
- src/detectors/gatsby.js
- src/detectors/gridsome.js
- src/detectors/hexo.js
- src/detectors/hugo.js
- src/detectors/jekyll.js
- src/detectors/middleman.js
- src/detectors/next.js
- src/detectors/nuxt.js
- src/detectors/parcel.js
- src/detectors/phenomic.js
- src/detectors/quasar-v0.17.js
- src/detectors/quasar.js
- src/detectors/react-static.js
- src/detectors/sapper.js
- src/detectors/stencil.js
- src/detectors/svelte.js
- src/detectors/vue.js
- src/detectors/vuepress.js
- src/utils/detect-server.js
- src/utils/detect-server.test.js
**- Summary**
This doesn't affect anything on the outside or any functionality. This is just to reduce confusion around different port names.
https://github.com/netlify/cli/issues/882
https://github.com/netlify/cli/issues/677
https://github.com/netlify/cli/issues/658
https://github.com/netlify/cli/pull/669
No changes to functionality
* Rename `proxyPort` to `frameworkPort` internally
🦆
> Internal only: Rename proxyPort to frameworkPort

- src/commands/dev/index.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/903
`netlify dev` in Gatsby project should not add any `....` to terminal
Add `output: 'silent'` option to `waitPort` calls
🐝
> Dev: Dont add dots when waiting for port

- .github/workflows/main.yml
- src/utils/gh-auth.js
- src/utils/init/config-github.js
- tests/addons.test.js
**- Summary**
Octokit now uses named imports and prints a deprecation notice if you use the default import 
```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
```
this change swaps out to the named import to remove this deprecation notice
> fix: use named Octokit import

- package-lock.json
- package.json
This upgrades `@netlify/build`, `@netlify/cli`, `@netlify/zip-it-and-ship-it` and the `js-client` to their latest versions.
This includes the breaking changes outlined in https://github.com/netlify/build/issues/1068, but those are good with `@netlify/cli`.
> Upgrade Netlify Build

- docs/commands/build.md
CI tests are currently failing due to Prettier not having been run in a separate PR. This fixes this.
> Fix CI tests failing

- src/commands/deploy.js
**- Summary**
This is to reduce confusion about `--branch` flag behavior.
Fixes: https://github.com/netlify/cli/issues/275
Add `--alias` flag to `netlify deploy` command.
🤦🏽‍♂️
> Deploy: Rename --branch to --alias

- src/utils/detect-server.js
- src/utils/detect-server.test.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/932
Tests added
* Have `command` in `netlify.toml` `[dev]` section
* Run `netlify dev --dir something`
* Check for `command` and `targetPort` options in `flags` rather than `[dev]` config when `dir` flag is set
* Make sure `command` is not set from config when `dir` flag is set
🦥
> Fix checks for "command" and "dir" combination

- src/commands/addons/delete.js
- src/commands/addons/list.js
- src/commands/api.js
- src/commands/build/index.js
- src/commands/deploy.js
- src/commands/dev/index.js
- src/commands/functions/build.js
- src/commands/functions/create.js
- src/commands/functions/invoke.js
- src/commands/functions/list.js
- src/commands/init.js
- src/commands/link.js
- src/commands/login.js
- src/commands/open/index.js
- src/commands/sites/config.js
- src/commands/sites/create.js
- src/commands/sites/delete.js
- src/commands/sites/list.js
- src/commands/status/index.js
- src/utils/command.js
- tests/build.test.js
This adds a `--debug` CLI flag to all commands.
When enabled, this prints additional information in `@netlify/config` showing the configuration before and after resolution.
It also prints additional information inside `@netlify/build` when using `netlify build`.
This could prove very useful when debugging bug reports that might be configuration-related.
Instead of adding the flag to each command, this PR adds it to the base command, since all commands use `@netlify/config`.
This PR includes a test for this new flag.
> Add `--debug` CLI flag

- src/commands/dev/index.js
- src/utils/create-stream-promise.js
- src/utils/serve-functions.js
- tests/dev.test.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/695
Test added
Record the request body and replay on time we try original URL or alternative URL's
🐶
> Fix requests hanging when function not found

- src/commands/dev/index.js
- tests/dev.test.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/972
Test added
Check Content-Type headers to see if POST requests are form submissions before handing them over to be processed as form submissions
🐶
> Dev: Fix false positives for Netlify Forms

- package-lock.json
- package.json
- src/commands/dev/index.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/904
You can follow my comment [here](https://github.com/netlify/cli/issues/904#issuecomment-652421285) to reproduce
[chokidar](https://github.com/paulmillr/chokidar) sends an initial `add` event for each existing file in the watched directory.
In the case of the bug, that event was fired for each file under `functions/node_modules` spawning multiple build commands.
You can ignore those initial events by waiting for the `ready` event or passing `ignoreInitial`:
https://github.com/paulmillr/chokidar#path-filtering
Also debounced the build command to make sure only one instance of it executes at a single point in time.
🐈
> fix: wait for chokidar ready event before listening to function builder src directory

- src/utils/serve-functions.js
This might not be an exhaustive list of all the mimetypes we'll have to support, but it solves the problem I was running into (uploading images through a Netlify function locally using `netlify dev`)
**- Summary**
I've been trying to use a Netlify function as an image/file uploading proxy and running into problems, both locally using `netlify dev` and in production.
I managed to fix the problems in production after looking at [this thread](https://community.netlify.com/t/baffled-by-binary-event-body-in-lambda-function/17395). I believe this is something you're currently looking into.
Going over the `netlify-cli` code, I saw there was no way of changing the default 'utf8' decoding format for the request `body` Buffer, which won't work for binary data. As I say above, I'm unsure if there …
> Use base64 encoding for binary types

- src/utils/serve-functions.js
- tests/dev.test.js
- tests/dummy-site/functions/no-body.js
**- Summary**
This PR fixes #977 that occurred because [this line](https://github.com/netlify/cli/blob/16fc9342d5134b7add18a65923110810109d6375/src/utils/serve-functions.js#L55) only detects when the request body is a string type. It should process normally both for when it has no body(undefined) and the body is not string type. [Refer to this case.](https://community.netlify.com/t/i-got-function-invocation-failed-incorrect-function-response-body-error-from-lambda-function/17772)
The reason I've edited this code is that I found this [code is actually from ZISI](https://github.com/netlify/netlify-dev-plugin/commit/27da1184d35f2ecc2f4c8af9fa3c74ea86009baf) and originally created in [Netlify lambda repo](https://github.com/netlify/netlify-lambda/commit/a528e439cc3fec6973d6b0eb …
> fixes #977 change request body validation

- src/commands/dev/index.js
- src/utils/serve-functions.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/627 (also https://github.com/netlify/cli/issues/627#issuecomment-657331256)  since https://github.com/netlify/netlify-lambda/pull/239 is released 
See example success logs:
See example failure logs:
1. Provide feedback when build is done.
2. Provide feedback when build fails. 
🐩
> fix(function-builder): report build errors

- src/utils/command.js
**- Summary**
Fixes: https://github.com/netlify/cli/issues/959
Use `siteId` or `site` flags as `siteId` as parameters to `resolveConfig`
🐠
> Pass site or siteId to @netlify/config

- package-lock.json
- package.json
This is a re-do of #836, which was accidentally reverted as part of #902 ([here](https://github.com/netlify/cli/pull/902/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R158)).
On top of what #836 mentions, `dependency-cruiser` also makes `npm install` fail on Node 14 (due to incompatible `engines.node`).
> Remove `dependency-cruiser`

- src/detectors/README.md
- src/detectors/angular.js
- src/detectors/brunch.js
- src/detectors/create-react-app.js
- src/detectors/docusaurus.js
- src/detectors/eleventy.js
- src/detectors/ember.js
- src/detectors/expo.js
- src/detectors/gatsby.js
- src/detectors/gridsome.js
- src/detectors/hexo.js
- src/detectors/hugo.js
- src/detectors/jekyll.js
- src/detectors/middleman.js
- src/detectors/next.js
- src/detectors/nuxt.js
- src/detectors/parcel.js
- src/detectors/phenomic.js
- src/detectors/quasar-v0.17.js
- src/detectors/quasar.js
- src/detectors/react-static.js
- src/detectors/sapper.js
- src/detectors/stencil.js
- src/detectors/svelte.js
- src/detectors/vue.js
- src/detectors/vuepress.js
- src/utils/detect-server.js
Netlify Dev `settings.port` is always `8888` (before `getPort()` is called to see if the port is available), no matter how Netlify Dev was called, and no matter which detector was picked.
This PR simplifies the logic by making it a single constant instead.
> Simplify `port` in Netlify Dev

- src/commands/dev/index.js
- src/detectors/README.md
- src/detectors/angular.js
- src/detectors/brunch.js
- src/detectors/create-react-app.js
- src/detectors/docusaurus.js
- src/detectors/eleventy.js
- src/detectors/ember.js
- src/detectors/expo.js
- src/detectors/gatsby.js
- src/detectors/gridsome.js
- src/detectors/hexo.js
- src/detectors/hugo.js
- src/detectors/jekyll.js
- src/detectors/middleman.js
- src/detectors/next.js
- src/detectors/nuxt.js
- src/detectors/parcel.js
- src/detectors/phenomic.js
- src/detectors/quasar-v0.17.js
- src/detectors/quasar.js
- src/detectors/react-static.js
- src/detectors/sapper.js
- src/detectors/stencil.js
- src/detectors/svelte.js
- src/detectors/vue.js
- src/detectors/vuepress.js
- src/utils/detect-server.js
- src/utils/detect-server.test.js
Only 3 detectors set some `env`. This PR simplifies the code by not requiring that `env` object to include `process.env`. `process.env` is passed later on instead (when the server is spawned). The behavior should not change, this just simplifies code.
> Simplify Netlify Dev detectors `env`

- src/utils/detect-server.js
This is a small code simplification of some code in Netlify Dev.
> Simplify some code in Netlify Dev

- src/utils/detect-server.js
This PR simplifies some code that are calling `console.log()` through more levels of indirection than needed.
> Simplify `console.log()` statement

- src/utils/detect-server.js
This removes an `if` branch whose condition can never be `true`.
In that function, `optionalValue` can never be `undefined`. The function is called only by two other functions.
> Removes unreachable code 

- src/utils/detect-server.js
This improves how `devConfig.command` is handled, by simplifying the code a little.
It also handles the case where arguments are separated by multiple spaces instead of one, by improving the RegExp.
Note that splitting by whitespace is not great, since arguments might be quoted strings with spaces in them. The command itself might have a space: this is especially common on Windows due to `C:\Program Files\`. We might want to improve that parsing later.
> Improve Netlify Dev command parsing

- src/utils/detect-server.js
This simplifies Netlify Dev `assignLoudly()` function a little further.
> Simplify Netlify Dev `assignLoudly`

- src/utils/detect-server.js
When `dev.command` is defined, we override the detected framework's `command` and `args`. The way this is currently done can be simplified since the branch checks that `devConfig.command` is defined. The `assignLoudly()` function assigns a default value when `devConfig.command` is not defined, but that can never happen in that branch, so can be removed. Furthermore, the `console.log()` message is printed in the wrong opposite condition.
> Simplify default `devConfig.command` assignment

- src/detectors/angular.js
- src/detectors/create-react-app.js
- src/detectors/ember.js
- src/detectors/expo.js
- src/detectors/gatsby.js
- src/detectors/hexo.js
- src/detectors/next.js
- src/detectors/nuxt.js
- src/detectors/parcel.js
- src/detectors/quasar-v0.17.js
- src/detectors/quasar.js
- src/detectors/react-static.js
- src/detectors/sapper.js
- src/detectors/svelte.js
- src/detectors/vue.js
- src/detectors/vuepress.js
When we fail to detect the build command with Netlify Dev, many detectors are adding a default command.
The way this is currently done does not work. This is because the `possibleArgsArr` are the arguments passed to `command` which is `npm run` or `yarn`. For example, if `possibleArgsArr` is `['gatsby', 'develop']`, then `npm run gatsby develop` will be run instead of simply `gatsby develop`. 
A follow-up PR will fix how we assign a default build command. This PR just removes the code that is currently failing.
> Remove detectors code that is not currently working

- src/detectors/utils/jsdetect.js
This simplifies some common logic used by detectors a little more.
This should not change the logic, except for one small bug that this is fixing: we have some logic that prevents triggering a `package.json` `scripts` whose command includes `netlify dev` (to prevent infinite recursion). However, it was still possible to have `netlify dev` triggered by Netlify Dev when the script included one of the frameworks' `preferredCommand`. For example:
```json
"scripts": {
"build": "netlify dev && gatsby develop"
}
```
> Simplify detectors a little more

- src/commands/dev/index.js
- tests/command.dev.test.js
**- Summary**
`netlify dev` was failing for me consistently with the following error message:
```
◈ Netlify Dev ◈
◈ No app server detected and no "command" specified
◈ Using current working directory
◈ Unable to determine public folder to serve files from
◈ Setup a netlify.toml file with a [dev] section to specify your dev server settings.
◈ See docs at: https://cli.netlify.com/netlify-dev#project-detection
◈ Running static server from "mybinder.term"
◈ Server listening to 3999
┌─────────────────────────────────────────────────┐
│                                                 │
│   ◈ Server now ready on http://localhost:8888   │
│                                                 │
└─────────────────────────────────────────────────┘
TypeError: Cannot read property 'endsWith' of undefined …
```
> Handle contentType not being set in netlify dev

- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/commands/functions/create.js
- src/utils/dev.js
This extracts some code into functions (with descriptive names) and removes a redundant argument to `addEnvVariables`
> refactor: clean up addEnvVariables function

- package.json
**- Summary**
Trying to install the cli with [Volta](https://volta.sh) using `volta install netlify-cli` failed with `error: Could not parse version ">=v8.17.0"`. Removing the `v` from the version string should fix that.
I could install version `2.58.0` without any problems and when comparing diff of 2.59.0 I noticed the node engine change that added the `v`. 
Remove unnecessary `v` from node engine version string.
> Remove v from node engine version string

- src/commands/dev/index.js
- tests/command.dev.test.js
Hi Netlify :heart:,
I'm submitting this PR as suggested by @erezrokah in order to fix issue #1017.
**- Summary**
When you have a folder and a file with the same name (e.g., foo.html and foo/), Netlify will serve the contents of foo.html.
Until now, netlify dev was inconsistent with that behavior and returned a 403 Forbidden error in this scenario (because directory listings are forbidden).
This PR makes netlify dev behave consistent with Netlify by serving the .html (or .htm) file instead of returning 403 Forbidden.
Fixes: #1017 
I first added a test to `tests/command.dev.test.js`. I ran the test and confirmed that it failed. Then I implemented the fix. I reran the test and the test passed.
I ran `npm run test` and everything came back green.
**- Description for the …
> Fix: Return .html file when file and folder share name

- src/commands/dev/index.js
- tests/command.dev.test.js
**- Summary**
In Netlify, you can set a custom 404 page by putting a 404.html file inside the publish folder (e.g., public or whatever is specified in netlify.toml).
Until now, this custom 404 page was not picked up by netlify dev. For it to work in netlify dev, the custom 404.html file had to be in the root folder.
This PR makes the behavior of netlify dev consistent with Netlify in production by using the custom 404.html page in the publish folder.
Fixes: https://github.com/netlify/cli/issues/1158
I first added a test to tests/command.dev.test.js. I ran the test and confirmed that it failed. Then I implemented the fix. I reran the test and the test passed.
I ran npm run test and everything came back green.
Fix: Use 404.html page in …
> Fix: Use 404.html page in publish folder

- renovate.json5
Ignore some more packages since we can't update until we drop node 8.
I already updated those to the latest version supporting node 8.
> chore(deps): ignore some more packages due to node 8 support

- .github/workflows/main.yml
Our current testing matrix uses 12 machines (4 node version * 3 OS).
This is redundant.
We should test on:
1. Node 8 since we still support it.
2. Node 12 since it LTS and default in Netlify.
3. Node 14 since it is the current version.
> ci: update node versions to 8,12,14

- .github/workflows/main.yml
Found out the default limit is 6 hours(!):
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
This PR changes it to 30 minutes
> ci: change job time limit to 30 minutes

- src/commands/dev/index.js
- src/utils/detect-server.js
- tests/utils/devServer.js
This is an attempt to make the tests more stable.
The static server port is currently hard coded (that port is used when no framework is detected and we just server files statically from the publish folder).
Added a hidden flag to be used in tests for the sake of randomising the port.
> test: set random static server port for tests

- scripts/generateCommandData.js
- site/package-lock.json
- site/package.json
The `staticServerPort` flag added to the `dev` command [here](https://github.com/netlify/cli/pull/1188) is shown in the docs.
This PR fixes the code that generates the docs to remove hidden flags.
> fix(docs): hide hidden command flags from docs

- README.md
- docs/README.md
- docs/commands/env.md
- docs/commands/index.md
- site/src/_app.js
- src/commands/env/get.js
- src/commands/env/import.js
- src/commands/env/index.js
- src/commands/env/list.js
- src/commands/env/set.js
- src/commands/env/unset.js
- tests/command.addons.test.js
- tests/command.env.test.js
- tests/utils/callCli.js
- tests/utils/createLiveTestSite.js
**- Summary**
Closes #1011
This PR introduces commands for managing environment variables from the CLI. It uses the Netlify API to set environment variables for the current site in the UI. 
| Command | Description |
| -------------- | --------------- |
| `netlify env:list` | Shows a table of env variables including those set in `netlify.toml`.  |
| `netlify env:get NAME` | Prints the value of a specified variable including those set in `netlify.toml`. |
| `netlify env:set NAME VALUE` | Sets an environment variable in the UI. |
| `netlify env:set NAME` | Removes an environment variable in the UI. |
| `netlify env:import FILE_NAME` | Imports environment variables from `.env` files and sets them in the UI. |
| `netlify env:import --replaceExisting FILE_NAME` | Imports environment variables …
> feat(env): add command to list/get/set/import environment variables 

- src/commands/env/import.js
@Pyrax our default branch CI started failing after merging https://github.com/netlify/cli/pull/1162
https://github.com/netlify/cli/runs/1061075168?check_suite_focus=true#step:5:251
My guess it that one of the dependencies update broke the `error` command on node 8 (tried it locally and it is indeed broken).
This PR should fix it.
> fix(command-env): handle non existing import file on node 8

- src/commands/dev/index.js
- src/lib/exec-fetcher.js
- src/lib/exec-fetcher.test.js
- src/lib/settings.js
- src/utils/global-config.js
- src/utils/live-tunnel.js
- src/utils/proxy.js
- src/utils/serve-functions.js
- src/utils/traffic-mesh.js
- tests/command.dev.test.js
- tests/utils/devServer.js
Fixes https://github.com/netlify/traffic-mesh/issues/806
This is a big PR since I did some refactoring to the dev command in the process since it was very hard to follow.
The commits are small though.
I'll add comments to clarify the changes.
This PR consists of 3 main changes:
1. Extract common logic to download binary clients (this was used in the tunnel client and now shared with traffic mesh agent).
2. Extract the different dev command responsibilities (starting functions server, framework server, Netlify dev proxy, tunnel client, etc) into separate functions/files.
3. Traffic Mesh flag implementation which was quite small.
> When enabling traffic mesh some test are still failing - looking into those.
> Feat: add traffic mesh proxy flag

- src/commands/dev/index.js
- src/utils/detect-server.js
- src/utils/traffic-mesh.js
Adds support for functions redirects when using `--trafficMesh`.
Pending a new release of https://github.com/netlify/traffic-mesh-agent
> fix(command-dev): pass functions server uri to traffic mesh

- src/detectors/docusaurus.js
**- Summary**
Docusaurus automatically launches a browser, but Netlify Dev does not prevent it, leading to confusing scenarios where you'll have the wrong server open in your browser and Netlify options like redirects won't work. This also brings the functionality in line with similar tools like create-react-app.
I ran `bin/run` and Docusaurus did not launch the browser as I expected.
Disable Docusaurus' `BROWSER` environment variable.
> fix(command-dev): prevent Docusaurus from launching browser

- CONTRIBUTING.md
- package-lock.json
- package.json
Follow up on https://github.com/netlify/cli/pull/1213
Related to https://github.com/netlify/cli/issues/756
Switch to using `standard-version` to auto increment versions.
Kept the old way of generating the changelog for now.
> chore: use standard-version to increment versions

- site/scripts/docs.js
- site/scripts/generateCommandData.js
Follow up on https://github.com/netlify/cli/pull/1216 which broke docs generation due to moving the directory of the docs scripts.
Fixes path resolving based on `__dirname`
> docs: fix path to docs files directory

- package.json
Another follow up to https://github.com/netlify/cli/pull/1216
Fixes a reference to the docs script in the root `package.json`
> chore: fix docs script in root folder

- docs/commands/api.md
- docs/commands/build.md
- docs/commands/deploy.md
- docs/commands/dev.md
- docs/commands/functions.md
- docs/commands/init.md
- docs/commands/link.md
- docs/commands/sites.md
- site/package-lock.json
- site/package.json
- site/scripts/generateCommandData.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1220
See deploy preview of docs site
Our docs were generated based on the object returned from `flags.string`:
https://github.com/netlify/cli/blob/aef62e9e6e8a035936c692e5a1382b8890ae9f78/site/scripts/docs.js#L150
https://github.com/netlify/cli/blob/aef62e9e6e8a035936c692e5a1382b8890ae9f78/src/commands/build/index.js#L53
Which returns `type: option`.
This PR uses a more common `string` type.
🐩
> docs: use 'string' instead of 'option' in docs

- package.json
As a result of https://github.com/netlify/cli/pull/1214 the changelog was generated with the previous version and not the new one (see https://github.com/netlify/cli/commit/b8de9cc8b8de900795ef0fc7c0dde4daad149126#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR10)
This change fixes that issue.
> chore: fix release script

- src/detectors/docusaurus.js
**- Summary**
This PR closes #1199. With Docusaurus V2, the dependencies and commands have changed. In order to support the new version I've updated the dependency check to look for either the V1 dependency or the V2 dependency. Depending on whether the V1 or V2 dependency is installed, the correct command will be added to the `scanScripts` call.
```sh
npx @docusaurus/init@next init my-website classic
cd my-website
netlify dev
```
With these changes, running `netlify dev` from within a Docusaurus V2 website will work as expected.
`feat(command-dev): Support Docusaurus V2`
> feat(command-dev): Support Docusaurus V2

- README.md
**- Summary**
Replacing outdated david-dm's badge with Snyk's for security insights.
N/A
docs(readme): use Snyk badge for deps security
> README: use Snyk badge for deps security

- src/commands/deploy.js
**- Summary**
The PR refactors the `deploy` command code by extracting most of the logic into functions.
Some logic mutates objects so I didn't extract it yet since I wanted the functions to be pure.
Tested manually the different deploy flags, and actually exposed old bugs in the process (which I fixed).
Should not change behaviour
🐼 
Related to https://github.com/netlify/cli/issues/1236 and https://github.com/netlify/cli/issues/1227 - I initially started looking into those issues and found the code very hard to follow.
> refactor: extract deploy command logic into separate functions

- src/utils/proxy.js
- tests/command.dev.test.js
**- Summary**
There is a [bug in the next-on-netlify](https://github.com/netlify/next-on-netlify/issues/41) package being caused by this. Requests are being routed to a catch-all page, when they shouldn't be. This fixes that!
(see linked issue above)
Fix: Request URL for static pathnames decoded properly
> Fix invalid static parameters

- package.json
- src/commands/deploy.js
- src/lib/api.js
- src/lib/fs.js
- src/lib/spinner.js
- src/utils/command.js
- src/utils/edge-handlers.js
- src/utils/env.js
- src/utils/gitignore.js
- tests/command.addons.test.js
- tests/command.deploy.test.js
- tests/command.env.test.js
- tests/utils/callCli.js
- tests/utils/createLiveTestSite.js
- tests/utils/siteBuilder.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1236
This is a draft PR not to be reviewed yet (needs some cleanup and tests).
Opening for visibility.
Depends on https://github.com/netlify/js-client/pull/155 and branched out from https://github.com/netlify/cli/pull/1240
The flow is:
1. Create the deploy (used to be in `js-client`)
2. Upload Edge Handlers if  `.netlify/edge-handlers` exists or passed as an argument via `--edgeHandlers`
3. Run `deploy` from `js-client` with the created `deployId`
Will add comments after https://github.com/netlify/cli/pull/1240 is merged and I do a rebase.
Support deploying Edge Handlers as a part of the deploy command.
🐻
> Feat: edge handlers deploy

- docs/commands/deploy.md
- src/commands/build/index.js
- src/commands/deploy.js
- src/lib/build.js
- tests/command.deploy.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/179
Adds a `--build` flag to run the build command before deploying.
Support running the build command before deploying
😸
> Feat: run build command when deploying

- src/commands/deploy.js
- tests/command.deploy.test.js
- tests/utils/siteBuilder.js
**- Summary**
Related to https://github.com/netlify/js-client/issues/157 and https://github.com/netlify/cli/issues/1227.
Fixes https://github.com/netlify/cli/issues/1225#issuecomment-696957186
The CLI deploy command relies on `js-client` default filter to skip some files when deploying.
This is done here:
https://github.com/netlify/js-client/blob/55650048fc7fe6288816c1dc172b27024cbd1586/src/deploy/util.js#L8 
and trying to emulate the code here:
https://github.com/netlify/open-api/blob/e72e2eb2d7eedf02bccc5916fc0330022f7f823b/go/porcelain/deploy.go#L692
This PR fixes a few discrepancies with our buildbot:
1. Allows publishing a hidden directory (e.g. `.public`) - fixes part of https://github.com/netlify/cli/issues/1227.
2. Allows deploying `node_modules` when inside a publish folder. …
> fix(command-deploy): align file filtering with buildbot

- src/commands/dev/index.js
- src/utils/traffic-mesh.js
- tests/command.dev.test.js
**- Summary**
This PR changes the directory we're passing to the traffic mesh agent to be the publish directory.
This is done to support sourcing `_redirects` and `_headers` from the publish directory and the project directory (only the latter was supported).
Added a test for this, which is still disabled when running with `--trafficMesh` since there are still other bugs to be fixed.
Pass publish directory to traffic mesh agent instead of project directory.
🐶
> fix(command-dev): pass publish directory to traffic mesh agent

- package-lock.json
- package.json
- src/commands/deploy.js
- src/lib/api.js
- src/utils/edge-handlers.js
- tests/command.deploy.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1227
Dependant on https://github.com/netlify/js-client/pull/161
Handles the error thrown by `js-client` when there are no files to deploy (cancels the created deploy).
Will push a test once is https://github.com/netlify/js-client/pull/161 merged and published
Handle deploy error when there are no files to deploy
🐳
> fix(command-deploy): handle deploy error when there are no files to deploy

- .eslintrc.json
- site/.eslintrc.json
- src/commands/functions/create.js
- src/hooks/analytics.js
- src/utils/command.js
- src/utils/detect-server.js
- src/utils/gh-auth.js
- src/utils/live-tunnel.js
- src/utils/parse-raw-flags.test.js
- src/utils/read-repo-url.js
- src/utils/serve-functions.js
**- Summary**
This PR removes some redundant await keywords from our code base and adds a lint rule for it.
Haven't done it for our function templates yet, since removing `await` from some of them will make them not return a promise. I'll need to verify that pattern is supported first.
N/A
Add a lint rule to track redundant `await` keywords.
🐦
> chore: remove redundant await keywords

- tests/command.deploy.test.js
**- Summary**
This PR enables the deploy edge handlers test on windows, since it is now supported
> test(command-deploy): enable edge-handlers plugin test on windows

- package-lock.json
- package.json
- src/commands/dev/exec.js
- tests/command.dev.exec.test.js
**- Summary**
Follow up on https://github.com/netlify/cli/pull/1305 - don't mutate `process.env` when we can pass `env`
to `execa`
Don't mutate `process.env` in `commands/dev/exec.js`
🐈
> refactor(command-dev-exec): don't mutate process.env

- src/commands/addons/auth.js
- src/commands/deploy.js
- src/commands/dev/index.js
- src/commands/open/admin.js
- src/commands/open/site.js
- src/utils/command.js
- src/utils/gh-auth.js
- src/utils/init/config-github.js
- src/utils/open-browser.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1212, follow up on https://github.com/netlify/cli/pull/1144
More context - not only we had duplicate code around this, we were using 2 different dependencies to do so. I removed the usage of https://github.com/oclif/cli-ux/blob/515570bbeb40bcd28698b6b7af53cc9bfdf86279/src/open.ts#L12 as it seems like an out of date version of https://github.com/sindresorhus/open/blob/f3748e4f5a04a41e27034aff1eb08e8b86d01c1c/index.js#L34
Tested manually the different commands related to opening browsers (`login,dev,deploy,init,open,sites:create --with-ci`).
Remove open browser code duplication
🐕
> refactor: remove open-browser code duplication

- src/commands/dev/trace.js
- src/utils/traffic-mesh.js
- tests/command.dev.trace.js
This new subcommand allows checking whether a request will match
a remap rule directly from the cli.
It requires the new traffic mesh agent.
Closes https://github.com/netlify/product/issues/584
> feat(dev): add trace subcommand to simulate redirects

- renovate.json5
Latest major version for this package requires node 10
> chore: ignore major updates for update-notifier

- src/lib/build.js
- tests/command.deploy.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1332
pass `buffer: true` to Netlify build if `--json` or `--silent`
> fix(command-deploy): pass buffer: true to build if --json or --silent

- src/commands/functions/create.js
- src/utils/addons.js
Related to https://github.com/netlify/cli/issues/310 and https://github.com/netlify/cli/issues/1331
Wanted to fix https://github.com/netlify/cli/issues/1331, but couldn't do it since the addons code doesn't allow getting the env variables easily at the moment:
I going to do some refactoring first so we can have https://github.com/netlify/cli/blob/b88cf6db2028741b93ce271cfaca934c4f812a0d/src/utils/dev.js#L25 return addons envs instead of mutating `process.env`
I removed a bunch of outdated comments from `utils/addons.js` and did some code cleanup.
Note that part of that function is duplicated from:
https://github.com/netlify/cli/blob/b88cf6db2028741b93ce271cfaca934c4f812a0d/src/commands/addons/create.js#L155
I follow up in another PR. 
Also changed some code in `functions/create.js` to use …
> refactor: cleanup createSiteAddon function

- src/commands/dev/trace.js
- src/utils/traffic-mesh.js
Otherwise the process doesn't wait to the server to be running.
> fix(dev): add missing await

- .eslintrc.json
- package-lock.json
- package.json
- site/.eslintrc.json
- src/lib/exec-fetcher.test.js
- src/lib/http-agent.test.js
- src/utils/detect-server.test.js
- src/utils/headers.test.js
Related: https://github.com/netlify/build/pull/1935
This adds [`eslint-plugin-ava`](https://github.com/avajs/eslint-plugin-ava) to lint our Ava test files.
> Lint Ava test files

- src/utils/serve-functions.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`prefer-array-find`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-array-find.md).
> Prefer `Array.find()` over `Array.filter()`

- src/lib/http-agent.js
- tests/command.deploy.test.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`prefer-number-properties`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-number-properties.md).
> Use `Number.parseInt()` instead of `parseInt()`

- src/utils/addons/compare.js
- src/utils/gitignore.js
- src/utils/proxy.js
- src/utils/rules-proxy.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`prefer-spread`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-spread.md).
> Prefer `[...array]` over `Array.from(array)`

- src/functions-templates/js/oauth-passport/oauth-passport.js
This fixes a linting error from `eslint-plugin-unicorn`.
This PR simplifies a callback which is unnecessary.
> Small code simplification

- src/utils/detect-server.js
- src/utils/dev.js
- src/utils/proxy.js
- src/utils/serve-functions.js
This fixes the linting errors from `eslint-plugin-unicorn` related to template strings.
> Use template strings

- src/utils/serve-functions.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`consistent-function-scoping`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/consistent-function-scoping.md).
This function can be safely moved to the top-level scope.
> Move a function to the top-level scope

- src/lib/http-agent.js
- src/utils/command.js
- src/utils/headers.js
- src/utils/proxy.js
- tests/command.deploy.test.js
- tests/utils/create-live-test-site.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`prefer-string-slice`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-string-slice.md).
> Prefer `String.slice()`

- src/lib/api.js
- src/lib/http-agent.js
- tests/command.dev.trace.test.js
- tests/utils/dev-server.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`no-useless-undefined`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-useless-undefined.md).
> Avoid unnecessary `undefined`

- src/commands/functions/create.js
- src/commands/sites/create.js
- src/utils/proxy.js
- tests/utils/create-live-test-site.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`better-regex`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/better-regex.md).
> Lint RegExps

- renovate.json5
Ignores major updates to `del` and `dot-prop` due to Node 8 compatibility.
> chore(deps): ignore major updates for `del` and `dot-prop`

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/lib/exec-fetcher.js
- src/utils/traffic-mesh.js
- tests/command.dev.trace.test.js
This PR reintroduces `netlify dev:trace` command tests with some improvements:
1. Uses the latest version of `gh-release-fetch` that allows passing fetch options. We use it to pass an auth token that allows for much higher rate limits.
2. Pre-installs the traffic mesh agent so tests can run in parallel.
> test(command-dev-trace): re-enable tests

- .github/workflows/main.yml
- .gitignore
- package-lock.json
- package.json
- scripts/run-on-error.js
This PR aims at improving the Netlify CLI npm scripts:
- Only run ESLint and Prettier on Node 14 in CI, as described in https://github.com/netlify/build/issues/1962 and as implemented in Netlify Build in https://github.com/netlify/build/pull/1969
- Minor updates (adding some titles) in the GitHub actions `workflow.yml` to make it more similar to [`@netlify/build`'s `workflow.yml`](https://github.com/netlify/build/blob/master/.github/workflows/workflow.yml)
- Run formatting on `git push`, as described in https://github.com/netlify/build/issues/1950
- Sort and rename npm scripts
- Distinguish between `npm test` (local machine) vs `npm test:ci`.
- Small optimization of the `nyc` arguments to avoid running it twice
- Add caching to ESLint, and few smaller CLI flags (`--format=codeframe` and …
> Improve npm scripts

- .eslintrc.js
- src/commands/dev/index.js
- src/commands/status/index.js
- src/functions-templates/js/google-analytics/google-analytics.js
- src/utils/addons/prompts.js
- src/utils/addons/render.js
- src/utils/proxy.js
- src/utils/traffic-mesh.js
- tests/utils/dev-server.js
This adds the [`array-callback-return`](https://eslint.org/docs/rules/array-callback-return) ESLint rule. 
This is a useful linting rule, and actually I think applying it in this PR might have found some bugs.
> Add `array-callback-return` ESLint rule

- .eslintrc.js
- src/utils/addons/validation.js
This adds the [`func-name-matching`](https://eslint.org/docs/rules/func-name-matching) ESLint rule.
> Add `func-name-matching` ESLint rule

- .eslintrc.js
- src/utils/init/config-manual.js
- src/utils/serve-functions.js
This adds the [`no-implicit-coercion`](https://eslint.org/docs/rules/no-implicit-coercion) ESLint rule.
This PR's diff was generated by `eslint --fix` and `prettier`.
> Add `no-implicit-coercion` ESLint rule

- .eslintrc.js
- src/commands/functions/invoke.js
- src/functions-templates/js/sanity-groq/sanity-groq.js
- src/utils/addons/compare.js
- src/utils/addons/diffs/index.js
- src/utils/command.js
- src/utils/gh-auth.js
- src/utils/headers.js
- src/utils/rules-proxy.js
- src/utils/telemetry/index.js
This adds the [`prefer-object-spread`](https://eslint.org/docs/rules/prefer-object-spread) ESLint rule.
This PR's diff was generated by `eslint --fix` + `prettier`.
> Add `prefer-object-spread` ESLint rule

- .eslintrc.js
- src/commands/deploy.js
- src/commands/env/unset.js
- src/commands/functions/create.js
- src/commands/functions/invoke.js
- src/commands/link.js
- src/commands/sites/create.js
- src/function-builder-detectors/netlify-lambda.js
- src/functions-templates/js/fauna-crud/delete.js
- src/functions-templates/js/fauna-crud/fauna-crud.js
- src/functions-templates/js/fauna-crud/read.js
- src/functions-templates/js/fauna-crud/update.js
- src/functions-templates/js/submission-created/submission-created.js
- src/functions-templates/js/url-shortener/get-route.js
- src/lib/exec-fetcher.test.js
- src/utils/command.js
- src/utils/detect-server.js
- src/utils/init/config-github.js
- src/utils/link/link-by-prompt.js
- src/utils/proxy.js
- src/utils/telemetry/index.js
- src/utils/telemetry/validation.js
- tests/command.dev.test.js
- tests/command.env.test.js
- tests/utils/create-live-test-site.js
This adds the [`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring) ESLint rule.
Two functions required more refactoring, so those changes have been done in separate PRs #1414 and #1415, and `// eslint-disable-next-line` was used instead in this PR.
> Add `prefer-destructuring` ESLint rule

- .eslintrc.js
- src/commands/functions/create.js
This adds the [`no-invalid-this`](https://eslint.org/docs/rules/no-invalid-this) ESLint rule.
A file is passing `this` around instead of using class methods, which is odd. We should either use class methods there, or pass the `context` object around. This PR chooses the second pattern for the time being, because this generates the smallest diff.
> Add `no-invalid-this` ESLint rule

- .eslintrc.js
Now that linting is only performed in Node 14, this PR removes some dead code.
> Remove some dead code related to linting

- .github/ISSUE_TEMPLATE/feature_request.md
- .prettierrc.json
- src/detectors/README.md
- src/function-builder-detectors/README.md
- src/functions-templates/js/README.md
- tests/site-cra/README.md
This uses Prettier to enforce the maximum line length inside Markdown files too, by using wrapping, without changing how the Markdown is rendered.
Note that Prettier is not run on `README.md` and other Markdown files that are automatically generated in this repository.
> Wrap Markdown

- .eslintignore
- .gitignore
- .prettierignore
- package.json
This speeds up and simplifies ESLint and Prettier by using `.gitignore` (which skips more files) instead of `.prettierignore` and `.eslintignore`.
> Speedup ESLint and Prettier

- src/lib/exec-fetcher.js
- src/utils/traffic-mesh.js
This PR fixes the `netlify dev:trace` command by pinning the traffic mesh agent to the latest known working version
> fix(command-dev-trace): pin traffic mesh agent version

- .editorconfig
- .prettierrc.json
This adds an [`.editorconfig` file](https://editorconfig.org/).
> Add `.editorconfig`

- .eslintrc.js
- src/commands/dev/index.js
This adds the [`no-multi-assign`](https://eslint.org/docs/rules/no-multi-assign) ESLint rule.
> Add `no-multi-assign` ESLint rule

- .eslintrc.js
- tests/command.dev.test.js
- tests/utils/dev-server.js
This adds the [`no-promise-executor-return`](https://eslint.org/docs/rules/no-promise-executor-return) ESLint rule.
> Add `no-promise-executor-return` ESLint rule

- .eslintrc.js
- site/src/_layout.js
- src/commands/functions/create.js
- src/commands/functions/invoke.js
- src/functions-templates/js/fauna-graphql/fauna-graphql.js
- src/functions-templates/js/fauna-graphql/sync-schema.js
- src/functions-templates/js/graphql-gateway/graphql-gateway.js
- src/functions-templates/js/hasura-event-triggered/hasura-event-triggered.js
- src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
- src/functions-templates/js/url-shortener/generate-route.js
- src/functions-templates/js/url-shortener/get-route.js
- src/utils/command.js
- src/utils/detect-server.js
- src/utils/gh-auth.js
- src/utils/init/config-github.js
- src/utils/live-tunnel.js
- src/utils/proxy.js
- src/utils/rules-proxy.js
- src/utils/serve-functions.js
- tests/command.functions.test.js
This adds the [`prefer-template`](https://eslint.org/docs/rules/prefer-template) ESLint rule.
This PR's diff was generated by `eslint --fix` + `prettier`.
> Add `prefer-template` ESLint rule

- .eslintrc.js
- src/utils/detect-functions-builder.js
- tests/utils/dev-server.js
- tests/utils/site-builder.js
This adds the [`no-await-in-loop`](https://eslint.org/docs/rules/no-await-in-loop) ESLint rule.
> Add `no-await-in-loop` ESLint rule

- .eslintrc.js
- src/commands/functions/create.js
- src/utils/proxy.js
This adds the [`default-param-last`](https://eslint.org/docs/rules/default-param-last) ESLint rule.
> Add `default-param-last` ESLint rule

- package-lock.json
- package.json
- src/utils/traffic-mesh.js
**- Summary**
To make resolution more rigid and to avoid bloating the user's PATH with internal tools, mesh-forward now wants the path to the CLI of the edge handler build plugin passed in via its CLI. In this PR we resolve the path to the CLI via `require.resolve` and then pass it on to mesh-forward.
~~Please note the version of the build plugin specified in the dependencies here **does not yet** ship with the CLI, that's why this is a draft (it would be super nice to get this released, but I don't have the permissions to do that).~~
I wonder what's the best way forward here.
Ideally both repos (mesh-forward & cli) had separate integration tests against one another, but I'm afraid right now only `cli` as a consumer of mesh-forward actually has them.
I made changes to …
> feat(command-dev-local): pass path to bundler plugin CLI to mesh forward

- .github/workflows/main.yml
- README.md
- codecov.yml
- scripts/coverage.sh
This adds Codecov for test coverage.
It's quite useful to see the test coverage of a PR by looking at the PR status. 
This disables PR comments because they can be noisy.
> Add Codecov test coverage

- renovate.json5
@ehmicky I'm hoping this will force `npm@6`:
https://github.com/renovatebot/renovate/blob/75737805c804f69f427e0f8147c463836b1af448/lib/manager/npm/post-update/npm.ts#L31
> chore(renovate): add npm constraint

- src/utils/traffic-mesh.js
This PR reverts https://github.com/netlify/cli/pull/1458 until we have a new mesh forward version ready. See
https://github.com/netlify/cli/pull/1458#discussion_r510114277
and https://github.com/netlify/cli/pull/1469
since it's blocking CLI releases as passing the bundler arg fails on version `v0.22.1`:
```
error: Found argument '--bundler' which wasn't expected, or isn't valid in this context
```
> fix: don't pass bundler path to mesh forward

- renovate.json5
Follow up on https://github.com/netlify/cli/pull/1470
See https://github.com/renovatebot/renovate/issues/7474#issuecomment-717051216 and https://github.com/renovatebot/renovate/issues/7474#issuecomment-717009199
> chore: force renovate to use npm v6

- src/utils/finders.js
**- Summary**
Per the [Build with Javascript documentation](https://docs.netlify.com/functions/build-with-javascript/), functions ought to support the following naming formats:
- my_functions/functionname.js
- my_functions/functionname/functionname.js
- my_functions/functionname/index.js
Currently, this works perfectly fine on Netlify hosted production environments, but fails when running `netlify dev` via the CLI.
For more details on how to replicate this problem, including a minimal reproduction, please see this [support thread](https://community.netlify.com/t/netlify-dev-function-returns-404-when-using-functions-functionname-index-js-syntax-instead-of-functions-functionname-js/24124/2) I created on the Community Forums.
1. I first tested some basic scenarios in a …
> fix: support index.js function name

- .eslintrc.js
- site/scripts/generate-command-data.js
- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/commands/functions/create.js
- src/commands/functions/invoke.js
- src/functions-templates/js/fauna-crud/fauna-crud.js
- src/functions-templates/js/fauna-graphql/sync-schema.js
- src/functions-templates/js/url-shortener/url-shortener.js
- src/utils/command.js
- src/utils/detect-functions-builder.js
- src/utils/detect-server.js
- src/utils/init/config-manual.js
- tests/command.dev.test.js
This adds the [`node/global-require`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/global-require.md) ESLint rule.
We probably could remove more dynamic requires (currently marked as linting exceptions in this PR), but this would lead to too much refactoring for the moment.
A few dynamic requires had comments "lazily evaluated on purpose", but I don't see any actual good purpose for doing so since those libraries do not perform any logic on `require()` and are fairly small/fast to load.
> Add `node/global-require` linting rule

- .eslintrc.js
- package-lock.json
- package.json
- src/commands/functions/invoke.js
This upgrades `@netlify/eslint-config-node`.
This takes an approach slightly different from the one commented in https://github.com/netlify/cli/pull/1472#discussion_r512653424, to decrease the amount of PRs and back-and-forth.
Instead, `@netlify/eslint-config-node` [now contains](https://github.com/netlify/eslint-config-node/commit/dd7f829536d99d2e6305f6b80e6a1156b1f00c41) all the rules we might want to enable. In Netlify Build, all those rules currently work. In the CLI, there are a few rules that require additional refactoring, so they are explicitly disabled. We can fix those one at a time. If it turns out a specific rule is to much of a problem, or we want to change rule options, we can do it directly on `@netlify/eslint-config-node`, then make a new release.
> Upgrade `@netlify/eslint-config-node`

- scripts/coverage.sh
http://codecov.io/bash is returning 502 at the moment
> ci: don't fail on codecov error

- .eslintrc.js
- src/utils/state-config.js
This adds [`eslint-plugin-fp`](https://github.com/jfmengels/eslint-plugin-fp).
At the moment, the codebase cannot enable most rules from this ESLint rule, but we can enable them one by one as we go.
> Add `eslint-plugin-fp`

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/commands/dev/trace.js
- src/utils/traffic-mesh.js
- tests/command.dev.trace.test.js
**- Summary**
This configures the CLI to load `traffic-mesh` via npm instead of via downloading it manually the first time `netlify dev` is run.
~~The package itself is quite heavy right now (40mb) because it contains the binaries for all operating systems, but we can always improve on that later by shipping a stripped package that downloads the right binaries on installation. For the MVP I wanted to avoid the additional moving parts this brings.~~
This should not change any behavior, so the existing tests should continue working.
Install `traffic-mesh` component via npm package.
> Install traffic-mesh via npm package

- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/commands/functions/create.js
- src/utils/dev.js
- src/utils/dot-env.js
- src/utils/dot-env.test.js
- src/utils/proxy.js
- tests/command.dev.exec.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1386
Related to https://github.com/netlify/cli/issues/1331
Also fixed some stuff related to addons since during my manual testing I noticed it was broken.
Fixed some tests.
I still need to think about adding new tests, as testing https://github.com/netlify/cli/issues/1386 will require creating a live site and then running `netlify dev` or `netlify dev:exec`.
Refactor environment variables handling.
> fix: don't override dot envs with site envs

- src/commands/build/index.js
- src/commands/deploy.js
- src/lib/build.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1331
Tested manually with the flow in https://github.com/nimbella/netlify-plugin-nimbella
Inject relevant env variables when running the build command.
> fix(build): pass team,site, addons env variables to build command

- src/utils/serve-functions.js
**- Summary**
Closes #1459, problem described with detail in relative issue.
There are more elegant ways to solve this, but I would delay them to later times. This is kind of a quick but solid workaround.
I also removed the colored `◈` from the response body (ANSI chars), and changed the console log message to include the same exact failure message of the response: "Function invocation failed" (was slightly different, creating confusion).
Tested as described in #1459 with a TimeoutError, and by manually causing a `new Error` in the code.
Knowing what else can cause an error would help in triggering other possible error types.
- Error 500 "Function invocation failed" message is more informative in both response body and console log (for …
> Display more informative error information in TimeoutError response body

- src/function-builder-detectors/netlify-lambda.js
- src/function-builder-detectors/netlify-lambda.test.js
- src/function-builder-detectors/tests/netlify-lambda.test.js
**- Summary**
Having a Netlify project with the following package.json doesn't work. 
```
{
"name": "project",
"private": true,
"scripts": {
"start": "netlify dev",
"build": "run-p build:**",
"build:lambda": "netlify-lambda build --config config/webpack.functions.js src/lambda/",
}
}
```
It does not find the functions folder properly, as per the logs:
```
◈ Function builder netlify-lambda detected: Running npm script build:lambda
›   Warning: ◈ This is a beta feature, please give us feedback on how to improve at https://github.com/netlify/cli/
◈ Function builder netlify-lambda building functions from directory --config
```
See test cases.
netlify-lambda build step in package.json now allows the use of command line arguments like …
> fix(command-dev): allow netlify-lambda build parameters

- tests/command.addons.test.js
- tests/command.deploy.test.js
- tests/command.env.test.js
- tests/utils/create-live-test-site.js
This test is failing for most contributors since the Edge Handlers are in preview and not enabled for most accounts.
Added a small check to only run it if the account supports it
> test: don't run edge handlers deploy if the account doesn't support it

- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/commands/functions/create.js
- src/lib/account.js
- src/lib/build.js
- src/utils/command.js
- src/utils/dev.js
- src/utils/serve-functions.js
- tests/command.deploy.test.js
- tests/command.dev.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1553
Also related to https://github.com/netlify/cli/issues/958
Tested locally with an account that supports background functions, and another one that doesn't
See example warning:
Warn when background functions are not supported when `netlify dev` is invoked
> fix(command-dev): warn when background functions are not supported

- docs/commands/sites.md
- site/scripts/docs.js
- src/commands/sites/delete.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1555
Looks like this was an attempt to improve the docs of the `delete` command.
Not sure why we need a different doc format for it.
We could improve single argument commands by appending the argument to the command in the docs, but that should be done for all commands (and in a separate PR).
Run `netlify sites:delete --help`
Don't print a duplicate `netlify` when running `netlify sites:delete --help`
🐱
> fix(command:sites:delete): don't print duplicate netlify in help

- src/commands/deploy.js
- src/lib/log.js
- src/utils/serve-functions.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1569
See error message:
Print relevant error message when failing to deploy a background function to an account that doesn't support it
🐼
> fix(command-deploy): print relevant log error when background functions are not supported

- docs/netlify-dev.md
Fixes the docs to match https://github.com/netlify/cli/blame/master/docs/netlify-dev.md#L151, https://github.com/netlify/cli/blob/8efe94e5fb38976c49f0cf1ee7c062de2853ca43/src/utils/detect-server.js#L78, https://github.com/netlify/cli/blob/8efe94e5fb38976c49f0cf1ee7c062de2853ca43/src/utils/detect-server.js#L82 and https://github.com/netlify/cli/pull/843#issue-405552392
> fix(docs): change port to targetPort when framework is #custom

- docs/netlify-dev.md
Fixes the docs to add a missing `jwtSecret` configuration to the `dev` block.
Follow up on https://github.com/netlify/cli/pull/1545
> fix(docs): add jwtSecret doc to dev section

- src/commands/init.js
**- Summary**
Related to https://github.com/netlify/cli/issues/958
Tested manually
Use `siteInfo` from `@netlify/config` instead of calling `api.getSite`
🐱
> refactor(command-init): remove duplicate call to getSite

- tests/command.deploy.test.js
This PR propagate `fetch` errors in our `deploy` tests to make it easier to debug flaky CI
> test: add debug log

- site/package-lock.json
- site/package.json
**- Summary**
When running the `site:build:install` command, I'm getting an error for a missing dependency: `nan`. This seems to be a problem with a transitive dependency, as reported in https://github.com/fsevents/fsevents/issues/320.
This PR removes that error by adding `nan` to the `devDependencies` list of the docs site.
Issue observed and solution verified in Node v12.20.0. Test suite running smoothly.
Add nan to devDependencies of docs site
> Fix dependency error in docs site

- src/utils/dev.js
**- Summary**
This PR adds logging messages that flag to the user whenever an environment variable they've defined is overridden by another variable with the same name defined somewhere with a higher precedence.
Closes #1598.
In this example, I've defined `NETLIFY_TEST_VAR` in four places (`.env` file, `.env.development` file, team-level environment, and site-level environment) and `TWITTER_SCREEN_NAME` in two (site-level environment and process level).
Log overridden environment variables
> Add logging for ignored env vars

- docs/commands/deploy.md
- src/commands/deploy.js
**- Summary**
Adding an alias of 38 characters or more leads to the site not being deployed to the desired URL but instead does not resolve. This is a hard issue to debug. Furthermore, other documentation should be updated to state this limitation
Read the docs
- Update deploy.md and deploy.js reflect the 37 character limit 
https://imgur.com/L6NPukj
> Document: 37 character limit on alias flag

- src/utils/dev.js
**- Summary**
In the last few months the addition of Build Plugins (particularly https://github.com/bencao/netlify-plugin-inline-functions-env) combined with the [deploy context env var](https://docs.netlify.com/configure-builds/environment-variables/#build-metadata) have made it possible for Functions to feel environment-agnostic a la:
```js
const contextualEnvVar = (v) => {
const currentContext = process.env.CONTEXT
const formattedContext = currentContext.replace('-', '_').toUpperCase()
return process.env[`${formattedContext}_${v}`]
}
exports.handler = async _ => {
return {
statusCode: 200,
body: JSON.stringify({
status: contextualEnvVar('API_KEY')
})
}
}
```
I'll be writing up a post on this soon, but the premise is that I can set `PRODUCTION_API_KEY`, `DEPLOY_PREVIEW_API_KEY`, and …
> Set CONTEXT when running Netlify Dev

- tests/utils/call-cli.js
This PR adds a timeout of 30 seconds for CLI invocations in our tests.
> test: add CLI timeout

- package-lock.json
- package.json
- tests/command.deploy.test.js
- tests/command.dev.test.js
- tests/cra.test.js
- tests/rules-proxy.test.js
- tests/utils/got.js
Replaces the usage of `node-fetch` to `got` in our tests.
This allows:
1. Built in retries
2. Built in timeouts
Related to https://github.com/netlify/cli/issues/1703
> test: use got instead of node-fetch

- package-lock.json
- package.json
- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/commands/env/get.js
- src/commands/env/list.js
- src/commands/functions/create.js
- src/lib/build.js
- src/utils/command.js
- src/utils/dev.js
- src/utils/dot-env.js
- src/utils/dot-env.test.js
- tests/command.build.test.js
- tests/command.dev.test.js
**- Summary**
This PR is the CLI counterpart of https://github.com/netlify/build/pull/2040. It introduces the updated environment variables object coming from `@netlify/build` to various commands.
Copying across this list created by @ehmicky in the build PR. I'll use it to track the progress on the various commands.
- `netlify build`:
- [`netlify env:list`](https://github.com/netlify/cli/blob/e031d8eb3bc2b56e85fc19e5fc395440acd30158/src/commands/env/list.js#L26) and [`netlify env:get`](https://github.com/netlify/cli/blob/e031d8eb3bc2b56e85fc19e5fc395440acd30158/src/commands/env/get.js#L23):
We might want to select only specific environment variables categories, and merge them.
- `netlify dev`, `netlify dev:exec`, `netlify functions:create`:
- Pass [`--offline` CLI …
> Use environment variables from @netlify/config

- package-lock.json
- package.json
- src/commands/dev/index.js
- src/utils/traffic-mesh.js
- tests/command.dev.test.js
This brings a new version of the TM agent that fixes most of the tests
failing for it in the dev suite. It also modifies some of the test
to change expectations that are not required to work exactly equally
across both proxies, like common response headers.
Fixes #1724
> chore(dev): update TM agent and tests

- src/utils/dev.js
- tests/command.dev.test.js
**- Summary**
Force the value of the `CONTEXT` environment variable to `dev`. Reinstates https://github.com/netlify/cli/pull/1685.
Added integration tests to ensure this regression is not introduced again.
fix: override CONTEXT env variable
> fix: override CONTEXT env variable

- .github/workflows/labeler.yml
Uses a matrix in the PR labeler action and updates the action to use the new repo path (we transferred it from `erezrokah` to `netlify`)
> chore: update PR labeler

- .github/workflows/verify-docs.yml
- CONTRIBUTING.md
Related to https://github.com/netlify/cli/issues/1665.
Solves the blocker for adding a release PR workflow by verifying docs are synced using a GitHub action.
Makes sure a change to a command has the relevant doc change (instead of pushing the docs to the default branch during publishing).
Useful until we do https://github.com/netlify/cli/issues/304
> chore: verify docs using a GitHub action

- src/lib/http-agent.test.js
This test has been randomly failing. See https://github.com/netlify/cli/pull/1747/checks?check_run_id=1708215271#step:7:357
I updated it to check for either message without being platform dependent
> test(http-agent): fix flaky test

- package.json
- src/lib/deprecations.js
- src/utils/command.js
- tests/command.test.js
Related to https://github.com/netlify/product/issues/257#issuecomment-746446846 and https://github.com/netlify/build/pull/2175
See example log:
Not sure if we should avoid duplicating the logic by having `@netlify/conifg` or `@netlify/build` return it.
Since it's a temporary message I think we can live with it.
> feat: warn when project has netlify dir

- package.json
Removes `verbose` flag from `ava` and only keep the JSON coverage file in CI.
I'm hoping this will help with our CI jobs getting stuck during tests.
> test: generate only json coverage file in CI

- package-lock.json
- package.json
- src/commands/sites/create.js
**- Summary**
When CLI offers suggestions for a new site name (e.g. as part of `ntl init`), it uses the user's `slug` property, which isn't guaranteed to exist. This PR addresses that by computing a slug in those cases, using the `full_name` property.
Closes #1730 
- Verified that the behaviour for a user that does have the `slug` property remains unchanged
- Verified that the behaviour for a user that does not have the `slug` property now includes a slug
fix: compute slug for site name suggestions when user does not have one
> Compute slug for site name suggestions when user does not have one

- tests/command.build.test.js
Build tests now require a valid auth token which is not available to forked PRs.
Fixes CI failures in https://github.com/netlify/cli/pull/1758
> test(command-build): don't run on forked repos

- src/commands/api.js
**- Summary**
The anchor portion of the links had an extra slash which meant the page wouldn't scroll to the right section.
Fixed links to api docs in `netlify api --list`
> Fix links to api docs in `netlify api --list`

- package-lock.json
- package.json
- src/utils/detect-server.test.js
Since we dropped Node.js 10 we should be able to use `ava v3`
> test: upgrade ava to v3

- src/commands/status/index.js
- src/utils/command.js
**- Summary**
Since #1722, CLI is making an API call for every command, even for the ones that don't require API data (e.g. `login` and `logout`).
As a consequence, users might get locked in their accounts if they have an invalid/revoked token. If they try to login or logout, CLI will still try to use their existing token and fail before the command they're trying to execute has a change to succeed.
This PR adds a temporary solution that re-tries a call to `@netlify/config` _without_  a token if a call with the existing token fails.
It also adds a message to the `status` command checking for an unauthorised call to `api.listAccountsForUser` and `api.getCurrentUser` (currently it only exists for `api.getSite`. We should abstract this behaviour, so that any time we retrieve any user data …
> fix: recover from unauthorized error in @netlify/config call

- src/commands/dev/index.js
- src/detectors/next.js
**- Summary**
This PR allows us to toggle the local server polling functionality introduced in #1795 based on the framework being used. For now, we're disabling it for Next.js, since its local server triggers a new page build for every request during the startup phase.
Closes #1815.
fix: disable local server polling for Next.js
> fix: disable local server polling for Next.js

- .github/workflows/main.yml
Part of https://github.com/netlify/team-dev/issues/1
This tests Node 15 in CI.
This only tests Node 10 and 15, not 12. In my experience, it is quite rare to find a bug that fails on a specific major Node.js release but neither on an older nor newer one. Please let me know what you think.
> chore: support Node 15

- src/utils/headers.js
- src/utils/headers.test.js
- src/utils/proxy.js
The CLI's current behavior is to only allow the asterisk wildcard `*` at the end of a rule. This PR aims to add support for wildcard which matches Netlify's deploy logic, which does not seem to have the same restriction.
1. See https://github.com/netlify/next-on-netlify/issues/151
2. Closes #1148
Tests were updated in `headers.test.js`. More robust testing should likely be added before merging.
```none
Previously, (*) wildcards had to appear at the end of a rule path, as in /path/to/dir/*. The CLI now supports the asterisk wildcard at any part of the rule, i.e. /test/*/test/*/test.
```
> fix(headers): add support for consistent * wildcard

- src/utils/command.js
**- Summary**
Partially addresses https://github.com/netlify/cli/issues/1707 pending the long term solution in that issue.
Run `netlify logout` then `netlify login` and don't follow through with authentication
Timeout authorization after 5 minutes instead of 1 hour
> fix(command-login): reduce auth timeout, display spinner

- renovate.json5
**- Summary**
Renovate bot no longer uses the term `masterIssue` in their docs, it's now called `dependencyDashboard`.
If you want to make changes to your dashboard and search for `masterIssue` you're not going to find any references to that term in the Renovate docs.
This PR ensures you're using a current term.
The functionality does not change, you'll keep your Dependency Dashboard just the way it is now.
If you don't want this PR, you can just close it, as the Renovate bot already "massages" any old config terms to newer terms behind your back anyways. 😄 
Reference: https://docs.renovatebot.com/configuration-options/#dependencydashboard
I've done this migration for other repositories, and they had no problems with their dashboard. 😄  …
> chore: migrate masterIssue to dependencyDashboard

- README.md
- docs/README.md
- docs/commands/functions.md
- docs/commands/index.md
- src/commands/functions/list.js
**- Summary**
Added  command functions:list to the docs
nil
functions:list command which is missing in the docs have been added 
> feat(command-functions-list): remove hidden flag

- tests/utils/create-live-test-site.js
This is useful when the user belongs to multiple teams and the first one is not the one we want to test against.
> test: allow configuring test account slug

- src/utils/headers.js
- src/utils/headers.test.js
Follow up on https://github.com/netlify/cli/pull/1777 to fix header values such as `https://www.example.com`
> fix(command-dev): handle headers with colon in value

- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/commands/dev/trace.js
- src/utils/command.js
- src/utils/dev.js
- tests/command.dev.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1873
Added a couple of tests
Pass `context: dev` to `@netlify/config` when running dev related commands. This should tell `@netlify/config` to resolve settings from the correct `context`.
> fix(command-dev): pass dev context to '@netlify/config'

- renovate.json5
Fixes https://github.com/netlify/cli/issues/1663
Testing this configuration so we don't get releases with just a package lock file change
> chore(deps): update renovate to use  rangeStrategy bump

- src/commands/lm/uninstall.js
- src/utils/lm/install.js
- tests/command.lm.test.js
Follow up to https://github.com/netlify/cli/pull/1489.
Adds a hidden command to undo the changes made by `ntl lm:install` (to be used by our tests).
> test(command-lm): add uninstall command

- src/utils/lm/install.js
Follow up on https://github.com/netlify/cli/pull/1879#discussion_r576247092
@ehmicky we can't use `unixify` as it replaces drive names
> fix(command-lm-install): fix gitconfig path in windows

- src/commands/link.js
- src/commands/sites/list.js
- src/lib/api.js
- src/utils/link/link-by-prompt.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1898
Doesn't fix https://github.com/netlify/cli/issues/258 since that issue is now related to [strict SAML support](https://docs.netlify.com/accounts-and-billing/team-management/saml-single-sign-on/#only-sso-allowed) in the CLI.
Tested manually 
```sh
$ ntl sites:list --json | jq length
$ 226
```
Paginate on all sites when calling `listSites`
> fix(command-link): retrieve all sites using pagination params

- src/utils/lm/install.js
Fixes https://github.com/netlify/cli/issues/1895
On Windows we append to `PATH` and not prepend:
https://github.com/netlify/cli/blob/75742eeae55b57ef8b657811ddeb443167f9f9e5/src/utils/lm/scripts/path.ps1#L26
https://github.com/netlify/cli/blob/75742eeae55b57ef8b657811ddeb443167f9f9e5/src/utils/lm/scripts/zsh.sh#L3
https://github.com/netlify/cli/blob/75742eeae55b57ef8b657811ddeb443167f9f9e5/src/utils/lm/scripts/bash.sh#L14
So if you have a version in the old location it takes precedence.
I think we should remove those regardless when installing a version to the new location.
We could also do some cleanup, but I'm a bit worried breaking users environments by removing stuff from `PATH`.
In addition, we could also prepend to `PATH`.
> fix(command-lm-install): remove legacy version on install

- package.json
This removes `src/functions-templates/**/node_modules` from the package published to npm.
Before: `305.8 KB` (packed), `1.3 MB` (unpacked)
After: `160.5 KB` (packed), `599.2 KB` (unpacked)
> fix: reduce package size

- src/utils/init/utils.js
**- Summary**
fixes https://github.com/netlify/cli/issues/1909
Updates the default functions directory recommendation to `netlify/functions`
> fix(command-init): use netlify/functions instead of functions

- src/lib/build.js
**- Summary**
With the rollout of esbuild (https://github.com/netlify/zip-it-and-ship-it/pull/339 and https://github.com/netlify/build/pull/2308), `zip-it-and-ship-it` will no longer look for a `NETLIFY_EXPERIMENTAL_ESBUILD` environment variable. This means that people who want to bundle locally using esbuild will lose their ability to opt-in.
Until we have #1913, there's no feature flag mechanism extended to the CLI, so this PR reuses the same environment variable that `zip-it-and-ship-it` was using. When it's detected, the correct feature flag (i.e. `buildbot_esbuild`) is passed along to Netlify Build.
feat: add environment variable for esbuild
> feat: add environment variable for esbuild

- src/commands/dev/index.js
- tests/command.dev.test.js
**- Summary**
The `--trafficMesh` flag is not a super clear term to users, let's go for `--edgeHandlers` which is more to the point. Deprecate the current flag in favor of a. new flag and add a warning to users that use the old one.
Choose your poison:
- `npm run test` (follow Contributing.md for instructions)
- `netlify dev --edgeHandlers`
- `netlify dev -eh`
Rename `netlify dev` flag `--trafficMesh` (short: `-t`) to `--edgeHandlers` (short: `-eh`) and update description to `activates the edge handlers runtime`.
> feat: rename trafficMesh flag to edgeHandlers

- renovate.json5
Use the default renovate strategy to avoid restricting ranges for non Netlify packages.
For Netlify packages we still use `bump` from https://github.com/netlify/renovate-config/blob/e7e66c5e8ec56923e0acfcb8b335564e86e7ff2d/default.json#L23
This should close all of theses PRs
> chore: use default rangeStrategy

- src/utils/detect-server.js
- src/utils/serve-functions.js
- tests/command.dev.test.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1279
Call the `next` function when an invalid request was sent to the functions form submission handler to avoid blocking forever.
> fix(command-dev): call middleware next on invalid content-type

- renovate.json5
We can't update these until we drop support for Node.js 10
> chore: ignore major updates for 'open' and 'inquirer'

- src/commands/sites/delete.js
**- Summary**
When running `ntl sites:delete <site-id>` from a directory not linked to a site the prompt before deleting the site had `undefined` in the warning message.
This PR fixes it.
Before:
After:
Fix `undefined` in warning message when deleting a site.
> fix(sites-delete): use siteId instead of cwdSiteId for warning messages

- .github/PULL_REQUEST_TEMPLATE.md
We don't really need the `Description for the changelog` part in the PR template as we autogenerate the changelog.
> chore: remove redundant changelog header in pr template

- docs/commands/watch.md
- site/src/_app.js
**- Summary**
The watch command is available when someone runs `ntl help`. It doesn't make any sense to hide it in the site docs.
See preview URL
> fix: add missing watch command to docs site

- docs/commands/deploy.md
- src/commands/deploy.js
This lets you publish to production if it's unlocked in the Netlfify dashboard and create drafts otherwise.
closes #1392
The oclif/command lib doesn't let us create a `--prod=auto` flag that's also a boolean flag so it's separate. I think it's clearer anyway.
> feat: add a --prodIfUnlocked flag

- .eslintrc.js
- src/functions-templates/js/fauna-crud/create-schema.js
- src/functions-templates/js/fauna-crud/create.js
- src/functions-templates/js/fauna-crud/delete.js
- src/functions-templates/js/fauna-crud/read.js
- src/functions-templates/js/fauna-crud/update.js
- src/functions-templates/js/sanity-create/sanity-create.js
- src/functions-templates/js/sanity-groq/sanity-groq.js
- src/functions-templates/js/slack-rate-limit/slack-rate-limit.js
- src/utils/read-repo-url.js
Related to https://github.com/netlify/cli/issues/1891
> refactor: enable and fix prefer-await-to-then

- package-lock.json
- package.json
- src/utils/command.js
- src/utils/init/config-github.js
- src/utils/init/config-manual.js
- src/utils/init/frameworks.js
- src/utils/init/node-version.js
- src/utils/init/plugins.js
- src/utils/init/utils.js
- tests/command.init.test.js
- tests/command.lm.test.js
- tests/utils/mock-api.js
- tests/utils/site-builder.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/1832 pending https://github.com/netlify/framework-info/issues/123 and https://github.com/netlify/netlify-plugin-nextjs/issues/93
Going to do some more testing once the blocking issues are completed
Recommend plugins during `ntl init` command and let the user choose if to install them
> feat(command-init): recommend build plugins

- tests/command.init.test.js
- tests/utils/site-builder.js
This PR fixes an issue with our tests expecting the default branch of `git init` to be `master` (the test fails for users with a different default branch).
> test(command-init): use predictable branch name

- src/commands/status/index.js
**- Summary**
I noticed `ntl status` only prints the site information if the site has a `netlify.toml`.
This doesn't make sense to me.
`site.configPath` is used later on in the code in `logJson` and `prettyjson.render`. Both filter out `undefined`.
Run `ntl status` on a site without `netlify.toml`
> fix(command-status): site info is missing for sites without netlify.toml

- src/utils/lm/install.js
- src/utils/lm/scripts/fish.sh
- src/utils/lm/ui.js
**- Summary**
Replaces https://github.com/netlify/netlify-lm-plugin/pull/42
Existing tests are passing
Add `fish` shell support for Large Media install command
> feat(command-lm): add PATH configuration for fish shell

- src/utils/init/config-github.js
This PR fixes a typo in one of our `ntl init` messages
> fix(command-init): use GitHub instead of Github

- src/utils/proxy.js
- tests/command.dev.test.js
- tests/utils/site-builder.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2013
Fixes https://github.com/netlify/cli/issues/1605
Also see https://answers.netlify.com/t/querystringparameters-not-working-with-redirect-on-production/3828 and https://github.com/netlify/proxy/issues/449
This PR aligns the way query parameters redirects work in `netlify dev` with our production environment.
Given the following `_redirects` file:
```
/api/* /.netlify/functions/test?foo=1&foo=2 200
/foo / 302
/bar /?a=1&a=2&b=3 302
/test id=:id /?param=:id
```
The expected behavior based on the repo https://github.com/erezrokah/fn-payload-test deploy to https://erez-redirects-query.netlify.app/
1. Rewrites to functions always strip the redirect rule query params in favor of passing through the request query params.
2. If a non …
> fix(command-dev): fix query params handling in redirects

- tests/command.init.test.js
**- Summary**
See https://github.com/netlify/cli/pull/2028/commits/1c34d24e9b268203cffcf92f71a562491d94fc31
These tests were failing on forked PRs since forks don't have access to the Netlify access token configured as a repo secret (so the CLI prompted the user to login).
For these specific tests we can use a fake token, since we're using a mock API.
N/A
> test(command-init): make tests pass on forked PRs

- .eslintrc.js
- src/commands/functions/create.js
- src/functions-templates/js/fauna-crud/create-schema.js
- src/functions-templates/js/using-middleware/using-middleware.js
- src/utils/lm/steps.js
- src/utils/rules-proxy.js
- tests/utils/dev-server.js
Related to https://github.com/netlify/cli/issues/1891
It seems `prefer-await-to-callbacks` relies too much on argument names.
> refactor: enable and fix promise rules

- src/utils/gitignore.js
**- Summary**
Partially fixes https://github.com/netlify/cli/issues/2029 (I'll open other separates issue per https://github.com/netlify/cli/issues/2029#issuecomment-803581401)
On a linked repo change your `.gitignore` `.netlify` pattern to `/.netlify` and re-run `ntl link`.
> fix(command-link): don't modify gitignore if a pattern includes .netlify

- src/lib/build.js
**- Summary**
This PR removes the esbuild feature flag that is no longer in used. It was deprecated in favour of the functions configuration API.
N/A
> chore: remove esbuild feature flag

- docs/commands/functions.md
- src/commands/functions/create.js
- tests/command.functions.test.js
- tests/command.init.test.js
- tests/utils/handle-questions.js
**- Summary**
Currently, if no directory is specified for functions in the user's `netlify.toml`, you get an error. The user is required to go to the docs to learn how to configure the setting in netlify.toml. This PR creates a directory for the user with a default to `netlify/functions`
Also updates instances of `folder` to `directory` in the functions command.
Closes #1822, #1957 
Run `netlify functions:create`
With a functions directory already existing:
Without a functions directory:
> feat: add functions directory creation when non-existent in netlify.toml

- .github/workflows/main.yml
Only test Node.js 10 on linux.
Aligns the testing matrix with our other Node.js repos
> chore: only test Node.js 10 on linux

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/fossa.yml
- .github/workflows/main.yml
- .github/workflows/release-please.yml
- .github/workflows/verify-docs.yml
- CONTRIBUTING.md
- README.md
- codecov.yml
- docs/netlify-dev.md
- site/src/_layout.js
- src/detectors/README.md
- src/utils/init/utils.js
**- Summary**
Ended up making this a `feat:` since it required changing some CLI code
Existing tests
🐼
> feat: rename default branch from master to main

- renovate.json5
> chore(renovate): ignore Node.js>=12 packages

- src/function-builder-detectors/zisi.js
- tests/command.dev.test.js
**- Summary**
Since #2094, `netlify dev` is serving functions after bundling them with `zip-it-and-ship-it`. To contain the risks of that change, we enable it only when we detect that users have opted in to esbuild via the `functions.node_bundler` configuration property.
However, we treat TypeScript support as GA, with no correlation with the opt-in mechanism to the beta feature that `node_bundler` provides. This means that someone who wants to continue to use the legacy bundler for JavaScript functions but also include a TypeScript function will not be able to access the TypeScript function locally, since CLI will serve the raw file.
This PR changes the condition used by the `zisi` function builder, so that it's enable if `node_bundler` is `esbuild` _or_ there's at least one TypeScript …
> feat: use zisi function builder when using TypeScript functions

- .github/workflows/release-please.yml
Follow up on https://github.com/netlify/cli/pull/2141
We need to install `./site` dependencies so linting passes (we run the linter on the `prePublishOnly` script).
See failure here https://github.com/netlify/cli/runs/2372808042?check_suite_focus=true
> chore(release-please): fix release process

- .github/workflows/release-please.yml
Another follow up (see https://github.com/netlify/cli/pull/2149).
The tests we run on `prePublishOnly` hit the Netlify API so they need the auth token passed as a secret
> chore(release-please): add missing env variables

- .github/workflows/benchmark.yml
**- Summary**
Adds a benchmark workflow to track the evolution of the package size. It works by running `npm install --production` and calculating the size of the generated `node_modules` directory. It makes use of https://github.com/netlify/delta-action to report the results and compare against the baseline.
N/A
> chore: add package size benchmark

- src/utils/get-functions.js
- src/utils/get-functions.test.js
- src/utils/serve-functions.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/909
~~Still in draft since I need to test it more~~
I believe we would need to add similar code to the functions builders to make this work for `esbuild`.
Another way to implement this is via configuration (e.g. flags/`netlify.toml` or both)
🐼
> feat(command-dev): watch all functions files

- .github/workflows/main.yml
**- Summary**
A shot in the dark trying to prevent our Windows CI from hanging. The default shell for windows is PowerShell.
I couldn't reproduce this on my Windows VM and also getting nowhere with this https://github.community/t/github-actions-times-out-with-no-logs/156707/2
Merge to `main` and see if this makes a difference
> chore(ci): switch to cms shell on windows

- src/function-builder-detectors/zisi.js
**- Summary**
Delete the functions serving directory when the ZISI function builder is initialised.
Closes #2190.
N/A
🐦
> fix: delete the directory from which functions will be served

- package-lock.json
- package.json
This fixes https://github.com/netlify/cli/issues/2202 (and https://github.com/alexreardon/memoize-one/issues/80).
Since currently we're using `^5.1.1` format, `5.2.0` is used for the CLI and it is causing the error. By pinning the memoize-one version to `5.1.1`, the error will be gone.
We can look into for upgrading `5.2.0` or not later on.
> fix(deps): pin memoize-one to 5.1.1

- package-lock.json
- package.json
- src/utils/get-global-config.js
**- Summary**
Following up on #2204 and #2202. The latest release of memoize-one introduced a breaking change for the cjs exports - https://github.com/alexreardon/memoize-one/releases/tag/v5.2.0 - this PR bumps the `memoize-one` dep and addresses the breaking changes.
> fix(deps): memoize-one cjs exports breaking changes

- package-lock.json
- package.json
- src/utils/get-global-config.js
Context: https://github.com/netlify/cli/issues/2202
`memoize-one@5.2.0` introduced an unintentional breaking change to the CommonJS bundle. `5.2.0` has been deprecated, and `5.2.1` removes the named import to revert the breaking change to the CommonJS bundle.
This PR simply bumps you back to `5.2.1` and moves away from the named import which is no longer supported (as `5.2.0` has been deprecated)
> fix(deps): upgrading memoize-one to 5.2.1

- src/utils/get-functions.js
- src/utils/get-functions.test.js
**- Summary**
Partially reverts https://github.com/netlify/cli/pull/2143 as the code doesn't work with `esbuild` [yet](https://github.com/netlify/cli/pull/2228).
Fixes https://github.com/netlify/cli/issues/2227
Fixes https://github.com/netlify/cli/issues/2238
Existing tests
🐒
> fix(command-dev): revert usage of listFunctionsFiles

- tests/utils/dev-server.js
**- Summary**
In CI we pass a NETLIFY_AUTH_TOKEN. When this env variable exists `@netlify/config` infers that we should retrieve site information from the production API:
https://github.com/netlify/build/blob/b442daf2efa2a31057e8628309903f6ec3976945/packages/config/src/options/main.js#L40
https://github.com/netlify/build/blob/b442daf2efa2a31057e8628309903f6ec3976945/packages/config/src/api/client.js#L9
This is not required for `dev` command tests.
Existing tests
🐢
> test(command-dev): don't pass auth token to CLI

- src/utils/detect-server.js
This was a very confusing error message. "args" in this case is an implementation detail, and the error message didn't provide any insight as to what might have gone wrong.
In my case, it was using `craco` to override my base `create-react-app` config, which meant a change to the start script from `react-scripts-start` to `craco start`. I didn't know how to use a custom framework until after writing a craco-specific detector in my local install of the CLI
**- Summary**
> fix(command-dev): Update detect-server.js

- src/commands/dev/index.js
- src/utils/dev.js
- src/utils/serve-functions.js
- tests/command.dev.test.js
- tests/utils/dev-server.js
**- Summary**
The CLI synchronous functions timeout was hardcoded to 10 seconds.
This PR retrieves the timeout based on the site information and uses it, if present.
Added a test
🐼 
Fixes https://github.com/netlify/pod-workflow/issues/198 and https://answers.netlify.com/t/increase-function-timeout/26361/12
> fix(command-dev): use custom functions timeout if present

- tests/command.addons.test.js
- tests/utils/mock-api.js
**- Summary**
Uses a mock API for our addons tests. I'll port each set of tests in a separate PR.
As a bonus this allows running tests in parallel and also removes the need to skip these tests on forked PRs
See modified tests
> test(command-addons): use mock api

- src/detectors/jekyll.js
**- Summary**
Detects Jekyll if the project uses `_config.yaml` or `_config.toml` as the configuration file instead of `_config.yml` which is currently the only detected config file name for Jekyll.
I've recently started using Netlify dev, and found that while it worked as I expected in an Angular project (when running `netlify dev`, I saw the expected output from `ng serve` and the server updated as file changes were made), it didn't run `jekyll serve` in a Jekyll project, even though I've defined the project as a Jekyll project (Netlify build command is `jekyll build`, and `jekyll serve` is defined as the `start` script in `package.json`).  When I forced Netlify dev to use Jekyll by setting
```toml
[dev]
framework = "jekyll"
```
in my `netlify.toml` file, the cli gave the error message …
> fix(command-dev): detect other Jekyll config file names

- .github/workflows/main.yml
**- Summary**
Another attempt to improve Windows tests.
See https://docs.microsoft.com/en-us/biztalk/technical-guides/settings-that-can-be-modified-to-improve-network-performance#adjust-the-maxuserport-and-tcptimedwaitdelay-settings and https://www.ibm.com/docs/en/records-manager/8.5.0?topic=performance-configuring-maxuserport-maximum-user-ports
Default port limit is between 1024 to 5000 and default time wait delay is 120
Existing test
> test(windows): increase port limit and reduce time wait delay

- .github/workflows/main.yml
**- Summary**
We don't need to run the full test suite if we only changed files under `docs/`, for example https://github.com/netlify/cli/pull/2320
Please note this is only relevant for the manually created docs as most commands docs are autogenerated based on the CLI code (meaning most docs changes are coupled to code changes).
Existing tests
🐱
> ci(github): skip CLI tests for docs changes

- npm-shrinkwrap.json
- package.json
- tests/command.addons.test.js
- tests/command.env.test.js
- tests/utils/mock-api.js
**- Summary**
A bit of refactoring before opening a PR for https://github.com/netlify/cli/issues/2302 to make the upcoming PR easier to review.
This PR changes the mock API to use object comparison instead of string comparison when matching request body to allow comparing the same object with different properties order.
Exiting tests
🐐
> test(mock-api): use object comparison

- src/commands/init.js
- src/commands/link.js
- src/utils/command.js
- tests/command.link.test.js
- tests/utils/site-builder.js
**- Summary**
Fixes https://github.com/netlify/cli/issues/2383
Added new tests for the `link` command
> fix(command-link-init): always create gitignore in repo root

- src/utils/init/config-github.js
- src/utils/init/config-manual.js
- src/utils/init/utils.js
- tests/command.init.test.js
**- Summary**
Related to https://github.com/netlify/cli/issues/2302 and https://github.com/netlify/cli/issues/2380
During `ntl init` we used to set the functions directory in a separate API call due to a bug in our API.
That bug has been fixed so we can remove the workaround.
Updated the tests to use `requestBody` instead of validating requests. `requestBody` was added recently to the mock API and asserts that the request body sent by the CLI matches the expected one.
🐦
> fix(command-init): remove functions dir workaround

- src/commands/deploy.js
- src/utils/deploy/deploy-site.js
- src/utils/deploy/hash-fns.js
**- Summary**
Shows a warning when running `netlify deploy` on a site that uses at least one function with native Node.js dependencies.
Closes #2363.
N/A
> feat: add warning for native modules

- .github/workflows/benchmark.yml
- .github/workflows/main.yml
- .github/workflows/release-please.yml
- .github/workflows/verify-docs.yml
Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.
> chore: run CI on latest Node.js

- functions/telemetry.js
- netlify.toml
**- Summary**
This is a follow up of the work in https://github.com/netlify/cli-telemetry-service/issues/14 and developed under https://github.com/netlify/pod-workflow/issues/160
I've tested this work locally, however I'll probably give the redirects a try once the deploy preview is up and running 👍 
🐥
> chore(telemetry): switch the telemetry backend via redirects

- tests/command.functions.test.js
Follow up on https://github.com/netlify/cli/pull/2450
Increases the `functions:serve` wait port timeout since it's flaky on CI
> test(command-functions): increase wait port timeout

- src/hooks/analytics.js
- src/hooks/init.js
- src/utils/command.js
- src/utils/telemetry/index.js
- src/utils/telemetry/request.js
- tests/telemetry.test.js
- tests/utils/mock-api.js
**- Summary**
Related to https://github.com/netlify/cli/issues/2458
Cleans up our telemetry code a bit and also fixes a bug with `netlify --telemetry-enable` not being tracked
Added 2 new tests for `--telemetry-disable` and `--telemetry-enable` using a mock API
> fix(telemetry): fix tracking of --telemetry-enable flag

- src/utils/deploy/hash-files.test.js
- src/utils/deploy/hash-fns.test.js
**- Summary**
Related to Related to https://github.com/netlify/cli/issues/2209
I'm doing some benchmarking on our tests and noticed the `hash-fns.test.js` takes about 20 seconds on my machine when executed as a single test (it's slower when running all tests in parallel).
On CI with limited compute this is even worse:
https://github.com/netlify/cli/runs/2672814438?check_suite_focus=true#step:8:289
I believe the reason is that it's using `__dirname` at the functions directory to hash which is not necessary. 
I changed it to use a dedicated site and also cleaned up both tests
Existing tests
> test(command-deploy): improve hash files/fns tests

- .github/workflows/benchmark.yml
- .github/workflows/main.yml
- .github/workflows/verify-docs.yml
- package.json
**- Summary**
Adds the `--no-audit` flag to `npm ci` and `npm install` commands. It's not really useful for GitHub workflows/CI.
Since npm v7 `npm ci` also runs the audit which adds a few seconds to each installation process.
See https://github.com/npm/cli/issues/2703.
Also we use renovate to update dependencies and GitHub alerts us when there are security vulnerabilities, so I don't think there's much benefit to it. 
Existing tests
🦒 
> On a side note we can consider adding this to all our repos workflows
> chore(ci): pass --no-audit flag to npm

- src/utils/telemetry/request.js
- tests/utils/mock-api.js
**- Summary**
Sets the correct `content-type` header for the telemetry requests.
Automatted tests but I've also run it locally. The resulting lambda execution shows the header was set 👍 :
```bash
1:10:17 PM: {"level":30,"time":1622203817056,"pid":9,"hostname":"169.254.11.189","httpMethod":"POST","path":"/track","headers":{"accept":"*/*","accept-encoding":"gzip","client-ip":"100.64.0.79","content-length":"150","content-type":"application/json","forwarded":"for=94.63.204.136;proto=https","host":"cli-telemetry.netlify.engineering","user-agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","via":"http/1.1 Netlify[87e6d7c6-478f-436c-8a38-93295836ce5d] (Netlify Edge Server), https/1.1 Netlify[33025fc6-25ae-4c95-818f-5f3496865ae1] (Netlify Edge …
```
> fix(telemetry): add the correct content-type header to the request

- src/utils/telemetry/request.js
- tests/telemetry.test.js
- tests/utils/mock-api.js
**- Summary**
Follow up on #2458 and https://github.com/netlify/cli-telemetry-service/issues/26. Updates our `uger-agent` header to fwd the app and version performing the request.
Tested locally, the lambda execution was the following (notice the `user-agent` headers):
```bash
1:37:59 PM: {"level":30,"time":1622205479733,"pid":8,"hostname":"169.254.46.221","httpMethod":"POST","path":"/track","headers":{"accept":"*/*","accept-encoding":"gzip","client-ip":"100.64.0.248","content-length":"150","content-type":"application/json","forwarded":"for=94.63.204.136;proto=https","host":"cli-telemetry.netlify.engineering","user-agent":"netlify-cli/3.31.14","via":"http/1.1 Netlify[b80cee17-b260-40c2-91ea-78b3223a8dc1] (Netlify Edge Server), https/1.1 …
```
> fix(telemetry): add cli user-agent to the request with the cli version included

- src/detectors/redwoodjs.js
As part of adding framework detection for RedwoodJS with:
https://github.com/netlify/framework-info/blob/main/src/frameworks/redwoodjs.json
We also need to add a detector so that `netlify dev` will detect a redwoodjs-based site/app.
This PR endeavors to add this configuration such that netlify dev can be used with a `netlify.toml` file in a RedwoodJS app like:
```toml
[dev]
command = "yarn rw dev"
framework = "redwoodjs"
targetPort = 8910 # The port for your application server, framework or site generator
port = 8888 # The port that the netlify dev will be accessible on
```
Notes:
* we do use `yarn rw dev` as the command and `yarn rw` is set in this detector. We do know this might spawn an extra yarn, but so much of our docs use `yarn rw` and Redwood uses `yarn workspaces` so the …
> feat: Adds RedwoodJS Detector for netlify dev

- src/detectors/svelte-kit.js
- src/detectors/svelte.js
**- Summary**
Neither the [`svelte`](https://github.com/netlify/cli/blob/main/src/detectors/svelte.js) nor [`sapper`](https://github.com/netlify/cli/blob/main/src/detectors/sapper.js) detector fit to SvelteKit as discussed here https://github.com/sveltejs/kit/issues/1568 and its PR. That's why I added a new detector.
Unfortunately a small but -- in my opinion -- reasonable workaround is needed to make Netlify Dev useful together with SvelteKit: enforcing a prod build beforehand. But it looks like e.g. the [angular](https://github.com/netlify/cli/blob/main/src/detectors/angular.js) detector is doing something similar (for similar reasons?!)
I've run and tested it locally. Both the detection itself and the enforcement of a SvelteKit production build is working fine.
**- A …
> feat: add detector for SvelteKit

- src/hooks/init.js
- src/index.js
**- Summary**
This is a result of going over results generated from https://github.com/davidmarkclements/0x.
See example for the `status` command [here](https://netlify-cli-performance.netlify.app/status).
This lazy loads `envinfo` and disables `registerTSNode` (see huge chunk due to it in above link).
Before see 20 invocations of the `status` command (my local machine on a linked sites):
```
ntl status --silent  0.88s user 0.33s system 31% cpu 3.807 total
ntl status --silent  0.80s user 0.27s system 51% cpu 2.109 total
ntl status --silent  0.81s user 0.28s system 53% cpu 2.033 total
ntl status --silent  0.84s user 0.28s system 55% cpu 2.014 total
ntl status --silent  0.79s user 0.25s system 50% cpu 2.077 total
ntl …
```
> fix(performance): load envinfo on demand, disable ts-node

- src/utils/detect-server.js
- src/utils/get-functions.js
- src/utils/serve-functions.js
**- Summary**
Related to https://github.com/netlify/cli/issues/2209.
Improves the `netlify dev` command initialization time, from when the user runs `netlify dev` until the first log line is printed here:
https://github.com/netlify/cli/blob/1590158bc72f18daa9e908a2409e5a9e48ee9393/src/commands/dev/index.js#L201
For projects that don't have a functions directory the execution time is also improved as we don't require related dependencies.
Based on running an analysis with https://github.com/davidmarkclements/0x
Before
```
BROWSER=none ntl dev --silent  3.03s user 0.55s system 158% cpu 2.261 total
BROWSER=none ntl dev --silent  2.74s user 0.49s system 158% cpu 2.037 total
BROWSER=none ntl dev --silent  2.77s user 0.50s system 161% cpu 2.030 total
BROWSER=none ntl dev …
```
> fix(command-dev): improve initialization time

- src/utils/rules-proxy.js
Part of https://github.com/netlify/build/issues/2889
This is a small clarification of the logic used to find the files containing redirect rules.
> chore: refactor redirects file path logic

- src/commands/deploy.js
- src/function-builder-detectors/zisi.js
- src/utils/deploy/deploy-site.js
- src/utils/deploy/hash-fns.js
**- Summary**
Passes the `basePath` and `experimentalHandlerV2` parameters to `zip-it-and-ship-it`, as introduced by https://github.com/netlify/zip-it-and-ship-it/pull/474.
N/A
🦒
> feat: use ZISI v2 handler

- src/utils/get-global-config.js
**- Summary**
An attempt to fix an issue that's be causing our [Windows CI to be unstable](https://github.com/netlify/cli/runs/2822712775?check_suite_focus=true#step:8:498).
Underlying issue is https://github.com/npm/write-file-atomic/issues/28
Existing tests
🐒
> fix(windows): retry getGlobalConfig

- src/lib/functions/server.js
- src/lib/functions/synchronous.js
- src/lib/functions/utils.js
- src/lib/log.js
**- Summary**
Adds a warning message whenever a runtime error occurs due to `aws-sdk` being missing. This must accompany https://github.com/netlify/cli/pull/2713, since `lambda-local@2.0.0` no longer includes `aws-sdk` as a dependency.
N/A
🐦
> feat: add warning for missing aws-sdk dependency

- src/function-builder-detectors/zisi.js
- src/lib/functions/memoized-build.js
**- Summary**
Moves this utility from the ZISI function builder to its own file.
Part of #2806.
> refactor: abstract `memoizedBuild` util to a separate file

- tests/command.dev.test.js
- tests/utils/dev-server.js
Part of https://github.com/netlify/cli/pull/1704/
This passes the `--offline` flag for `ntl dev` in our tests instead of removing the `NETLIFY_AUTH_TOKEN` env variable.
Both are valid ways to prevent `ntl dev` sending API requests, `--offline` is more clear.
There is only a single tests that needs to hit the API so I updated it accordingly.
> test(command-dev): pass offline flag by default

- tests/command.functions.test.js
These tests are randomly failing in our CI.
See also https://github.com/netlify/cli/issues/2876
> test(command-functions): skip flaky tests

- src/lib/functions/runtimes/js/index.js
- tests/command.dev.test.js
**- Summary**
Follow up on https://github.com/netlify/cli/pull/2826
Fixes an issue where functions headers from `lambda-local` are not passed down to the functions server.
Found it while reviewing https://github.com/netlify/cli/pull/2852
Added a test case for it
🐪
> fix(command-dev): pass full lambda-local result functions server

- npm-shrinkwrap.json
- package.json
- src/utils/read-repo-url.js
- src/utils/read-repo-url.test.js
Closes #2896 
**- Summary**
- Removes the unlicensed `safe-join` dependency
- Instead, we remove the leading and trailing slashes from the path
:eyes: 
:eyes: :eyes:
> chore: remove `safe-join` dependency

- .github/workflows/main.yml
- CONTRIBUTING.md
- tests/command.deploy.test.js
**- Summary**
resolves https://github.com/netlify/cli/issues/2541
This PR clarifies that the deploy test suite use a live site to run integration tests which require an active Netlify account. 
To make things simpler to configure, the `IS_FORK` environment variable (which disables these tests) has been renamed to `NETLIFY_TEST_DISABLE_LIVE`. 
`npx ava -v -s` for https://github.com/netlify/cli/commit/a134b72409550aec4676a992d47dcca668322eb9 on Node.js 10
> fix(docs): clarify live site creation from tests closes #2541

- .eslintrc.js
- src/utils/chalk.js
**- Summary**
See #1891 
Enables the fp/no-proxy  for `eslint-plugin-fp`.
There was only a single instance of Proxy being used to disable colors for the [chalk](https://www.npmjs.com/package/chalk) package. The package now has a `level` option that can be used to disable the coloring as documented here: https://github.com/chalk/chalk#chalklevel.
The file: `src/utils/command.js` was using this custom chalk instance.
`npx ava -v -s` ran without errors. I tried out the `sites:list` command normally and with the `--json` flag. As expected `--json` produced discolored output.
> refactor: enable and fix fp/no-proxy

- tests/command.deploy.test.js
- tests/command.dev.test.js
- tests/utils/site-builder.js
**- Summary**
The current edge-handler tests make assumptions about where edge-handler code is stored (default directory). Although this is an interface (contract) worth testing, it is hampering our ability to change this default. This PR removes the reliance on a default directory by explicitly configuring one.
Since the changes are only to tests, i'm relying on CI to ensure they are passing.
> test(edge-handlers): using new edge-handler default directory

- .github/workflows/pre-release.yml
**- Summary**
This PR fixes the pre-release workflow by:
- Installing the core dependencies so that the `prepack` script can run
- Use `--allow-same-version` in `npm publish` in case the workflow is running for a second time after an issue in one of the steps (if the version has already been published, the workflow will fail in the `npm publish` step anyway).
It can be seen working at https://github.com/netlify/cli/runs/3103864820?check_suite_focus=true.
> chore: fix pre-release workflow

- src/utils/command.js
**- Summary**
fixes https://github.com/netlify/cli/issues/2400
This PR makes a temporary fix for the shorthand notation (`-o`) of the offline flag not working due to parsing flags through `minimist` instead of the oclif parser. 
The fix is temporary since the ideal solution using the oclif parser might require substantial refactoring.
- `npx ava -v -s` ran without errors.
- Tested a log statement in the `getConfig` method to see if the value for the `offline` parameter was `true` for both `--offline` and `-o` flags.
> fix: shorthand notation o for the offline flag fixes #2400

- src/commands/deploy.js
**- Summary**
When running the `deploy` command without the `--prod` flag, the CLI will display a message with a command that allows the user to take the deployment to production. This PR makes it so that said command preserves the `--build` flag if it was present in the original `deploy` command.
Closes #3008.
> fix: keep --build flag in deploy message suggestion

- src/utils/lm/scripts/fish.sh
**- Summary**
Whenever a new fish shell is spawned, the current git lm utility script appends the binary to the user `$fish_user_paths`, leading to the following:
```sh
> echo $fish_user_paths
/Users/jgantunes/.fzf/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin /Users/jgantunes/Library/Preferences/netlify/helper/bin …
```
> fix(fish): stop git lm utility script path clutter

- tests/serving-functions-go.test.js
- tests/serving-functions.test.js
**- Summary**
Follow up on https://github.com/netlify/cli/pull/3015
Adds more logs to print the CLI output when requests to `ntl dev` fail
Existing tests
🦁
> test(serving-functions): add more logs

- src/utils/init/plugins.js
Part of https://github.com/netlify/pod-workflow/issues/157
This updates the version of `plugins.json` to match the new URL format.
> fix: fix version of `plugins.json`

- src/utils/detect-server-settings.js
**- Summary**
This was missed in https://github.com/netlify/cli/pull/3071.
> fix: take internal functions directory into account when assigning functions server port

- src/commands/functions/create.js
**- Summary**
The `functions:create` command will print a log message for each file that was copied from the template. Some files will be deleted later in the process, like `package.json` and `package-lock.json`. This PR adjusts the log messages so that those files aren't logged in the first place.
> fix: omit deleted files from log message

- npm-shrinkwrap.json
- package.json
- src/utils/headers.js
- src/utils/headers.test.js
- src/utils/proxy.js
Part of https://github.com/netlify/build/issues/2890
This uses [`netlify-headers-parser`](https://github.com/netlify/netlify-headers-parser) inside Netlify CLI in order to:
- Prevent code duplication between `@netlify/config` and `netlify dev`
- Be consistent with how redirects are parsed in `netlify dev` (with `netlify-redirects-parser`)
- Isolate the headers parsing logic so it's easier to make it use the back-end parsing logic in the future
- Benefit from the several bug fixes and minor improvements added by `netlify-headers-parser`
I have updated the automated tests and also tested it manually.
> feat: use `netlify-headers-parser`

- src/utils/headers.js
- src/utils/proxy.js
- src/utils/rules-proxy.js
Fixes #1198
This adds support for headers set in `netlify.toml` in `netlify dev`.
> fix: support `netlify.toml` headers with `netlify dev`

- .github/workflows/benchmark.yml
- .github/workflows/main.yml
- .github/workflows/release-please.yml
- .github/workflows/verify-docs.yml
Reverts - https://github.com/netlify/cli/commit/9e7f41720b97a695b235b78e6a27e0a491d40a04 - ~~caching only seems to work with `package-lock.json` files and doesn't seem to support `npm-shrinkwrap` (see https://github.com/netlify/cli/runs/3471879986)~~ (EDIT: the path for the lockfile can be configured apparently - https://github.com/actions/setup-node/issues/302)
> chore(ci): fix don't cache npm cache dir between workflow execs

- src/commands/dev/index.js
**- Summary**
Fixes #3251.
On Windows, the `dev` command does not properly terminate the framework process on exit, and leaves them running even though `netlify-cli` has exited.
This is because `execa` defaults to `windowsHide: true`, which seems to interfere with terminating child processes: sindresorhus/execa#433.
Other projects have also encountered this issue with execa's defaults and Windows: snowpackjs/snowpack#1022, lerna/lerna#2946.
Let's set `windowsHide: false` so that the framework process will terminate properly on exit. 
Run `netlify dev` with this PR and attempt to exit on Windows (e.g. via Ctrl-C). No framework processes should be left running after exit.
🦓
> fix(command-dev): ensure no orphaned child process on Windows

- src/commands/addons/auth.js
- src/commands/addons/config.js
- src/commands/addons/create.js
- src/commands/addons/delete.js
**- Summary**
#3028 was too large for review and is being broken down.
This PR is a follow-up on #3247 and uses the separate logging and process control utilities created in it to remove the inherited ones.
This PR focuses specifically on the `src/commands/addons` folder.
`npx ava --verbose --serial` ran without any failing tests.
> refactor: replace inherited error and exit utils in command.addons

- src/commands/dev/exec.js
- src/commands/dev/index.js
- src/commands/open/admin.js
- src/commands/open/site.js
- src/commands/sites/create.js
- src/commands/sites/delete.js
**- Summary**
#3028 was too large for review and is being broken down.
This PR is a follow-up on #3247 and uses the separate logging and process control utilities created in it to remove the inherited ones.
This PR focuses specifically on the `dev`,`open`,`sites` folder in `src/commands`.
Utilities outside this folder have been changed as less as possible to avoid growing the diff size in a single PR.
> refactor: replace inherited log utils in src/command/(dev|sites|open)

- src/commands/build/index.js
- src/commands/env/import.js
- src/commands/link.js
- src/commands/lm/setup.js
- src/commands/unlink.js
**- Summary**
#3028 was too large for review and is being broken down.
This PR is a follow-up on #3247 and uses the separate logging and process control utilities created in it to remove the inherited ones.
This PR focuses specifically on the `build`, `env`, `lm` , `link`, `unlink` commands in `src`.
> refactor: replace inherited log, exit utils in commands.(build|env|lm|link|unlink)

- src/lib/http-agent.js
- src/lib/http-agent.test.js
- src/utils/command.js
**- Summary**
While working on #3382, @ehmicky suggested that we could break down the `getAgent` function in `src/lib/http-agent.js` into 2 different functions (one that only returns successful or error responses and another which handles logging and process control) to allow better testing.
Note: Tests for the http-proxy now use the core function `tryGetAgent` instead of the earlier `getAgent` function which has now been turned into a wrapper.
> refactor: split core function of getAgent for better testing

- src/utils/dev.js
- src/utils/dot-env.js
- src/utils/dot-env.test.js
**- Summary**
While working on #3382, @ehmicky suggested that we could break down the `loadDotEnvFiles` function in `src/utils/dot-env.js` into 2 different functions (one that only returns successful or error responses and another which handles logging) to allow better testing.
> refactor: split core function of loadDotEnvFiles for better testing

- tests/command.lm.test.js
- tests/utils/call-cli.js
Fixes #3573 
When executing the test with a `zsh` shell the formatting of the box was off, so that the regex matched a wrong string. Therefore the further execution of the test was not working. 
Updated the regular expression to match exactly the path regardless of what is between the word source and the absolute path.
> fixes the netlify lm:install tests for different shells (like zsh)

- src/lib/functions/registry.js
- src/lib/functions/server.js
The `netlify dev` command is showing a warning message when a Background Function is used and the `capabilities` object shows that the current plan doesn't support that feature. However, it's possible that the `capabilities` object is not populated due to the user being signed out or running the command using the `--offline` flag.
This PR addresses that by passing an `isConnected` flag to the functions registry, which infers whether the site is connected by looking at the `siteUrl` property. If that property is falsy, CLI won't show the warning because it can't know whether the user has a plan with access to the feature or not.
Closes https://github.com/netlify/pod-serverless/issues/31.
> fix: show Background Function plan warning only if site is connected

- src/utils/command.js
- tests/telemetry.test.js
At the moment, we send the [default `netlify/js-client`](https://github.com/netlify/js-client/blob/46becd9e829c60cac83828c7905674027d66d88d/src/index.js#L14) user-agent for every API request that's made from the CLI. This PR updates it so that the user-agent discloses both that it's a request from the CLI, what version it's on, what operating system and what version of Node.js. On my machine, this would be `netlify-cli/6.14.25 darwin-x64 node-v16.13.0`.
cc @netlify/data 
Closes #2804
---
> feat: send CLI version in all API requests

- package.json
From the discussion at https://github.com/netlify/netlify-headers-parser/pull/80#discussion_r755356450
Discussing with @lukasholzer and @JGAntunes we decided to drop support for Node 13, 15 and 14 below 14.14.0.
This will require a major release and editing our previous announcement.
---
> chore!: drop support for Node `13`, `14.0.0-14.13.1` and `15`

- .github/workflows/main.yml
When docs are being updated, our CI setup does not run automated tests since those are not needed then.
However, we also enforce automated tests in PRs as part of our required status checks using branch protection rules.
Unfortunately, branch protection rules do not allow for conditions such as "if only docs are being updated". Since we do want to keep those rules, then this PR makes our CI setup run automated tests even when only docs are being updated.
---
> fix: docs update and required status checks

- bin/run.cmd
remove the unnecessary file for the windows command as node generates on windows the binaries on their own. no need to ship anything
---
> chore: remove unnecessary windows cmd entry point

- tools/affected-test.js
> chore: fixes an issue on windows

- site/src/_layout.js
AFAICT, this is supposed to replace only the first instance. If so, using a string is enough and this fixes the missing escape:
* <https://regex101.com/r/3XSp31/1>
> fix(site): fix wrong regex

- src/lib/functions/config.js
Include `schedule` in the list of properties that is passed to zip-it-and-ship-it. This fixes an issue where schedules defined in `netlify.toml` are not picked up.
> fix: add `schedule` property to normalised config

- .github/workflows/benchmark.yml
- npm-shrinkwrap.json
- package.json
See https://github.com/netlify/js-client/pull/659
This fixes how we use Husky with its latest version.
---
> chore: fix Husky

- .github/workflows/benchmark.yml
See https://github.com/netlify/cli/pull/4041#discussion_r785051424
This fixes the GitHub action which checks for the npm package's published size, to exclude `devDependencies`.
cc @XhmikosR 
---
> chore: fix GitHub action checking for install size

- tools/e2e/run.js
- tools/e2e/setup.js
> chore: fixes an issue with the e2e tests

- src/lib/functions/config.js
Passes the `zipGo` configuration property to zip-it-and-ship-it during the `deploy` command.
Follow up to https://github.com/netlify/zip-it-and-ship-it/pull/955 and https://github.com/netlify/build/pull/4058.
> feat: pass `zipGo` property to ZISI

- tests/command.init.test.js
- tests/command.link.test.js
Disable flaky tests on windows:
These two where always failing and blocking 
https://github.com/netlify/cli/runs/4896037137?check_suite_focus=true
I curated a list of flaky tests and those two are failing more often
https://www.notion.so/netlify/Flaky-CLI-Test-1d125bd140da4d1dbdb05ca02113d46d (internal link)
> test: disable flaky tests on windows

- src/commands/functions/functions-invoke.js
- src/utils/functions/get-functions.js
- tests/command.functions.test.js
This PR fixes a bug discovered by @minivan, where our warning message was off when a toml-defined scheduled function was invoked with `functions:invoke`.
> fix: dont show warning message for toml-defined scheduled functions

- npm-shrinkwrap.json
- package.json
This PR broke the graphQL tests so reverting it.
It got merged since I messed up something with our branch protection.
> fix: revert "fix(deps): update dependency netlify-onegraph-internal to v0.0.18 (#4170)"

- src/commands/dev/dev.js
- src/commands/graph/graph-edit.js
- src/lib/one-graph/cli-client.js
- src/lib/one-graph/cli-netlify-graph.js
Fixes #4180 
Makes editing the Graph operations library file locally work while also sending updates to the ui to make the DX much smoother via file monitoring.
It also runs prettier (if available) on the output so the code conforms to the user's local expectations.
Shows a link when starting `netlify dev --graph` that takes the user to the graph editing UI (requested by @biilmann)
---
> feat: Show edit graph link on dev startup, send operations library edits to UI, and run prettier (if available) on code output

- npm-shrinkwrap.json
- package.json
- src/lib/one-graph/cli-netlify-graph.js
Fixes a bug where we send a SDL directive definition for `@netlify` to OneGraph. Normally this isn't a problem, but ocaml-graphql-server doesn't parse SDL, and declares it an invalid query. 
Also adds a quality-of-life improvement where we send you directly to the edit url for a graph session when running `graph:edit`
---
> fix: update dep and remove @netlify directive SDL definition in output

- src/lib/one-graph/cli-netlify-graph.js
Fixes `language` in `netlify.toml/graph` to be a scalar and not an array, which was causing the wrong language to be emitted for graph handlers
---
> fix: graph language

- src/commands/deploy/deploy.js
- src/lib/functions/config.js
- src/utils/deploy/deploy-site.js
- src/utils/deploy/hash-fns.js
zip-it-and-ship-it uses the `nodeVersion` configuration property to make certain decisions about the bundle (e.g. whether to use an ESM entrypoint or not). This PR reads the `AWS_LAMBDA_JS_RUNTIME` environment variable from the site settings and passes that along as the `nodeVersion` value.
This PR also sends the `zisi_detect_esm` and `zisi_pure_esm` feature flags to zip-it-and-ship-it.
> feat: pass `nodeVersion` and feature flags to zip-it-and-ship-it

- src/lib/build.js
Companion PR to https://github.com/netlify/netlify-plugin-nextjs/pull/1264, fixing https://github.com/netlify/netlify-plugin-nextjs/pull/1264.
Fixes a bug that causes an error when building a Next.js app in an Nx monorepo with the CLI and using the `cwd` option.
---
I wasn't sure how/where this would be tested, would appreciate any pointers there.
> fix: pass through cwd flag in getBuildOptions

- package.json
- src/lib/functions/synchronous.js
Wraps functions render error template block in try catch and returns the previous view should there be a problem getting the error template.
Part of https://github.com/netlify/pod-serverless/issues/78
---
> fix: fallback should there be an error getting the functions error page template

- src/lib/edge-functions/registry.js
Runs user-defined Edge Functions _before_ internal/framework-defined Edge Functions.
Closes https://github.com/netlify/pillar-runtime/issues/270.
> feat: change order of Edge Functions execution

- src/lib/edge-functions/proxy.js
- src/lib/edge-functions/registry.js
When a request matches an Edge Function for which there is a config declaration but no matching function file, we should show a warning message to assist developers with the process of creating a function.
Example:
> feat: warn about orphaned Edge Function declarations

- src/lib/functions/server.js
- tests/integration/200.command.dev.test.js
- tests/integration/300.command.dev.test.js
When using Netlify Dev with HTTPS, the `event.rawUrl` property in serverless functions incorrectly references the HTTP URL. This PR fixes that.
Closes https://github.com/netlify/pod-compute/issues/86
> fix: pass correct protocol to functions server

- src/lib/functions/netlify-function.js
The function URLs we display when the application starts needs to take into account whether HTTPS is configured.
> fix: use correct protocol when displaying function URL

- .github/workflows/release-please.yml
- package.json
Newer versions cannot parse versions/tags with major versions higher than 9.
googleapis/release-please#1451
It will take a little bit until this is solved, as after the linked PR, there has to be another PR updating release-please in the github action. That is why I think it is best to downgrade for now.
---
> chore: Downgrade release-please to make it work for now

- src/lib/functions/runtimes/rust/index.js
- tests/unit/lib/functions/runtimes/rust/index.test.js
`multiValueHeaders` was simply not forwarded from the response of the rust function
This is similar to #4618 but for rust.
---
> fix: correctly support multiValueHeaders in rust functions during development

- .github/workflows/release-please.yml
- renovate.json5
Reverts netlify/cli#4647
Also disable renovate for it for now.
Same as #4628, but now with renovate also disabled.
> chore(deps): downgrade googlecloudplatform/release-please-action action to v3.1.4

- tests/integration/620.serving-functions-rust.test.js
Refs #4625
This changes one test to delete the mocks after the dev server is closed. Before it was the other way around. This should hopefully fix some EBUSY errors in ci.
> chore: remove execa mock after dev server closed

- src/functions-templates/typescript/scheduled-function/{{name}}.ts
Without the async keyword, typescript instantly errors as the handler (according to the types
of `schedule()` ) needs to return a Promise.
I also tried deploying a function that is not async and lambda throws an error.
> fix: fix scheduled function template to use async

- src/lib/functions/netlify-function.js
- src/lib/functions/registry.js
- src/lib/functions/runtimes/js/builders/zisi.js
- tests/integration/330.serving-functions.test.js
- tests/unit/utils/functions/registry.test.js
Fixes #4454
Adds the files/globs from the `included_files` config option to the watcher.
This requires a new version of zisi with netlify/zip-it-and-ship-it#1098 , which is not released yet.
> fix: correctly watch function files specified in the config option `included_files`

- src/lib/edge-functions/deploy.js
- tests/integration/210.command.deploy.test.js
The paths we supply to the `files` hash needs to be in the unix format.
> fix: use correct paths when deploying edge functions on Windows

- npm-shrinkwrap.json
- package.json
In #4615 the `commander.js` function `conflicts()` is used. This functionality was added in `9.1.0` but our package json is set to `^9.0.0`
This pr updates the minimum `commander.js` version to 9.2.0, because this also includes a fix for `conflicts()`
https://github.com/tj/commander.js/blob/master/CHANGELOG.md#920-2022-04-15
Fixes #4747
> fix: update minimum required version of commander to 9.2.0

- .github/workflows/benchmark-post.yml
- .github/workflows/benchmark.yml
This enables the package-size to work also from forks. Currently
it does not work because the workflow gets only a readonly token
if started from a fork, hence the workflow cannot post the comment.
https://github.com/netlify/cli/runs/7194403058?check_suite_focus=true#step:6:27
By splitting the workflow, we run the calculation in a secure environment with
only the readonly token and then run the second workflow after the first
one is finished. The second workflow then has write access and can
post the comment
taken from https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
This upload of a workflow artifact will not count against the storage limit of the netlify github-account, because this is a public repository. …
> chore: split package size workflow to make it work for PRs from forks

- docs/commands/dev.md
- src/commands/dev/dev.js
- src/lib/one-graph/cli-client.js
Allow `netlify dev --graph --sessionId=...` to connect to a cloud session.
---
> feat: connect to a cloud session

- src/commands/sites/sites-create-template.js
- src/utils/sites/utils.js
- tests/integration/140.command.sites.test.js
Fixes #4777 
When a user uses the CLI for generating a site with a template, we want to make sure only the appropriate repos show up for us. Right now that's all public, non-archived projects. The default limit is 30, so we also doubled the site request for now.
---
I wasn't quite sure if I should make a separate test for validating that the other repository do not show up but I modified the example at least so it should still pass other tests.
> fix: Update getTemplatesFromGitHub to retrieve more repositories

- docs/commands/dev.md
- package.json
- src/commands/dev/dev.js
In raising issue #4819, @eduardoboucas noticed there's a typo in both the documentation and CLI command help. This PR fixes this.
---
> chore: fix country command + docs typo

- package.json
- src/commands/graph/graph-pull.js
Fixes passing the graphJWT to a place where it was missing
---
> fix(graph): use the JWT correctly in `refetchAndGenerateFromOneGraph`

- src/functions-templates/typescript/abtest/{{name}}.ts
- src/functions-templates/typescript/geolocation/{{name}}.ts
- src/functions-templates/typescript/json/{{name}}.ts
- src/functions-templates/typescript/log/{{name}}.ts
- src/functions-templates/typescript/set-cookies/{{name}}.ts
- src/functions-templates/typescript/set-req-header/{{name}}.ts
- src/functions-templates/typescript/set-res-header/{{name}}.ts
- src/functions-templates/typescript/transform-response/{{name}}.ts
Replaces `netlify:edge` with `https://edge.netlify.com` in Edge Functions templates.
Part of https://github.com/netlify/pillar-runtime/issues/322.
> feat: deprecate `netlify:edge` in function templates

- src/utils/deploy/upload-files.js
- tests/unit/utils/deploy/upload-files.test.js
Adds a retry count parameter to the `uploadDeployFunction` API call on retries.
Part of https://github.com/netlify/pod-compute/issues/140.
> feat: add retry count parameter to function uploads

- src/lib/edge-functions/deploy.js
- src/utils/deploy/deploy-site.js
- tests/integration/210.command.deploy.test.js
- tests/integration/utils/site-builder.js
Fixes netlify/netlify-plugin-nextjs#1400
Fixes netlify/pod-compute#150
The edge function dist path was incorrect when a custom working directory `--cwd` was supplied through the cli options. We were looking at `/repo/path/.netlify/...` instead of `/repo/path/cwd/.netlify/...`
Added a new test (which failed without the fix) and adjusted the other test to be more clear what failed. Just getting the uppercase/lowercase error, usually made me think this is some unimportant server/proxy conversation, but it actually means the edge function is not being loaded. Should be clearer now.
> fix: correctly create edge function directory when running in custom cwd

- src/lib/edge-functions/editor-helper.js
Fixes #4862 
Added a check for test environment inside the `promptEditorHelper` function. This decision was made based upon the thought that we could either change the `env.TERM_PROGRAM` in all tests, or check if the `env.NODE_ENV` was `test`.
---
> fix: prevent promptEditorHelper to run if running tests in vscode

- src/lib/edge-functions/proxy.js
- tests/unit/lib/edge-functions/create-site-info-header.test.js
As per request, I moved some logic to its own function and added a unit test.
I'd love to get input! Also on the style that I did it in. For example, would it have been better in its own file? (if so, how do we want to structure it? 🤔) and what do we think of the naming. (is it creating a header? or would it be better to name it `createSiteInfoBase64`?
---
> test: move site info header creation to function and write unit test for function

- npm-shrinkwrap.json
I just ran `npm dedupe` which deduplicates the dependencies, so they are not installed multiple times.
Most of the changes in the shrinkwrap file are encryption upgrade from sha1 to sha512
> fix: deduplicate shrinkwrap

- npm-shrinkwrap.json
- package.json
- src/lib/one-graph/cli-client.js
- src/lib/one-graph/cli-netlify-graph.js
Fixes an issue where session metadata would get too big and would fail to update.
Also warns when trying to generate code for Graph when missing config rather than exiting.
---
> fix(graph): don't attach codegen to session metadata, and don't die when missing toml config

- src/lib/edge-functions/registry.js
- tests/integration/100.command.dev.test.js
As discussed in Slack, this environment variable is used in plugins to differentiate between dev and prod.
> fix: supply NETLIFY_DEV to Deno

- .github/workflows/pre-release.yml
This PR fixes the pre-release workflow in CI by installing dependencies for the site, but not building the site. A new site build isn't necessary for a prerelease version, and skipping that step allows the workflow to succeed in CI. 
[Relevant Slack thread](https://netlify.slack.com/archives/CN8S7NB29/p1660759755607129)
---
> fix(ci): do not build site during prerelease workflow

- src/commands/dev/dev.js
- tests/integration/0.command.dev.test.js
We automatically add the `.netlify` directory to `.gitignore` as part of the `link` and `init` commands. This PR extends that behaviour to `dev`.
> feat: add `.netlify` to `.gitignore` in Netlify Dev

- src/commands/init/init.js
- src/commands/link/link.js
- src/commands/sites/sites-create.js
- src/utils/init/config-github.js
- src/utils/init/plugins.js
- src/utils/init/utils.js
- tests/integration/420.command.init.test.js
This PR contains a few changes to streamline the `init` and `dev` commands:
- Remove message in `link` command pointing to the location of the `state.json` file: https://github.com/netlify/cli/commit/0322ed5949d3807d5c2a68e7e298b5075f458703
- Automatically install recommended plugins in `init` command: https://github.com/netlify/cli/commit/8b4d91c9383de8b906bb2cbbe9ad37e1e94c1139
- Stop prompting users for the functions directory and use default instead: https://github.com/netlify/cli/commit/efc45b5f32582826cdf99bf463b2eb7f74017fcf
- Remove location of `state.json` in `link` confirmation message: https://github.com/netlify/cli/commit/62c566cf5bb8e33a63c7b8e055753ef727c55b24
- Add blank line around prompts: https://github.com/netlify/cli/commit/8d317004d963fea7d195cc06b4d873b91575d175
- …
> feat: simplify `init` and `link` flows

- src/lib/one-graph/cli-netlify-graph.js
- Fixes an issue that can happen when a `netlify.toml` doesn't have any `[graph]` configuration
Previously we could generate:
```toml
[some_config]
foo
codeGenerator = "foo"
```
Now we generate
```toml
[some_config]
foo
[graph]
codeGenerator = "foo"
```
---
> fix: graph code generator TOML injection

- src/commands/build/build.js
- src/commands/deploy/deploy.js
- src/lib/build.js
- src/utils/detect-server-settings.js
- src/utils/types.d.ts
- tests/integration/110.command.build.test.js
This reverts commit c85efc45bd46ee4038fbe44f64fe99ce0b25eb7b. (PR: https://github.com/netlify/cli/pull/5029) which added framework detection on netlify build and netlify deploy --build
Due to a number of issues, I'm reverting this feature until some bugs have been ironed out and more thoroughly tested. 
Related:
https://github.com/netlify/cli/issues/5080
https://github.com/netlify/cli/issues/5036
https://github.com/netlify/cli/issues/5082
> feat: Revert run framework detection and run plugins on netlify build

- renovate.json5
Before I update these grouping rules in the shared config, I wanted to test them here. In the [shared config](https://github.com/netlify/renovate-config/blob/main/shared.json#L19-L24) I think they are wrong as `matchSourceUrlPrefixes` and `matchPackageNames` are combined with AND, which doesn't match anything.
Let's see if this does fix the grouping.
---
> chore: fix grouping of renovate updates

- docs/commands/env.md
- src/commands/env/env-get.cjs
- src/commands/env/env-list.cjs
- src/commands/env/env-set.cjs
- src/utils/env/index.cjs
- tests/integration/650.command.envelope.test.cjs
- tests/unit/utils/env/index.test.cjs
This PR changes the post-processing flag from snake_case to kebab-case to match the convention of deploy context values (e.g. `branch-deploy` and `deploy-preview`). Our API supports both snake and kebab, but moving them to kebab in our CLI will make them more consistent when showing help commands like `netlify env:list --help`. 
Changes to open-api forthcoming. 
https://github.com/netlify/pillar-workflow/issues/808
---
> chore: kebab-case post-processing flag

- src/commands/dev/dev.cjs
This PR prints a message for sites that are using Envelope during `netlify dev` that environment variable values are being used for all scopes. This local behavior is slightly different than what occurs on Netlify, as env vars can be scoped to e.g. builds _or_ functions. Locally, this scoping doesn't happen -- everything is available in the same `process.env`. This log hopefully brings attention to that difference! 
Fixes https://github.com/netlify/pillar-workflow/issues/812
---
> chore: print env var scope during ntl dev

- tests/integration/650.command.envelope.test.cjs
Fixes [this prod test](https://github.com/netlify/cli/actions/runs/3338783978/jobs/5526895518), which I believe to have been broken due to [this open-api change](https://github.com/netlify/open-api/pull/403). 
---
> fix: fix one more instance of post_processing in broken test

- package.json
- src/lib/geo-location.cjs
- tests/unit/lib/geo-location.test.cjs
Adds missing mock geo data for local development. This can be merged before https://github.com/netlify/pod-ecosystem-frameworks/issues/305 is completed.
Fixes #5232
Relates to https://github.com/netlify/pod-ecosystem-frameworks/issues/305
---
> fix: added missing mock geo data

- src/lib/functions/server.mjs
- tests/integration/400.command.dev.test.cjs
if a request goes through an edge function the `content-length` header will be removed and instead the `transfer-enconding` is set to chunked. Our detection in the functions (non-edge) server was detecting these passthrough requests as requests without body, because of the missing `content-length`. `content-length` should be ignored anyways when `transfer-encoding` is used according to [the HTTP/1.1 spec](https://httpwg.org/specs/rfc9112.html#rfc.section.6.1).
Fixes #5030
This also changes `request.get(...)` and `request.headers[...]` to `request.header(...)` for readability.
> fix: detect requests without body correctly

- src/lib/edge-functions/registry.cjs
In certain situations, CLI is calling Edge Bundler's `generateManifest` function with functions that don't have a `path` or a `pattern` properties, which violates the expected type. This is causing a fatal error when running `netlify dev`.
This PR fixes that by discarding any invalid declarations.
> fix: discard edge function declarations without a path or pattern

- src/lib/edge-functions/internal.cjs
- tests/integration/100.command.dev.test.cjs
Currently, when CLI doesn't find a valid `manifest.json` file in the internal edge functions directory, it doesn't even look for edge functions in that directory. This means that declaring an internal edge function using in-source configuration without an accompanying manifest file doesn't work.
This PR addresses that by ensuring we always look for functions in that directory, regardless of whether or not there's a manifest with declarations.
> fix: always look for internal edge functions

- src/lib/edge-functions/internal.mjs
- src/lib/edge-functions/proxy.mjs
- tests/integration/100.command.dev.test.cjs
Should fix an issue where having any internal functions with in-source-config, but no other edge functions, would prevent the proxy from running the internal EF.
---
> fix: allow for in-source-config internal edge functions in proxy

- src/commands/deploy/deploy.mjs
- src/lib/build.mjs
- src/lib/edge-functions/consts.mjs
We have two different places where we need to send edge functions feature flags to Netlify Build. This PR centralises them.
> fix: centralize edge functions feature flags

- src/functions-templates/typescript/geolocation/{{name}}.ts
- src/functions-templates/typescript/json/{{name}}.ts
As per https://github.com/netlify/edge-functions-bootstrap/pull/142#issuecomment-1368897194, let's change the ef template code to use `Response.json` instead of the soon-to-be-deprecated `context.json`.
> feat(ef templates): replace context.json with Response.json

- src/lib/edge-functions/headers.mjs
- src/lib/edge-functions/proxy.mjs
- src/utils/proxy.mjs
This PR addresses an issue where enabling HTTPS may cause edge functions that make passthrough calls to fail due to untrusted certificates.
Rather than running the Deno server on HTTPS with the same certificate provided to the Netlify CLI, we'll run the Deno server on HTTP. To make passthrough calls work, we'll start a secondary CLI server on HTTP and use that for passthrough calls.
> fix: ensure edge functions work with HTTPS mode

- src/lib/functions/server.mjs
- src/lib/functions/synchronous.mjs
When we finish processing a serverless function and transfer any header it sets into the final response, we're doing [a `setHeader call`](https://github.com/netlify/cli/blob/main/src/lib/functions/synchronous.mjs#L15) that may throw. When that happens, the entire app crashes.
This PR addresses that by gracefully handling the error, showing a log in the terminal and displaying the function error page.
> fix: gracefully handle errors when setting headers

- src/utils/proxy.mjs
- src/utils/redirects.mjs
- src/utils/sign-redirect.mjs
- tests/integration/0.command.dev.test.cjs
- tests/integration/utils/external-server.cjs
Adds support for [signed redirects](https://docs.netlify.com/routing/redirects/rewrites-proxies/#signed-proxy-redirects) to the local development flow.
> feat: add support for signed redirects

- src/utils/proxy.mjs
- tests/integration/0.command.dev.test.cjs
Follow-up to #5414. The `signed` property holds the name of the environment variable that holds the secret for signing redirects. It does not hold the secret itself.
> fix: sign redirect with secret from env var

- src/commands/dev/dev.mjs
- src/utils/env/index.mjs
- tests/integration/100.command.dev.test.cjs
- tests/integration/utils/external-server-cli.cjs
- tests/integration/utils/external-server.cjs
https://github.com/netlify/cli/pull/5338 has changed the way the `NETLIFY_DEV` environment variable is set. Rather than mutating `process.env` immediately, we set a variable in the `env` object with the type `internal`, which is processed as a type of environment variable that can't be overridden.
Unfortunately, this wasn't added to the Envelope methods, and so the variable was being removed for sites with Envelope enabled.
This PR addresses that and adds some tests (to both legacy and new environment variable systems) to ensure we don't introduce this regression again.
> fix: load internal environment variables in Envelope

- src/utils/deploy/util.mjs
For deploy that fails while going live, we're currently printing a very non-explanatory error message - although we already might have a good one in `deploy.error_message`! This PR makes it so that that message is printed, if it exists.
---
> fix: print deploy error_message, if exists

- src/lib/edge-functions/registry.mjs
- tests/integration/100.command.dev.test.cjs
Fixes an issue where an error is thrown for edge functions defining a `path` property with multiple values via in-source configuration.
> fix: support multiple path values in edge functions config

- src/utils/deploy/hash-fns.mjs
Work for https://github.com/netlify/pod-compute/issues/350
Making sure that the generator field is passed along to the functions_config field we send to bitballoon.
---
> feat: add generator to functions config on deploy

- src/utils/telemetry/telemetry.mjs
Adds the Node.js version and the CLI version to telemetry.
> chore: add versions to telemetry

- src/lib/edge-functions/registry.mjs
- tests/integration/commands/dev/edge-functions.test.ts
- tests/integration/commands/dev/scheduled-functions.test.ts
- tests/integration/utils/dev-server.cjs
- tests/integration/utils/site-builder.cjs
The problem was that when the handling of internal and user functions was split, the detection for added/deleted function broke. All edge functions were always removed on change, because when detecting internal functions, the user functions were marked as deleted, and vice versa.
Ref https://github.com/netlify/pillar-support/issues/379
> fix: correctly reload edge functions on change

- src/lib/edge-functions/bootstrap.mjs
- tests/integration/100.command.dev.test.cjs
Updates the edge functions bootstrap to the latest version. Also tests the new `Netlify.env` object in an existing test.
> feat: update edge functions bootstrap

- src/lib/edge-functions/proxy.mjs
- tests/integration/200.command.dev.test.cjs
Sets the `Host` header to the passthrough URL in edge functions, so that `req.url` contains a valid URL when running the CLI on HTTPS.
> fix: set Host header on edge functions in HTTPS

- src/commands/deploy/deploy.mjs
Adds a direct link to the function logs page in the UI to the output of the `deploy` command.
Closes https://github.com/netlify/pod-dev-foundations/issues/290.
> feat: show function logs URL in `deploy` command

- src/utils/proxy.mjs
- tests/integration/100.command.dev.test.cjs
Fixes https://github.com/netlify/pod-dev-foundations/issues/536
---
> EF: Don't crash CLI when uncompressed request throws uncaught exception 

- src/utils/proxy.mjs
- tests/integration/100.command.dev.test.cjs
Currently, we're returning a 200 status code for the error page. This PR changes that to a 500.
> fix: ef error page should have 500 status code

- src/lib/functions/synchronous.mjs
- tests/integration/__fixtures__/dev-server-with-v2-functions/functions/uncaught-exception.mjs
- tests/integration/commands/dev/v2-api.test.ts
Fixes https://github.com/netlify/cli/issues/5839. Turns out we were showing the error screen already, and I didn't look close enough. This PR adds a test for that.
What we were missing though is a `text/html` content-type. This PR adds that.
---
> fix: add test for v2 error screen with text/html content-type

- src/lib/edge-functions/registry.mjs
In Local Dev, when there is no `netlify.toml` (e.g. because in-source-config is being used), `this.#configPath` was undefined. This caused the config file watcher to block indefinitely, so we never got to register the second watcher. This breaks automatic file reloading.
This PR fixes that by skipping the config watcher, if there is no config file. Ideally, we'd have both watchers and chokidar didn't block, so we'd pick up when the config file is added. Let's do that in a follow-up though.
> fix: dont block watching when netlify.toml doesnt exist

- src/utils/detect-server-settings.mjs
The framework object changed quite a while back but it got never fixed here:
This results in settings mismatch errors:
---
> fix: framework name in reporting

- src/lib/edge-functions/bootstrap.mjs
- src/lib/edge-functions/headers.mjs
- src/lib/edge-functions/proxy.mjs
- tests/integration/100.command.dev.test.cjs
Updates the edge functions bootstrap to the latest version and exposes `context.deploy` to Netlify Dev.
> feat: add `context.deploy` to edge functions context

- src/lib/functions/netlify-function.mjs
- src/lib/functions/registry.mjs
- src/lib/functions/runtimes/js/worker.mjs
The v2 API for functions requires Node 18 or greater, since it uses built-ins like `Request` and `Response`. If people try to use a function with an older version of Node, it will fail and they might be confused as to why.
In this PR we check for that scenario specifically and show a friendly error message. It also tidies up the logic for reloading functions. Finally, it ensures that if there was a build error in the function, it will be shown in the Netlify-branded error page when the function is accessed.
> feat: error when V2 functions are used with Node <18

- package-lock.json
- package.json
- src/lib/build.mjs
- src/utils/run-build.mjs
Fixes #5923. 
We had an issue where Deno cached an old version of edge-functions-bootstrap locally. On the next run, Deno re-fetched some of the assets but not others. Since it assumes URLs to be immutable, this shouldn't have made a difference - but because we were using the `https://edge.netlify.com` endpoint to parse Edge Functions config, the contents changed. This broke some customers trying to deploy edge functions locally. I have a hunch that this only affected some versions of Deno and not others.
Anyways, this PR fixes the issue by injecting a deploy-scoped Bootstrap URL into netlify/build (and by extension, into netlify/edge-bundler). Deploy-scoped URLs are immutable, so they should fix this bug.
---
For us to review and ship your PR …
> fix: always fetch immutable ef bootstrap version

- src/commands/base-command.mjs
- src/utils/run-build.mjs
Let the `--cwd` option override the default set working directory for execution and picking up files.
This restores in monorepos the previous default behavior of `cd <dir>` into a directory.
With that the execution root is not the jsWorkspace root.
Tested with the `next-runtime` monorepo by running:
```bash
ntl dev --cwd demos/default
ntl deploy --build --cwd demos/default
```
see deployed site: 
https://64ddf2008d235c6837b459e8--lukas-next-runtime-demos-default.netlify.app/
---
> feat: let the --cwd option override the monorepo execution directory

- README.md
- docs/README.md
- docs/commands/index.md
- docs/commands/lm.md
- site/src/_app.js
- src/commands/lm/lm-info.mjs
- src/commands/lm/lm-install.mjs
- src/commands/lm/lm-setup.mjs
- src/commands/lm/lm.mjs
- tests/integration/commands/help/__snapshots__/help.test.ts.snap
The Large Media feature was deprecated on September 1st, 2023 and will become unavailable in a future update. [Learn more and discover alternative solutions](https://answers.netlify.com/t/large-media-feature-deprecated-but-not-removed/100804)
As a result, we'll hide the `lm` command from the CLI. It will keep working, but we recommend against setting up Large Media on new sites.
---
> chore: deprecate `lm` command

- src/commands/lm/lm-setup.mjs
- tests/integration/commands/lm/lm.test.ts
Follow-up to https://github.com/netlify/cli/pull/5975. It broke the `lm:setup` test, which is currently blocking `main`. Unsure why it didn't break in the PR's test run 🤔 
---
> fix: make lm:setup test pass

- src/commands/lm/lm-setup.mjs
Fixes an issue where the confirmation prompt introduced in #5975 was blocking invocations of `lm:setup`, which would be a breaking change.
---
> chore: remove prompt at the beginning of lm:setup

- src/utils/proxy.mjs
- tests/integration/__fixtures__/dev-server-with-edge-functions/netlify/edge-functions/uncaught-exception.ts
- tests/integration/commands/dev/edge-functions.test.ts
Right now, if an edge function throws an unhandled exception, the CLI will crash with a cryptic error message:
```
SyntaxError: Unexpected token  in JSON at position 0
at JSON.parse (<anonymous>)
at formatEdgeFunctionError (file:///Users/eduardoboucas/Sites/netlify/cli/src/utils/proxy.mjs:65:12)
at IncomingMessage.onEnd (file:///Users/eduardoboucas/Sites/netlify/cli/src/utils/proxy.mjs:548:31)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
This is because the edge function is sending a compressed response which the CLI needs to decompress. We do have some logic for checking whether the body needs to be decompressed, which we've added in https://github.com/netlify/cli/pull/5837, but we're reading the `accept-encoding` header from the incoming request, when we …
> fix: decompress body from edge functions errors

- src/utils/deploy/hash-fns.mjs
- src/utils/deploy/upload-files.mjs
- tests/integration/210.command.deploy.test.cjs
We've added an `invocationMode` property to functions in https://github.com/netlify/zip-it-and-ship-it/pull/1421, but we've never added it to the API call to [the `uploadDeployFunction` endpoint](https://open-api.netlify.com/#tag/function/operation/uploadDeployFunction) made from the CLI.
This PR addresses that.
> fix: set `invocationMode` on deployed functions

- src/lib/edge-functions/bootstrap.mjs
- tests/integration/200.command.dev.test.cjs
Updates the version of the edge functions bootstrap. Also updates a test to ensure that edge functions can make `fetch()` calls to the incoming URL even when the CLI is running on HTTPS.
Part of https://github.com/netlify/pod-dev-foundations/issues/590.
> fix(deps): update version of edge functions bootstrap

- src/commands/functions/functions-serve.mjs
- src/utils/proxy.mjs
While testing around Go functions, I noticed that `netlify functions:serve` doesn't announce the port it's listening on. This PR adds the same banner that we're showing for `netlify dev` and `netlify serve`.
> feat: functions:serve should announce port via banner

- src/utils/deploy/hash-fns.mjs
When uploading functions from `netlify deploy`, we need to ensure that we're passing the right `runtime` parameter to our API. In open-api, we read the `runtimeVersion` field from the manifest, and if it exists we use it instead of the `runtime` field that contains the language. We should have the same behaviour in the CLI, so that the `runtimeVersion` field is respected.
Part of https://github.com/netlify/pod-dev-foundations/issues/581
---
> Pass functions manifest `runtimeVersion` to api when uploading functions

- src/lib/build.mjs
As explained in https://github.com/netlify/pod-dev-foundations/issues/581#issuecomment-1731022753, enabling the `zisi_golang_use_al2` flag will lead to failures in versions of the CLI that don't have the https://github.com/netlify/cli/pull/6020 patch. That means we need to decouple the rollout of `zisi_golang_use_al2` in buildbot (where @netlify/build is always up-to-date) from the rollout in the CLI, where the flag also affects versions with broken behaviour. That's why this PR adds a second flag, which we can use to control the CLI rollout independently.
Part of https://github.com/netlify/pod-dev-foundations/issues/581
---
> fix: add flag that allows us to control al2 rollout independent of buildbot

- src/utils/deploy/hash-fns.mjs
- tests/integration/210.command.deploy.test.cjs
We weren't including `routes` in the `functions_config` parameter we're sending to the API, so custom v2 routes didn't work properly. This PR fixes that.
> fix: include `routes` in functions config on deploy

- src/lib/functions/form-submissions-handler.mjs
- tests/integration/commands/dev/v2-api.test.ts
Part of https://github.com/netlify/pod-dev-foundations/issues/578. See title.
> fix: don't run form submission logic on paths matching function

- src/lib/functions/registry.mjs
- src/utils/proxy.mjs
In recent changes to how we match URL paths for functions, we started relying solely on `FunctionsRegistry.getFunctionForURLPath`, even for matching paths for the default functions URL (i.e. `/.netlify/functions`).
The problem is that this method is returning `undefined` if there is no matching function, but we also need to know when a URL is definitely for a function (i.e. starts with `/.netlify/functions`) regardless of whether an actual function for that name exists.
This is important so that we handle 404s in the functions server, letting us return the right status code and message. This PR fixes that.
> fix: fix function URL matching

- src/lib/edge-functions/consts.mjs
- src/lib/edge-functions/proxy.mjs
- src/lib/edge-functions/registry.mjs
Show warning when edge functions import npm modules that contain extraneous files.
> feat: show warning for npm modules with extraneous files

- README.md
- docs/README.md
- docs/commands/build.md
- docs/commands/completion.md
- docs/commands/index.md
- docs/commands/serve.md
- src/commands/build/build.mjs
- src/commands/completion/completion.mjs
- src/commands/recipes/recipes-list.mjs
- src/commands/recipes/recipes.mjs
- src/commands/serve/serve.mjs
Fixes #3661
These commands/features are no longer in beta and the documentation needs to be updated to reflect that
> fix: remove beta tag from commands that are no longer in beta

- site/src/register-addon-thanks.md
- site/src/register-addon.md
Fixes [#CT-298](https://linear.app/netlify/issue/CT-298/add-deprecation-notice-to-the-register-add-on-docs-page) by adding a deprecation note to the "register add ons" page, as [discussed on Slack](https://netlify.slack.com/archives/C043UGRAC3F/p1699976455996849?thread_ts=1699271734.943139&cid=C043UGRAC3F). It uses the same language we used on the [`addons` command](https://deploy-preview-6155--cli.netlify.com/commands/addons) page.
I also removed the broken link to https://github.com/netlify/addon-integration-examples/ from the success page.
> docs: adds deprecation notice to register add on page

- src/lib/images/proxy.mjs
- tests/unit/lib/images/proxy.test.mjs
Fixes [ADN-57](https://linear.app/netlify/issue/ADN-57/local-image-server-generating-incorrect-image-fit)
For the `fit` parameter to render correctly with IPX, the width and height parameters must use `s`.
With this PR, `/fit_cover,w_800,h_600/seed.jpg` becomes `/fit_cover,s_800x600/seed.jpg`
- [X ] Open a [bug/issue](https://github.com/netlify/cli/issues/new/choose) before writing your code 🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
- [X ] Read the [contribution guidelines](../CONTRIBUTING.md) 📖. This …
> fix: [image cdn] Use s resize

- package-lock.json
- package.json
- src/lib/blobs/blobs.mts
- src/lib/functions/server.mts
- src/utils/get-global-config.mts
- src/utils/live-tunnel.mts
- Uses a default site ID when running Netlify Dev with an unlinked site. This makes it possible to use Blobs even if the site is not linked.
- When the first request is made to the local blobs server, a message is printed to the console telling people that Blobs is running in sandbox mode for local development, including a link to the docs
- Updates `@netlify/blobs` to the latest version
> feat: miscellaneous Blobs improvements

- src/commands/status/status.mts
Removes a second run of `getSite` from the `netlify status` command as we already have that data when `base-command` runs first.
This makes this command a bit faster at the cost of losing errors based on error code (401, 404) but I think this a reasonable tradeoff.
|  Before |  After  |
|---|---|
| Between 3.6 and 5.1 seconds <img width="623" alt="Screenshot 2023-11-16 at 5 22 42 PM" src="https://github.com/netlify/cli/assets/4700602/ef2d1497-067f-44fa-92c2-387a20c243cb"> |  Between 3.2 and 3.7 seconds <img width="605" alt="Screenshot 2023-11-16 at 5 23 39 PM" src="https://github.com/netlify/cli/assets/4700602/f16e6d0c-fa00-4ee8-b7f3-b1a7d848a16f"> |
---
passes our …
> feat: speed up `netlify status` by removing extra api call

- src/lib/edge-functions/registry.ts
We're currently showing this warning when there's dependency graph:
https://github.com/netlify/cli/blob/dbd6066a69bc273846c640b8e5ca090695bde3c9/src/lib/edge-functions/registry.ts#L411
One case where there's no dependency graph is when there's no functions:
https://github.com/netlify/cli/blob/dbd6066a69bc273846c640b8e5ca090695bde3c9/src/lib/edge-functions/registry.ts#L467-L473
We shouldn't be showing the warning in that case. This PR adds an early-return that does that.
> fix: don't show warning when there are no ef

- src/lib/functions/registry.ts
Contains two follow-ups to https://github.com/netlify/cli/pull/6076, that were discovered while working on the Astro adapter.
1. `ntl serve` should pick up `routes` from `manifest.json`
2. `__netlify-entrypoint.js` is the wrong extension, it needs to be `.mjs` - see https://github.com/netlify/zip-it-and-ship-it/blame/f5fb309109408d25544fe34bdee77f917ff679e7/src/runtimes/node/utils/entry_file.ts#L150
> fix: `ntl serve` for v2 functions, follow-ups

- src/lib/edge-functions/bootstrap.ts
- src/lib/edge-functions/proxy.ts
- tests/integration/__fixtures__/dev-server-with-edge-functions/netlify/edge-functions/echo-env.ts
- tests/integration/commands/dev/dev-miscellaneous.test.js
- tests/integration/commands/dev/edge-functions.test.ts
Sets the `URL`, `SITE_ID`, and `SITE_NAME` environment variables when running edge functions locally.
Part of https://linear.app/netlify/issue/COM-149/edge-functions-are-missing-the-url-environment-variable.
> feat: set Netlify environment variables in edge functions

- src/lib/functions/netlify-function.ts
- src/lib/functions/runtimes/js/builders/zisi.ts
- tests/integration/commands/deploy/deploy.test.js
- tests/integration/commands/functions-with-args/functions-with-args.test.js
When we did the mass `.m(ts|js)` -> `.(js|ts)` extension change these got caught up. This effected the function transpillation process as it was parsing the wrong file types, creating a nested `functions-serve` directory which borked the gatsby plugin
---
> fix: use correct file extensions for transpilation

- src/commands/base-command.ts
- src/commands/dev/dev.ts
- src/commands/link/link.ts
- src/commands/serve/serve.ts
- src/commands/types.d.ts
- src/utils/command-helpers.ts
- src/utils/detect-server-settings.ts
- src/utils/init/utils.ts
To not have my change and the types refactoring in one PR this is just the PR for the types refactorings.
The actual change will come in a follow-up.
---
> chore: enhance types for base-command.ts

- tests/integration/commands/functions-with-args/functions-with-args.test.js
This is an effort to run the proper github actions on what was originally this PR: https://github.com/netlify/cli/pull/6245
> refactor: replace got with node-fetch on functions-with-args.test.js 

- src/commands/functions/functions-create.ts
- src/commands/lm/lm-setup.ts
- src/commands/main.ts
- src/commands/sites/sites-create-template.ts
- src/lib/exec-fetcher.ts
- src/lib/functions/local-proxy.ts
- src/lib/functions/runtimes/go/index.ts
- src/lib/functions/runtimes/js/builders/netlify-lambda.ts
- src/lib/functions/runtimes/rust/index.ts
- src/utils/banner.ts
- src/utils/build-info.ts
- src/utils/execa.ts
- src/utils/feature-flags.ts
- src/utils/init/utils.ts
- src/utils/live-tunnel.ts
- src/utils/lm/requirements.ts
- src/utils/sites/utils.ts
- src/utils/telemetry/report-error.ts
- src/utils/telemetry/telemetry.ts
This is a prerequisite before performing the actual change
---
> refactor: refactor typescript types from build-info and related parts

- package-lock.json
- package.json
- tests/integration/commands/addons/addons.test.js
- tests/integration/commands/build/build.test.js
- tests/integration/commands/dev/dev.geo.test.js
- tests/integration/commands/dev/images.test.js
- tests/integration/commands/env/env.test.js
- tests/integration/commands/envelope/envelope.test.js
- tests/integration/commands/init/init.test.js
- tests/integration/commands/link/link.test.ts
- tests/integration/commands/recipes/recipes.test.js
- tests/integration/utils/site-builder.ts
- tests/unit/utils/functions/get-functions.test.js
Lots of our tests use `withSiteBuilder`. I noticed that on Windows, we're seeing a lot of "Resource Busy or locked" exceptions when the site builder tries to clean up the directory it created. The resources are "busy", because we re-used the same sitename between a lot of our tests, so they ended up using the same directories - possibly a race condition. I'm assuming this comes from copy&paste.
This PR adds a new signature to `withSiteBuilder` that infers the site name based on the test name. Since we always adapt test names, this should work way better! Some of the usage i've already transitioned. To encourage folks to transition the rest as well, i've marked the old signature as deprecated.
> chore: site builder should infer directory name from tests

- src/lib/functions/server.ts
- tests/integration/commands/dev/dev-miscellaneous.test.js
This was updated on the CDN but not on the CLI. From the new docs: https://docs.netlify.com/functions/functions-and-identity/
> fix: include identity context data under custom netlify client context

- src/lib/blobs/blobs.ts
- src/lib/functions/server.ts
We want to support Blobs in Netlify Dev even if the site is not linked — this was supposed to be addressed by https://github.com/netlify/cli/pull/6176, but it didn't work properly (I've added more context in a comment). This PR fixes that.
Closes https://linear.app/netlify/issue/COM-211/blobs-possibly-not-working-in-framework-generated-functions.
> fix: support Blobs in unlinked sites

- src/lib/functions/server.ts
- tests/integration/commands/dev/dev-miscellaneous.test.js
Follow up to https://github.com/netlify/cli/pull/6277
The JWT decoding step can fail, and I've mistakenly took it out of the try block on the last PR. This fixes that.
> fix: decode identity jwt inside try block

- src/functions-templates/rust/hello-world/src/main.rs
Fixes [CT-459](https://linear.app/netlify/issue/CT-459/update-rust-template-in-cli)
Without this a user will see a `Could not determine the UTC offset on this system.` error when deploying this function out of the box.
---
> fix: update Rust template

- src/commands/base-command.ts
- src/commands/env/env-list.ts
- src/commands/types.d.ts
- src/utils/command-helpers.ts
- tests/integration/commands/dev/dev.config.test.js
Follow-up to https://github.com/netlify/cli/pull/6226#discussion_r1444364865. Adds typescript types to `cachedConfig.env`!
> refactor: type cachedConfig.env

- src/lib/build.ts
- src/utils/feature-flags.ts
- src/utils/run-build.ts
This is needed to rollout the next runtime version in the CLI through the feature flags as well
Fixes https://linear.app/netlify/issue/FRA-139/rollout-the-new-runtime
---
> feat: pass feature flags down to netlify build on dev

- STYLEGUIDE.md
- src/commands/api/api.ts
- src/utils/styles/index.ts
This converts the `api` command into using the new `NetlifyLog`. It is part of a bigger piece of work that can be seen in https://github.com/netlify/cli/pull/6293. This is also the reason why this PR is merged into the branch [CP-101/design-system-clack-implementation](https://github.com/netlify/cli/tree/CP-101/design-system-clack-implementation). It's a way in which I'm trying to keep possible failing tests, but also the review work to a minimum amount of work for those who are reviewing.
---
> chore: convert api command to use clack

- src/functions-templates/rust/hello-world/src/main.rs
The `handler_fn` function was deprecated in 0.5.0 of the lambda_runtime in favour of the `service_fn`.
Although removed from the function signature, the `Context` object is still available on the `Event` as a property (`event.context`)
---
> feat: update Rust template

- STYLEGUIDE.md
- src/commands/api/api.ts
- src/commands/link/link.ts
- src/commands/unlink/unlink.ts
- src/utils/styles/chalk.ts
- src/utils/styles/helpers.ts
- src/utils/styles/index.ts
Fixes: https://linear.app/netlify/issue/CT-477/convert-link-command-to-clack
This converts the `link` command into using the new NetlifyLog. It is part of a bigger piece of work that can be seen in https://github.com/netlify/cli/pull/6293. This is also the reason why this PR is merged into the branch [CP-101/design-system-clack-implementation](https://github.com/netlify/cli/tree/CP-101/design-system-clack-implementation). It's a way in which I'm trying to keep possible failing tests, but also the review work to a minimum amount of work for those who are reviewing.
It also changes a few things for `outro()`
I'm sorry it's a looot of screenshotting otherwise
https://github.com/netlify/cli/assets/30577427/dac544e7-c0e7-4920-8ad6-d26c63532d50
---
For …
> chore: convert link command

- src/commands/addons/addons-auth.ts
- src/commands/base-command.ts
- src/commands/build/build.ts
- src/commands/deploy/deploy.ts
- src/commands/integration/deploy.ts
- src/commands/login/login.ts
- src/commands/logout/logout.ts
- src/commands/open/open-admin.ts
- src/commands/open/open-site.ts
- src/commands/status/status.ts
- src/utils/command-helpers.ts
- src/utils/gh-auth.ts
- src/utils/open-browser.ts
Fixes: https://linear.app/netlify/issue/CT-478/convert-login-command-to-clack
This converts the `login` command into using the new NetlifyLog. It is part of a bigger piece of work that can be seen in https://github.com/netlify/cli/pull/6293. This is also the reason why this PR is merged into the branch [CP-101/design-system-clack-implementation](https://github.com/netlify/cli/tree/CP-101/design-system-clack-implementation). It's a way in which I'm trying to keep possible failing tests, but also the review work to a minimum amount of work for those who are reviewing.
---
> chore: convert login command

- src/commands/logout/logout.ts
Fixes: https://linear.app/netlify/issue/CT-501/convert-logout-command-to-clack
This converts the `logout` command into using the new NetlifyLog. It is part of a bigger piece of work that can be seen in https://github.com/netlify/cli/pull/6293. This is also the reason why this PR is merged into the branch [CP-101/design-system-clack-implementation](https://github.com/netlify/cli/tree/CP-101/design-system-clack-implementation). It's a way in which I'm trying to keep possible failing tests, but also the review work to a minimum amount of work for those who are reviewing.
---
> chore: convert logout command

- src/commands/functions/functions-create.ts
Fixes CT-497
We've had Rust support for a while but were not showing it as an option in the `functions:create` list of 'hello world' templates unless the `NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE` environment variable was set on the site.
These changes:
- Show Rust in the list of languages without consideration for the `NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE` environment variable
- Update the log output to tell the user to set this environment variable should they decide to use Rust
---
> feat: show Rust as option in functions:create

- src/commands/status/index.ts
- src/commands/status/status-hooks.ts
- src/commands/status/status.ts
Converts status command to clack
Before:
After:
---
> feat: convert status command to clack

- src/commands/open/open-admin.ts
- src/commands/open/open-site.ts
- src/commands/open/open.ts
Fixes https://linear.app/netlify/issue/CT-480/convert-open-command-to-clack
This converts the`open` command into using the new NetlifyLog. It is part of a bigger piece of work that can be seen in https://github.com/netlify/cli/pull/6293. This is also the reason why this PR is merged into the branch [CP-101/design-system-clack-implementation](https://github.com/netlify/cli/tree/CP-101/design-system-clack-implementation). It's a way in which I'm trying to keep possible failing tests, but also the review work to a minimum amount of work for those who are reviewing.
---
> chore: convert open command

- src/lib/edge-functions/proxy.ts
- src/lib/edge-functions/registry.ts
- src/lib/functions/runtimes/js/index.ts
- src/utils/feature-flags.ts
Feature flags coming from the site info are not being surfaced to the edge functions registry. This PR fixes that.
> feat: expose site feature flags to EF registry

- STYLEGUIDE.md
- src/commands/logs/build.ts
- src/commands/logs/functions.ts
- src/commands/open/open-admin.ts
- src/commands/open/open-site.ts
- src/commands/open/open.ts
- src/utils/styles/index.ts
- tests/integration/commands/logs/functions.test.ts
Fixes: https://linear.app/netlify/issue/CT-479/convert-logs-command-to-clack
This converts the `logs` command into using the new NetlifyLog. It is part of a bigger piece of work that can be seen in https://github.com/netlify/cli/pull/6293. This is also the reason why this PR is merged into the branch [CP-101/design-system-clack-implementation](https://github.com/netlify/cli/tree/CP-101/design-system-clack-implementation). It's a way in which I'm trying to keep possible failing tests, but also the review work to a minimum amount of work for those who are reviewing.
https://github.com/netlify/cli/pull/6325 was also merged into this branch which converts the open command to clack
---
For us to review and ship your PR efficiently, please perform the …
> chore: convert log command

- STYLEGUIDE.md
- src/commands/init/init.ts
- src/commands/link/link.ts
- src/commands/sites/sites-create.ts
- src/commands/unlink/unlink.ts
- src/commands/watch/watch.ts
- src/utils/init/config-manual.ts
- tests/integration/commands/init/init.test.js
- tests/integration/commands/sites/sites.test.ts
- tests/integration/utils/handle-questions.js
Converts watch and init commands to clack. Also, adjusts styling for the outro of unlinking.
Watch, where you link to existing site:
Watch, where site already linked:
Watch, where site gets created:
Link:
Also contains guidance so we avoid having multiple intros and outros like this: 
> chore: converts watch and init commands to clack

- src/commands/sites/sites-create.ts
- src/commands/sites/sites-delete.ts
- src/commands/sites/sites-list.ts
- src/utils/styles/index.ts
convert sites:list and sites:delete to clack
> chore: convert sites:list and sites:delete to clack

- src/commands/init/init.ts
Ensures clack intro is not repeated during the `init` command, when the site is created when no git remote is found
Before:
After:
---
> Fix no git path for init command

- src/utils/deploy/upload-files.ts
- tests/unit/utils/deploy/upload-files.test.js
When uploading a function, a 4xx error code means there's something wrong in the function itself and cannot be uploaded. Currently we keep retrying in all cases, but in some we shouldn't as it won't make a difference. This makes it so we retry only if it's not a 400 or 422.
Part of https://github.com/netlify/functions-origin/issues/358
This is an updated version of https://github.com/netlify/cli/pull/5963
---
> fix: do not retry uploads on 4xx errors

- src/commands/sites/sites-create-template.ts
- src/commands/sites/sites-create.ts
- src/utils/init/config-github.ts
- src/utils/sites/utils.ts
> chore: in progress of converting command having updated types

- src/commands/dev/dev.ts
- src/utils/headers.ts
- src/utils/proxy.ts
- src/utils/redirects.ts
- src/utils/rules-proxy.ts
- src/utils/run-build.ts
- tests/integration/commands/dev/dev-forms-and-redirects.test.js
- tests/integration/rules-proxy.test.ts
Reimplements @lukasholzer 's code from https://github.com/netlify/cli/pull/5546 which went stale and out of date. That part covered headers. 
My changes ported that, added support for redirects, and added additional checks for this behavior in a *Dev test.
Fixes https://github.com/netlify/cli/issues/5544
> This PR only parses the headers but we might want to do the same for redirects in a follow up or other config mutations not sure what frameworks needs here?
Currently, if you use the *Dev events, config changes within the callbacks are not applied. 
This PR does not include the ability to watch for these file changes and reapply the new config on file changes while dev is running. Meaning the config will get included on the first pass but it …
> fix: fix use headers/redirects that are set via the onPreDev of a plugin

- src/utils/deploy/hash-fns.ts
Reads the `priority` field from the functions manifest and sets it on the `functions_config` object on new deploys.
Part of COM-327.
> feat: set `priority` field on functions

- src/lib/functions/form-submissions-handler.ts
- src/utils/proxy.ts
- tests/integration/commands/dev/dev-miscellaneous.test.js
- tests/integration/commands/dev/dev.zisi.test.js
Resolves https://linear.app/netlify/issue/COM-366/ntl-dev-intercepts-all-form-submissions.
We're currently sending all form submissions (POST requests with the right content-type) towards the functions server, which will call the `submission-created` handler if it exists. That breaks frameworks like Remix that make heavy use of form submissions, because those requests aren't passed through to the framework server!
This PR fixes this, by only sending form submissions to the functions server if there's a submission handler registered.
---
> fix: only intercept form submissions if form handler is configured

- src/lib/functions/server.ts
- tests/integration/commands/dev/edge-functions.test.ts
- tests/integration/commands/functions-with-args/functions-with-args.test.js
We were changing the encoding of the incoming query string unnecessarily, turning `?1,2,3` into `?1%2D2%2D3` where it could've stayed as `?1,2,3`. This PR fixes that.
Part of https://linear.app/netlify/issue/COM-314/prevent-re-ordering-query-params-in-edge-functions.
---
> fix: dont touch query params encoding for ef and funcs

- tests/integration/__fixtures__/dev-server-with-v2-functions/functions/stream.js
We have an integration test that's a little flaky on CI. I'm not sure what's causing that, but I have a hunch that we're sending the two chunks fast enough that a busy CI runner will see them batched together. Let's see if this CI runs better!
Resolves https://linear.app/netlify/issue/COM-373/unflake-cli-test-for-streaming
> chore: increase timeout for streaming test

- src/commands/base-command.ts
If you had a monorepo and you did `cd apps/my-app` and then run `ntl build` the `PACKAGE_PATH`  was not set which leads to build failures for build plugins that rely on this monorepo configuration.
Now the PACKAGE_PATH constant will be set on those builds as well
Fixes https://linear.app/netlify/issue/FRA-350/enoent-no-such-file-or-directory-open-vartasknextbuild-id
---
> fix: an issue where the package path was missing when the cwd was not on the root

- package-lock.json
- package.json
- src/commands/recipes/recipes.ts
- src/lib/blobs/blobs.ts
- src/lib/edge-functions/editor-helper.ts
- src/recipes/blobs-migrate/index.ts
- tests/integration/commands/blobs/blobs.test.ts
- tests/integration/commands/recipes/__snapshots__/recipes.test.js.snap
Adds a new `blobs-migrate` recipe that lets folks migrate a Netlify Blobs store as they update to version 7.0.0 of `@netlify/blobs`.
Keeping this as draft until https://github.com/netlify/blobs/pull/148 is merged and the `@netlify/blobs` dependency is updated.
Part of ADN-370.
> feat: add `blobs-migrate` recipe

- src/commands/blobs/blobs-list.ts
Gracefully handles the case of an empty store in the `blobs:list` command.
_Before_
_After_
Closes COM-302
> fix: handle empty store on `blobs:list`

- .eslintrc.cjs
- src/commands/base-command.ts
- src/commands/deploy/deploy.ts
- src/commands/dev/dev.ts
- src/commands/serve/serve.ts
- src/lib/edge-functions/deploy.ts
- src/lib/edge-functions/proxy.ts
- src/lib/edge-functions/registry.ts
- src/lib/settings.ts
- src/utils/deploy/deploy-site.ts
- src/utils/deploy/hash-fns.ts
- src/utils/proxy-server.ts
- src/utils/proxy.ts
- tests/integration/commands/sites/sites.test.ts
- tests/unit/utils/deploy/hash-fns.test.js
Fixes broken deploys when run with `ntl deploy --build --skip-functions-cache` inside monorepos.
As the `getPathInProject` function is not monorepo aware, this breaks on monorepos.
There are more areas that depend on this function, but I'll do this in follow-up PRs to keep the PR size small.
Fixes https://linear.app/netlify/issue/FRA-385/could-not-resolve-vartaskappsdocsnetlifydistrunhandlerstracingjs
---
> fix: broken deploy with --skip-functions-cache

- src/lib/edge-functions/registry.ts
In #6276, we have started to trace transitive dependencies of edge function files for the purpose of hot reloading. This has introduced a regression where, for non-trivial dependency trees, we'll get into an infinite loop trying to recursively trace the dependencies of interdependent files.
This PR addresses that by ensuring we don't trace the same file twice.
Fixes COM-506.
> fix: cache edge function dependency tracing

- src/lib/functions/server.ts
- tests/integration/__fixtures__/dev-server-with-functions/functions/scheduled-v2.mjs
- tests/integration/commands/dev/scheduled-functions.test.ts
> fix: improve handling of scheduled v2 functions

- src/commands/base-command.ts
- src/commands/serve/serve.ts
- src/lib/edge-functions/proxy.ts
- src/lib/edge-functions/registry.ts
- src/lib/settings.ts
- src/utils/proxy.ts
Fixes https://linear.app/netlify/issue/COM-549/monorepo-with-edge-functions-ssr-returning-404-since-cli-v-17193
Fixes a regression that was introduced with #6433 
---
> fix: a regression in ntl serve with the package path

- src/lib/blobs/blobs.ts
- tests/integration/commands/dev/dev.config.test.js
Adds `uncachedEdgeURL` to local Blobs context for `ntl dev` and `ntl serve`.
Fixes COM-551.
> fix: add `uncachedEdgeURL` to Blobs context

- src/utils/detect-server-settings.ts
- tests/integration/__snapshots__/framework-detection.test.js.snap
When the framework isn't detected, a message is printed to stdout. Currently, this includes a link to a page that provides no useful information about framework detection. This replaces the URL with an actionable one.
---
> fix: replace bad doc URL in output

- package-lock.json
- package.json
- src/commands/deploy/deploy.ts
- src/lib/build.ts
- src/lib/edge-functions/bootstrap.ts
- src/lib/edge-functions/proxy.ts
- src/utils/run-build.ts
- tests/unit/lib/edge-functions/bootstrap.test.js
Rather than having to manually update the version of the edge functions bootstrap every time there's a new release, this PR loads the bootstrap URL from the `@netlify/edge-functions` module. When there's a new version of the bootstrap, we'll release a new version of the module and Renovate will kick the usual update routine, meaning we'll have a semi-automated way of keeping the bootstrap up-to-date.
> feat: load edge functions bootstrap from module

- src/commands/dev/dev.ts
- src/commands/functions/functions-serve.ts
- src/commands/serve/serve.ts
- src/lib/blobs/blobs.ts
- src/lib/edge-functions/proxy.ts
- src/lib/functions/netlify-function.ts
- src/utils/proxy-server.ts
- src/utils/run-build.ts
`netlify serve` is a bit special in that it first runs a build and then starts a server. In production, these steps have different Blobs contexts — API access should be used at build time and edge access should be used at runtime. This PR makes the `serve` command respect that.
Part of COM-580.
> fix: use the right Blobs context in `serve`

- package-lock.json
- package.json
The `get-port` dependency update has been reverted back to `5.1.1` as users were reporting that they were not able to acquire ports that they required as part of their development workflow. One such port that was affected was `443`, but others around that range were also affected.
> fix: revert get-port dependency update

- tests/integration/commands/dev/dev.test.ts
A PR to skip tests for external contributors where the test requires the Netlify account to make requests to the server
Fixes #<replace_with_issue_number>
---
> chore: skip blob tests if live

- .github/workflows/e2e-tests.yml
- .github/workflows/integration-tests.yml
- tests/integration/framework-detection.test.js
Caught as part of - https://github.com/netlify/cli/pull/6565 - seems like there's a regression on latest node 20 which doesn't npm in the release see:
- https://github.com/nodejs/node/issues/52682#issuecomment-2100193247
- https://github.com/nodejs/node/issues/52884
---
> chore(ci): windows node 20 regression

- src/utils/open-browser.ts
Added TS to open-browser file. I couldn't find any `@types/open-browser` package in the DefinitelyTyped repo, so left the @ts-expect-error. 
---
> chore: added TS to open-browser file

- src/lib/blobs/blobs.ts
- src/lib/functions/netlify-function.ts
Sets the right metadata properties in the Blobs context for the `experimentalRegion` property to work correctly in the `serve` command.
Fixes FRA-503.
> fix: set Blobs region in `serve` command

- src/utils/gh-auth.ts
After authenticating in the browser, the CLI renders this page: ![Screenshot 2024-05-14 at 17 10 28](https://github.com/netlify/cli/assets/1377702/b0bc9b2e-8396-4f71-9df4-421dc56d43ca)
This gives a bit of a bad first impression!
The better fix might be to set the right encoding on the response or something, but this seemed easy enough for now.
---
> fix: fix funky apostrophe on "now logged in" page

- src/lib/functions/server.ts
- tests/integration/commands/dev/dev-miscellaneous.test.js
Fixes CT-1153
Following this change by Netlify: https://answers.netlify.com/t/deprecating-automatic-com-redirects/115442
---
> Locally emulated Identity service URL should use .app

- tests/integration/commands/dev/dev-miscellaneous.test.js
Fixes tests for https://github.com/netlify/cli/pull/6235
See [discussion](https://github.com/netlify/cli/pull/6235#discussion_r1596798506) for more information on the behaviour
We opted to skip the test on windows as edge functions will not be hosted on windows machines in production, and during local development there is no need for a short refresh window (< 1s)
Confirmed test passes / gets skipped on windows with these changes
---
> test: skip test on windows due to unexpected fetch behaviour

- src/lib/functions/server.ts
- src/utils/functions/functions.ts
Fixes [#CT-1145](https://linear.app/netlify/issue/CT-1145/internal-functions-not-running-locally-in-monorepos)
`ntl serve` was skipping including `functions-internal`, `functions-dist`, and `functions-serve` because it wasn't able to locate them. Adding the package path into the function call resolves the issue.
Tested with a next monorepo
Before:
After:
(Even though it's an error, we know it's being registered now)
> fix: serve function support in monorepos

- src/commands/functions/functions-create.ts
Fixes CT-1060
When creating an edge function from a template, we weren't awaiting the step where we prompted the user for the route to register the edge function on, leading to the prompt being interrupted by the "Function created!" success message as the rest of `scaffoldFromTemplate` executed. This sometimes appeared as the CLI hanging, since the prompt for user input was no longer on the last line, making it easy to overlook that the CLI was waiting for user input.
Unfortunately, difficult to test for this without reworking the `handleQuestions` test helper, which seems daunting right now 😬   
---
here is my cat playing a …
> fix: un-awaited prompt when creating edge function from template  

- src/commands/env/env-get.ts
- src/utils/env/index.ts
Resolves https://linear.app/netlify/issue/CT-1215/%5Bbug%5D-cli-throwing-envelopeitems-error.
> fix: crash on `envelopItems.filter`

- src/utils/proxy.ts
Tweak which requests are considered activity. Now we filter out redirects (including to internal plugins) and non-GET requests.
ref CRE-1189
---
> fix: dev server - tweak which requests are considered activity

- package-lock.json
- package.json
- src/lib/edge-functions/headers.ts
- src/lib/edge-functions/proxy.ts
- tests/integration/commands/dev/dev-miscellaneous.test.js
- tests/integration/commands/dev/edge-functions.test.ts
- tests/integration/commands/dev/v2-api.test.ts
Part of https://linear.app/netlify/issue/FRP-753/expose-deploy-context-and-published-state-to-functions-and-edge.
> feat: expose deploy context to functions and edge functions

- src/utils/dev.ts
Fixes #6125
When a site has a custom timelimit for functions, its exposed as `function_timelimit` directly on the site object returned from the API. The current CLI code always tries to read it from the generic function_config hash if one is present.
---
> fix: load functions timeout from site properly

- src/utils/dev.ts
Fixes FRP-1293, changing the default local timeout to 30s
🦫
> fix: increased the default functions timeout to 30s

- .github/workflows/integration-tests.yml
- package-lock.json
- tests/integration/commands/deploy/deploy.test.ts
Contains https://github.com/netlify/cli/pull/6824 + https://github.com/netlify/cli/pull/6822 + some test adjustments to decrease some flakiness
---
> fix(deps): bump find-my-way from 8.2.0 to 8.2.2 and vite from 5.2.10 to 5.4.6

- package-lock.json
- package.json
Because almost every package uses lodash, we always happened to have a copy of @types/lodash end up at the root of our `node_modules` due to a transitive dependency, so this worked out.
I confirmed this fixes that branch locally. I didn't wanna push to it unnecessarily since then Dependabot would stop auto-rebasing it and I am lazy. 😄
> chore(deps): add missing @types/lodash dev dependency

- src/commands/deploy/deploy.ts
- tests/integration/commands/deploy/deploy.test.ts
Follow-up to https://github.com/netlify/cli/pull/6851.
You can see here it says "Show logs for deploy...": https://app.netlify.com/sites/hydrogen-advanced-caching/logs/edge-functions?scope=deployid:6705473738103f2856071dbd.
This doesn't work with `?scope=deploy:`.
This is a bit of a footgun since the Functions log URL takes `deploy:` but the Edge Functions log URL takes `deployid:`. 😓
> fix(deploy): fix edge function logs url scope key

- .github/workflows/vale.yml
Fixes DOC-1029 by pinning the ubuntu image to 22.04 for the Vale lint docs action. Similar to what we've done for the [SDK](https://github.com/netlify/sdk/pull/1819) and [docs](https://github.com/netlify/docs/pull/4194) repos. 
I'll keep the action disabled for now so that it doesn't impact other PRs but will re-enable it after this is merged and confirm that it works. 
Background info:
- https://github.com/errata-ai/vale-action/issues/128
- https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/
---
> ci: fix vale by pinning the ubuntu image to 22.04 

- src/commands/sites/sites-create-template.ts
- src/utils/gh-auth.ts
This PR implements two small changes to the `sites:create-template` command to make it more user-friendly.
1. When user validates with GitHub personal access token, the PAT is hidden from the console, so as to protect these sensitive credentials.
2. If creating a GitHub repo fails because of a possible PAT issue, the error output reads "GitHub personal access token" rather than "GitHub PAT"
These are both suggestions from internal Netlify folks. Thanks for the feedback!
---
> fix: make outputs more user-friendly for `sites:create-template`

- .github/workflows/integration-tests.yml
- src/utils/framework-server.ts
- src/utils/static-server.ts
- tests/integration/commands/dev/dev.test.ts
- tests/unit/utils/copy-template-dir/copy-template-dir.test.js
This hopefully fixes this: https://answers.netlify.com/t/128792
I noticed, while running this on windows in a VM, that the proxy was trying to connect to an IPv4 server, while the static server was actually an IPv6 one. 
With this logic, we explicitly check what version we are running within the `settings.useStaticServer` branch of logic as well. 
---
> fix: check ip version if settings.useStaticServer

- .github/workflows/benchmark-post.yml
- .github/workflows/benchmark.yml
The `post-package-size` action isn't a required step, but it is annoying that it fails when it doesn't need to fail, and can make engineers spend too much time in slack threads trying to figure out what is going on. This will hopefully prevent that although long slack threads are fun and maybe we shouldn't avoid them?
Oh also this action hasn't even been working for 7 months because we upgraded to `actions/upload-artifact@v4` which ignores hidden files by default whereas v3 didn't, and all our `.delta.*` files are hidden. lol
> chore: fix the CI benchmarks posting and also exit gracefully if not even relevant

- bin/run.js
- src/commands/base-command.ts
- src/commands/sites/sites-create-template.ts
- src/commands/sites/sites-create.ts
- src/commands/status/status.ts
- src/commands/types.d.ts
- src/utils/types.ts
We're calling the non-minimal accounts API in `@netlify/config` and including it in the object returned from `resolveConfig`. Then we were doing it a second time in the CLI on a few different commands. The non minimal endpoint is really expensive so this saves a good chunk of time (a couple seconds in my testing).
---
> fix: remove extra call to accounts endpoint across cli

- src/utils/proxy.ts
- tests/integration/commands/dev/redirects.test.ts
- tests/integration/utils/fixture.ts
Hides this functionality under env var for better control/transition period while discussing it
---
> fix: hide dynamic ssg endpoint resolution under environment variable

- src/commands/recipes/recipes.ts
- src/recipes/ai-context/context.ts
- src/recipes/ai-context/index.ts
- tests/integration/commands/recipes/__snapshots__/recipes.test.js.snap
- tests/unit/recipes/ai-context/context.test.ts
Adds a `ai-context` recipe that creates context files for AI tools.
Usage:
- `ntl recipes ai-context <directory>`: Saves context files on the given directory
- `ntl recipes ai-context`: Prompts the user for the location of where the context files should be placed
> feat: add `ai-context` recipe

- src/utils/proxy.ts
- tests/integration/commands/dev/redirects.test.ts
For dev servers context, whenever the env var `NETLIFY_DEV_SERVER_CHECK_SSG_ENDPOINTS` is used (currently by dev server), skip the checks for the endpoint existence in case `hidden-proxy` header present.
Redirect works, but because of the endpoint check - it makes unnecessary request for the current server, which produces in case of remix unnecessary console output. For instance, when used with plugin-dev-server, which has redirect:
```
{
from: `/.ntlfy-dev/*`,
to: `http://localhost:${port}/:splat`,
status: 200,
headers: {
'x-nf-hidden-proxy': 'true',
},
}
```
Has next output when something tries to fire a request to `/.ntlfy-dev/health`
---
**A …
> fix: skip checking for endpoint existence for hidden redirects

- .github/workflows/format.yml
- .github/workflows/lint.yml
Whoops. I split up a job in https://github.com/netlify/cli/pull/7069, but it turns out if your workflow is invalid, it doesn't even report as failed. And I hadn't marked the new jobs as required yet. 🤦🏼
**Note:** Now that these jobs have run successfully once on this PR, I was able to mark the checks as required.
> ci: fix new job config

- .github/workflows/pre-release-sha.yml
This changeset adds a workflow that allows an operator to publish an ad-hoc version of the CLI by specifying a SHA.
> ci: add pre-release-sha workflow

- .github/workflows/verify-docs.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
- site/netlify.toml
- site/netlify/functions/error-reporting.ts
- site/netlify/functions/telemetry.js
- site/package-lock.json
- site/package.json
- site/scripts/docs.js
- site/scripts/sync.js
- site/scripts/util/generate-command-data.js
This change moves the site `netlify.toml` to the `site/` directory.
Previously, the site-build workflow went like this:
- Netlify Build executed `npm install` at the root of the project (by default)
- After package installation, the `postinstall` hook triggered a CLI build
- Netlify Build would execute `netlify.toml#build.command`, which:
- Entered the docs directory
- Ran `npm install` against `docs/package.json`
- Ran a site build (which implicitly relied on the root directory `npm install` and `npm run build` steps)
To make this change, I modified the logic to:
- Netlify Build starts in the `site/` directory and executes `npm install`
- `site/netlify.toml#build.command`  enters the root and preps the CLI, then returns to the `docs/` directory
- We then build the site
In this way, the …
> build: relocate site netlify.toml to site/ directory

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
- package.json
This changeset splits the lint and format tasks--formerly run as part of the unit test job--into their own CI jobs.
> ci: split lint, format tasks into jobs

- docs/commands/logs.md
- docs/commands/serve.md
- docs/index.md
- src/commands/logs/index.ts
These have all been stable for a while. We just forgot to remove these beta indicators.
> fix(docs): remove beta indicator from stable commands

- package-lock.json
- package.json
- scripts/prepare-for-publish.js
- src/commands/deploy/deploy.ts
- src/commands/functions/functions-create.ts
- src/commands/sites/sites-list.ts
- src/commands/watch/watch.ts
- src/lib/api.ts
- src/lib/edge-functions/proxy.ts
- src/lib/spinner.ts
- src/utils/deploy/deploy-site.ts
- src/utils/framework-server.ts
- src/utils/shell.ts
This should reduce our package size a bit, which is huge. See https://github.com/es-tooling/module-replacements/blob/main/docs/modules/ora.md.
I also added some missing types along the way.
> fix(deps): replace `ora` and `log-symbols` with tiny dependency `picospinner`

- tools/e2e/setup.js
The E2E test script unexpectedly runs a `git checkout .` on the CLI repository. If you run it locally and have any uncommitted changes, oops! It just discarded your work.
https://github.com/netlify/cli/pull/7119 removes the `package.json#scripts` pre-publish mangling that we used to do, which is ostensibly why we needed this in the first place.
> test: don't reset workspace when running E2E tests

- src/utils/shell.ts
This was a small regression introduced in https://github.com/netlify/cli/pull/7026.
I didn't quite map the previous lib's API to nanospinner's correctly.
The intent here is to manually control each frame render and each clear. Instead, the spinner here was already started before it's passed in to this method, then it was cleared and started again on each chunk - but `start()` here would start a new interval loop and set up new node.js exit listeners but `clear()` wouldn't clear them (`reset()` does that).
This was leading to unnecessary resource utilization and printing warnings like this:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use node …
```
> fix: avoid starting and stopping spinner loops

- package.json
See https://github.com/netlify/cli/issues/7141.
This will be faster than reverting a bunch of stacked PRs, and it's been too long to unpublish from the NPM registry.
> fix: temporarily remove broken postinstal hook

- .github/workflows/codeql.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/format.yml
- .github/workflows/integration-tests.yml
- .github/workflows/lint.yml
- .github/workflows/typecheck.yml
- .github/workflows/unit-tests.yml
- .github/workflows/vale.yml
- .github/workflows/verify-docs.yml
This changeset modifies the CI test workflows to not run on release PRs.
One effect this PR will have is that these workflows will no longer
report a status on release-please PRs. Because we have our repo rules
configured to require these workflows' jobs to block merges to main
unless these workflows are in a passing state, merging this as is will
break release-please branches. To fix this, we'll modify the
merge-to-main ruleset to exclude the release-please bot user from the
ruleset's requirements.
> ci: simplify release-please conditionals

- .github/workflows/release-please.yml
This is technically a `test` scope, but I'm giving it a fix so it triggers a release.
> fix: run E2E tests before publishing package

- vitest.config.ts
I'm pretty sure part of why our integration tests are so flaky is because e.g. the Next.js tests frequently take about 60s in CI. I think by increasing the timeout, we'll greatly reduce the amount of times our test suites flake due to timeout (when they'd pass if we just gave them more time), triggering a full-suite retry.
> test: increase test timeouts

- package.json
- scripts/prepublishOnly.js
We accidentally reintroduced dev dependencies in the `npm-shrinkwrap.json` file here: https://github.com/netlify/cli/pull/7119/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.md&file-filters%5B%5D=.yml&show-viewed-files=true&show-deleted-files=false#diff-3d80e6f9eb8af7a28cbe2209d086150e29b68f860376ee618a0041ca9b5c786dL18-L49.
The deleted script was deleting `package.json#devDependencies` before running `npm i && npm shrinkwrap`, which resulted in the shrinkwrap being built from a modified `package-lock.json` with dev deps removed 😓.
cc @ndhoule
> fix(npm-shrinkwrap.json): re-remove dev deps

- package-lock.json
- package.json
- src/commands/base-command.ts
- src/commands/sites/sites-create-template.ts
- src/commands/status/status.ts
- src/commands/types.d.ts
- src/lib/build.ts
- src/utils/types.ts
- tests/integration/commands/status/__snapshots__/status.test.ts.snap
- tests/integration/commands/status/status.test.ts
:warning: Depends on https://github.com/netlify/build/pull/6184. Merge and release that change first, and update the `@netlify/config` dependency in this PR to a non-RC release.
---
We've done this performance improvement many times elsewhere, but for posterity:
When we load a user's configuration, we perform a query to the Netlify API requesting information about which accounts a user is a member of. To do this, we query the `/accounts` endpoint, which is an expensive operation: It frequently takes 4+ seconds to get a response from this endpoint. This query happens as part of every CLI startup cycle.
By requesting a more minimal set of `accounts` data, we reduce almost every command's startup time.
Non-scientific testing shows this reduces `netlify status` runtime (on a Netlify dev's …
> perf!: perform minimal accounts query when loading config

- src/lib/functions/server.ts
- src/lib/functions/synchronous.ts
The types fixes in https://github.com/netlify/cli/pull/7130 identified a number of bugs. This fixes one of those.
> fix(functions): await functions error handling

- package-lock.json
- package.json
- src/lib/build.ts
- src/lib/edge-functions/registry.ts
This changeset updates `@netlify/config` to fix an error in `netlify link` where we sometimes print `undefined` in place of site information.
This addresses the root issue, but I'll create a follow-up PR that addresses the root issue (bad types).
> fix: print site information in `link` output

- tests/integration/utils/fixture.ts
We [bumped this up globally here](https://github.com/netlify/cli/pull/7154) but it didn't take everywhere because of this override.
You can see this run timing out after 30s for example: https://github.com/netlify/cli/actions/runs/14249390219/job/39938265313#step:10:381.
This should help with flakiness, especially since integration tests that use fixtures can be quite slow on Windows.
> build: remove test hook timeout override

- tests/integration/__snapshots__/framework-detection.test.js.snap
- tests/integration/framework-detection.test.js
- tests/integration/utils/snapshots.js
This logic was normalizing integration test snapshots by replacing any sequence of five digits with `88888`. The intent is to handle some randomness in test output.
It wasn't working some percentage of the time because randomly selected ports are sometimes _four_ digits. You can see an example in this failed run: https://github.com/netlify/cli/actions/runs/14434953424/job/40474516002?pr=7202#step:10:1143.
While I was at it, I made it less much less generic and moved it into the only test suite that relies on it.
> test: fix flakey snapshot normalization logic

- eslint_temporary_suppressions.js
- src/utils/init/config-github.ts
- src/utils/init/config-manual.ts
The types fixes in https://github.com/netlify/cli/pull/7130 identified a number of issues. This fixes one of those — just some unused args passed to a function.
> refactor: remove unused args in calls to `getBuildSettings`

- .github/workflows/e2e-tests.yml
We have this incantation in the integration test setup, and e2e tests are _excruciatingly_ slow on Windows (4-7 mins PER TEST, vs. 400-900ms for Ubuntu/macOS), so let's give this a try.
> ci(e2e): add same Windows perf config as for integration tests

- eslint_temporary_suppressions.js
- src/commands/deploy/deploy.ts
- src/commands/functions/functions-list.ts
- src/commands/status/status.ts
- src/recipes/blobs-migrate/index.ts
- src/utils/types.ts
The types fixes in https://github.com/netlify/cli/pull/7130 identified a number of issues. This fixes a couple of issues.
- mark `siteInfo.published_deploy` as optional
- remove unnecessary handling of nullish `siteInfo`
- fix some nearby eslint suppressions
> fix: mark `siteInfo.published_deploy` as optional

- eslint_temporary_suppressions.js
- package-lock.json
- package.json
- src/lib/functions/server.ts
- src/utils/copy-template-dir/copy-template-dir.ts
- src/utils/shell.ts
- types/express-logging/index.d.ts
- types/maxstache-stream/index.d.ts
- types/maxstache/index.d.ts
There's also https://github.com/netlify/cli/pull/7050 that removes it entirely, but I don't want to be blocked on this to continue improving type safety.
`stripVTControlCharacters` was added in 16.11.0 (we support >+18.14.0), so we don't need this tiny transform stream wrapper anyway
> fix(deps): remove or type last remaining untyped deps

- src/commands/base-command.ts
- src/commands/deploy/deploy.ts
- src/commands/deploy/index.ts
- src/commands/deploy/option_values.ts
- src/lib/build.ts
This change adds basic TypeScript types to the `deploy` command's input arguments (i.e. the command-line flags that a user passes to the `netlify deploy` command).
I also lifted some input argument validation out of the `deploy` command's business logic into the `createDeployCommand` function as a minor optimization so we don't pull in the full deploy dependency tree when we know we can't service a user's request.
> refactor: type deploy command input args

- src/lib/account.ts
- src/lib/functions/server.ts
- src/lib/images/proxy.ts
- src/utils/dev.ts
- src/utils/proxy-server.ts
- tests/unit/lib/account.test.ts
- tests/unit/lib/images/proxy.test.ts
Two small follow-ups to type fixes in https://github.com/netlify/cli/pull/7199
> refactor: fix `Account.capabilities` and `parseAllRemoteImages` types

- src/commands/env/env-get.ts
- src/commands/env/env-list.ts
- src/commands/env/env-set.ts
- src/commands/env/env-unset.ts
- src/utils/env/index.ts
- tests/unit/utils/env/index.test.ts
In preparation for a bug fix, this refactors code paths related to fetching and filtering environment variables for the optionally user-specified context and/or scope.
This should be pretty self-explanatory. I just renamed variables for clarity, fixed some missing types, added some inline doc comments, and did some minor refactoring.
Feel free to review commit by commit.
> refactor(utils/env): rename variables, add comments, and clarify intent

- bin/run.js
- package-lock.json
- package.json
This polishes the look and brand of the CLI update available notification and adds a link to release notes.
When looking at the screenshots below, keep in mind they just show my own terminal background and colour configuration. These can vary, but we do use libraries that automatically adapt to available color space, support for OSC 8 terminal links, etc.
> feat: beautify CLI update available notification and link to release notes

- docs/commands/deploy.md
- src/commands/deploy/index.ts
- tests/integration/commands/deploy/deploy.test.ts
This updates the `deploy` command to run the configured `build` command before deployment by default. Previously, this was achieved by passing the `--build` flag.
To opt into the previous behavior, users can now specify `netlify deploy --no-build`.
This has long been one of the most common sources of confusion with the Netlify CLI. Developers expect a "deploy" command to deploy their project. We're making this change to follow the Principle of Least Surprise and streamline the experience for new users.
Remove the `--build` flag:
```sh
netlify deploy --build [...] # before
```
→
```sh
netlify deploy [...] # after
```
> [!WARNING]
> Make sure your deploy command runs in your expected environment, e.g. if you were running `FOO=bar netlify build && netlify deploy`, make sure `FOO` is visible …
> feat!: run build by default before deploy

- src/utils/framework-server.ts
- src/utils/shell.ts
This is a regression in the loading spinner shown before "Waiting for framework port", introduced in 19.0.3.
See:
1. https://github.com/netlify/cli/pull/7026
2. https://github.com/netlify/cli/pull/7131
3. https://github.com/netlify/cli/issues/7124
Oops, I was really overthinking this. All this needs to do is, every time a chunk comes in from the underlying framework dev server, clear the spinner line, write the chunk, then resume the spinner.
This wasn't set up right at all, which was obfuscated by the erroneous use of `isSpinning`.
Fixes #7124.
Thank you @Florian-Mt for spotting the (embarrassing!) fix.
> fix: fix framework server loading spinner ("Waiting for framework port")

- bin/run.js
- scripts/postinstall.js
- Use a pretty Netlify-cyan box with the Netlify diamond icon
- Mention `ntl login` as a likely first step
- Link to better CLI entrypoint URL
- Link to main Netlify docs
> fix: polish and improve postinstall onboarding message

- tests/integration/commands/dev/dev.test.ts
- tests/integration/commands/dev/serve.test.ts
These suddenly started failing when a new major was published.
I don't think there's any particular reason to use `*` here. It just adds nondeterminism to our CI.
> test: pin @netlify/blobs deps in test fixtures

- docs/commands/api.md
- e2e/install.e2e.ts
- eslint_temporary_suppressions.js
- src/commands/api/index.ts
- src/commands/blobs/blobs.ts
- src/commands/build/index.ts
- src/commands/completion/index.ts
- src/commands/deploy/index.ts
- src/commands/dev/index.ts
- src/commands/env/env-unset.ts
- src/commands/env/env.ts
- src/commands/functions/functions-create.ts
- src/commands/functions/functions.ts
- src/commands/init/index.ts
- src/commands/init/init.ts
- src/commands/link/index.ts
- src/commands/login/index.ts
- src/commands/logout/logout.ts
- src/commands/logs/build.ts
- src/commands/main.ts
- src/commands/open/open-site.ts
- src/commands/sites/sites.ts
- src/commands/switch/switch.ts
- src/commands/unlink/index.ts
- src/commands/unlink/unlink.ts
- tests/integration/commands/help/__snapshots__/help.test.ts.snap
- Link out to relevant Netlify core docs from command help, e.g. the `netlify blobs` commands' help now links to https://docs.netlify.com/blobs/overview/
- Polish the main CLI help and its links:
- always show the Netlify CLI header, not just in the bare `netlify` case (there is also `netlify help` and `netlify --help`, which was otherwise identical)
- use more consistent branding
- change CLI getting started landing page
- move the links to the bottom
- add link to main Netlify docs homepage
- these use OSC 8 terminal links, so they're always clickable in most modern terminals
`netlify help` or `netlify --help`:
In addition, the output started with this only when using the bare `netlify`:
Now, all three are the same:
See the new line at the very bottom here for example:
> feat: link out to relevant Netlify docs in command help output

- docs/commands/deploy.md
- src/commands/deploy/index.ts
- tests/integration/commands/deploy/deploy.test.ts
We have no plans to remove these, so let's not annoy users about it
> fix(deploy): remove messages about future deprecated flag removals

- bin/run.js
- src/commands/deploy/deploy.ts
- src/commands/sites/sites-list.ts
As in https://github.com/netlify/cli/pull/7249, this makes misc. improvements to the output of `ntl deploy`, in order to improve the signal-to-noise ratio, improve clarity, and make it a little more pleasant to look at:
- Move deploy URL to its own primary section in a Netlify-cyan callout box with distinctive diamond
- It's the primary call-to-action, so it should be the primary focus rather than be buried with the three other URLs
- It's a little more celebratory/satisfying
- Remove redundant "draft" vs. "production" line (mentioned in new box now)
- This incidentally fixes a rendering bug, where "Uploading blobs to deploy store" with a spinner gets frozen in a weird place
- Use OSC 8 "terminal links" when supported
- Suppress redundant blobs upload build output
- This was basically …
> fix: polish and improve deploy command output

- src/utils/shell.ts
Even after we've called `.success()` or `.stop()` on this spinner, we were continuing to render it when we receive output from the framework server.
> fix: actually stop spinning on success/failure

- src/commands/deploy/deploy.ts
Fix missing space in message shown after non-prod deploy.
Fixes https://github.com/netlify/cli/issues/7285.
> fix(deploy): fix typo in post-deploy message

- src/commands/blobs/blobs.ts
- src/commands/build/index.ts
- src/commands/clone/index.ts
- src/commands/deploy/deploy.ts
- src/commands/deploy/index.ts
- src/commands/dev/index.ts
- src/commands/env/env.ts
- src/commands/functions/functions.ts
- src/commands/init/index.ts
- src/commands/link/index.ts
- src/commands/login/index.ts
- src/commands/main.ts
- src/commands/unlink/index.ts
- tests/integration/commands/help/__snapshots__/help.test.ts.snap
The `terminal-link` package uses [OSC 8](https://github.com/Alhadis/OSC8-Adoption/) link formatting when running in a terminal that supports it. When it isn't supported, by default it falls back to rendering the text followed by the link in parens. This is fine, but when we pass the full URL as the text, it's unnecessarily noisy, e.g.:
```
Deployed to draft URL: https://my-example-site.netlify.app (https://my-example-site.netlify.app)
```
Passing `fallback: false` toggles the fallback behaviour to just render the text as-is, e.g.:
```
Deployed to draft URL: https://my-example-site.netlify.app
```
This wasn't clear previously from the docs: https://github.com/sindresorhus/terminal-link/pull/26.
> fix: improve link fallback when OSC 8 is not supported

- src/utils/command-helpers.ts
Currently, when the `netlify login` command successfully finishes or fails, we fail to stop the spinner correctly. The user must then SIGINT/Ctrl-C to exit. This change fixes that issue.
> fix: stop spinner after `netlify login`

- tests/integration/commands/deploy/deploy.test.ts
The API now returns a new URL format for `admin_url`, so tests started failing on all branches about an hour ago.
> test: update integration test `admin_url` expectations

- src/utils/proxy.ts
…oxying
Fixes double encoding and marking preview server activity.
---
> fix: avoid double encoding when notifying dev server of activity

- src/commands/init/init.ts
- src/commands/link/link.ts
- src/utils/command-helpers.ts
Changes the output of `init` and `link` commands to be aware of the npx/pnpx context they are being run in
Part of FRB-1840
---
> fix: make cli aware when run in npx/pnpx context

- src/lib/functions/netlify-function.ts
- src/lib/functions/runtimes/js/index.ts
- tests/integration/commands/dev/functions.test.ts
Fixes environment variables from build event handlers not being passed to functions during local development. Static config environment variables from `netlify.toml` were already working via global process environment injection, but variables added by plugins via build event handlers were not.
Build event handlers (like `onPreDev`) could successfully mutate the config to add environment variables to `config.build.environment`, but these **mutated** environment variables were not available to functions in `process.env` during local development.
**What was working:**
- Static environment variables from `netlify.toml` → `cachedConfig.env` → global `process.env` → functions ✅
- Build event handler mutations → `config.build.environment` ✅  
- Process env override behavior ✅
**What was …
> feat: pass mutated config environment variables to functions during local development

- .github/workflows/e2e-tests.yml
- .github/workflows/format.yml
- .github/workflows/integration-tests.yml
- .github/workflows/lint.yml
- .github/workflows/pre-release-sha.yml
- .github/workflows/typecheck.yml
- .github/workflows/unit-tests.yml
- README.md
- package-lock.json
- package.json
- site/package-lock.json
- src/lib/functions/netlify-function.ts
- src/utils/nodejs-compile-cache.ts
- tests/integration/commands/dev/dev.config.test.ts
- tests/integration/commands/dev/v2-api.test.ts
This removes support for node 18.x and 19.x
---
> feat!: drop support for node 18.x and 19.x

- .github/workflows/e2e-tests.yml
- .github/workflows/integration-tests.yml
- .github/workflows/unit-tests.yml
Update CI to use the latest windows runner available
Seems to have a positive impact on the flakiness of the e2e tests
Ran a few times without hitting a time out, meanwhile in another branch without this change I'm on attempt 20 in a row
---
> ci: use windows-2025 image

- src/utils/proxy.ts
If preview server does the proxy e.g. to internal routes or the user site proxy-all `*` - we not notifying activity.
---
> fix: notify activity called for any proxied request

- src/utils/proxy.ts
Some requests might come as HEAD and spamming them might create a lot of activity calls - this PR prevents it.
---
> fix: notify activity should not be called for the HEAD requests

- src/utils/proxy.ts
Found another issue where liveness check was triggering notify activity, which made the preview server never auto shutdown
---
> fix: notify activity was called for internal endpoints

- package-lock.json
Just ran `npm audit fix`. For some reason Dependabot couldn't figure this out on its own.
See https://github.com/netlify/cli/security/dependabot/282.
Previously, `npm audit` reported `1 low severity vulnerability` and Dependabot provided these details:
```
Transitive dependency brace-expansion 2.0.1 is introduced via
@fastify/static 7.0.4 
...
brace-expansion 2.0.1
@netlify/build 33.5.0
...
brace-expansion 2.0.1
@netlify/build-info 10.0.7
...
brace-expansion 2.0.1
@netlify/zip-it-and-ship-it 12.2.0
...
brace-expansion 2.0.1
@vitest/coverage-v8 3.1.1
...
brace-expansion 2.0.1
@vitest/eslint-plugin 1.2.0
...
brace-expansion 2.0.1
c8 10.1.3
...
brace-expansion 2.0.1
eslint-plugin-n 17.17.0
...
brace-expansion 2.0.1
npm-run-all2 7.0.2
...
brace-expansion 2.0.1
typescript-eslint 8.26.0
... …
```
> fix(deps): bump `brace-expansion` to resolve vulnerabilities

- src/commands/functions/functions-serve.ts
This adds an unstable, undocumented configuration knob that instructs `netlify functions:serve` to load dist bundles, rather than to build and serve local functions.
This configuration knob is useful for internal testing of SDK-injected functions.
> feat: add internal functions:serve load-dist-functions knob

- package-lock.json
- package.json
low risk cve, dependabot couldn't figure this one out https://nvd.nist.gov/vuln/detail/CVE-2025-7339
> fix(deps): add override for on-headers security update as verdaccio has compression 1.8.0 pinned

- src/utils/command-helpers.ts
Fixes #EX-386
Replaced logic that gets API token from global config store with `getAPIToken`. 
Ref: https://github.com/netlify/primitives/blob/main/packages/dev-utils/src/lib/api-token.ts#L3
> refactor: use getAPIToken from @netlify/dev-utils

- src/commands/dev/dev.ts
- src/utils/env/index.ts
- tests/integration/commands/env/env-set.test.ts
- tests/integration/commands/env/env-unset.test.ts
- tests/unit/utils/env/index.test.ts
This changeset fixes environment-variable loading a Preview Server context.
Previously, we were missing `dev-server` from the CLI's list of
supported contexts. Because of a variable that (unnecessarily) mixes the
concept of branches and contexts, when we run into an unsupported
context, we assume we must be running a branch preview, and try to find
variables for the branch named `dev-server`. For the majority of users,
variables for that branch won't exist, and they'll end up with an
unexpectedly empty variable.
Why do we assume it's a branch preview when we have enough information
available to us to know it's not one? Why do we throw away the type
information that would have caught this? Why do we load environment
variables from the API in the CLI even though `@netlify/config` already …
> fix: load correct environment variables in Preview Server context

- src/commands/deploy/deploy.ts
Adds support for non interactive TTY when running `netlify deploy`
---
> fix: support non interactive tty when deploying

- src/commands/agents/agents-create.ts
- src/commands/agents/agents-show.ts
- src/utils/hooks/requires-site-info-with-project.ts
- Update the agent runner links to use `projects` and `sideInfo.name`
- Fix `--project` argument 
---
> fix: agent runner links and project arg
